### PR TITLE
Fixed refresh token handling in OAuth flow

### LINKED ISSUE #1495: Fix "Re-auth" issue on the Google credential caused by the refresh token

### PR DESCRIPTION
**Pull request by benedictus-dev**
## Notes for the reviewer
This will prompt the user to authorize the application again and will always return a refresh_token.

## Related issue
The refresh_token is only provided on the first authorization from the user. Subsequent authorizationswill not return the refresh_token.
Fixes #1495 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning/auth_providers/google.ex [hunk 1]
```diff
@@ -85,7 +85,8 @@ defmodule Lightning.AuthProviders.Google do
     OAuth2.Client.authorize_url!(client,
       scope: scope,
       state: state,
-      access_type: "offline"
+      access_type: "offline",
+      prompt: "consent"
```
Comment (stuartc) [inline lib/lightning/auth_providers/google.ex:89]: Beautiful!

**Review by stuartc — APPROVED** [review]
