### PR TITLE
Fix dropped dataclip type pill and state assembler notice

### LINKED ISSUE #975: Dataclip type and state assembly notice for creating new dataclip dropped during refactor
Changes to how new dataclips are treated have broken the "type: saved input" label and the explanation of how state will be assembled for a new dataclip.

This is how it looked prior to v0.7.0

image

And this is how it looks now - hiding the labels between the code editor and dropdown:
image

The section which describes the dataclip type (with a pill) and the state assembly is missing.

-----

- [ ] Ensure that this works as expected
- [ ] Add test case for this

### PR DESCRIPTION
**Pull request by elias-ba**
## Notes for the reviewer

This PR propose a fix for the dropped dataclip type pill and the state assembler notice displayed when run a job with a new custom dataclip.

Screenshot from 2023-08-09 07-52-03

## Related issue

Fixes #975 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning_web/live/job_live/manual_run_component.ex [hunk 1]
```diff
@@ -60,25 +60,24 @@ defmodule LightningWeb.JobLive.ManualRunComponent do
...
+        <div class="flex-1 flex flex-col gap-4">
           <div>
             <div class="flex flex-row">
               <div class="basis-1/2 font-semibold text-secondary-700">
                 Dataclip Type
               </div>
               <div class="basis-1/2 text-right">
-                <Common.dataclip_type_pill dataclip={@selected_dataclip} />
+                <Common.dataclip_type_pill dataclip={
+                  @selected_dataclip || %{id: "", body: [], type: :saved_input}
```
Comment (stuartc) [inline lib/lightning_web/live/job_live/manual_run_component.ex:71]: Hmmm, I'm not sure I'm digging this interface the `dataclip_type_pill` uses...

Lets chat later today and rearrange things (including the surrounding logic), our markup a little too complicated at the moment.
