### PR TITLE
Fix HTTP credentials, allowing JSON objects as form inputs

### LINKED ISSUE #3437: HTTP credentials don't work
Sentry Issue: [LIGHTNING-11X](https://openfn.sentry.io/issues/6753003066/?referrer=github_integration)

```
CaseClauseError: no case clause matching: %{"description" => "TLS options to use for HTTPS requests. See https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions", "examples" => [%{"cert" => "-----BEGIN CERTIFICATE[...]END CERTIFICATE-----"}], "title" => "TLS Options", "type" => "object", "writeOnly" => true}
  File "lib/lightning_web/live/credential_live/json_schema_body_component.ex", line 85, in LightningWeb.CredentialLive.JsonSchemaBodyComponent."schema_input (overridable 1)"/1
  File "lib/phoenix_live_view/tag_engine.ex", line 96, in Phoenix.LiveView.TagEngine.component/3
  File "lib/lightning_web/live/credential_live/json_schema_body_component.ex", line 63, in anonymous fn/4 in LightningWeb.CredentialLive.JsonSchemaBodyComponent.inner/1
  File "lib/enum.ex", line 1714, in Enum."-map/2-lists^map/1-1-"/2
  File "lib/enum.ex", line 1714, in Enum."-map/2-lists^map/1-1-"/2
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by taylordowns2000**
## Description

This PR fixes #3437 , allowing the new HTTP configuration schema (and anything that asks for a raw JSON object in the future) to be used in Lightning credentials.

## Validation steps

1. Try to create an HTTP credential. (It shouldn't crash.)
2. Try to pass a valid JSON object in for tls options.
3. Try to pass an invalid JSON object for tls options.
4. Save, then run a job that logs the `state.configuration` to check it's all saved properly. (Or fetch the credential body via IEX.)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [x] Strategy / design
- [x] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning_web/components/new_inputs.ex [hunk 1]
```diff
@@ -577,6 +578,25 @@ defmodule LightningWeb.Components.NewInputs do
     """
   end
 
+  def input(%{type: "codearea"} = assigns) do
```
Comment (midigofrank) [inline lib/lightning_web/components/new_inputs.ex:581]: 🤩

**Review by midigofrank — APPROVED** [review]
Nicely done 🙌

File: lib/lightning/credentials/schema.ex [hunk 2]
```diff
@@ -126,6 +126,18 @@ defmodule Lightning.Credentials.Schema do
 
       %{actual: "null", expected: expected} when is_list(expected) ->
         Changeset.add_error(changeset, field, "can't be blank")
+
+      %{expected: ["object"], actual: "string"} ->
+        # Check if the value is actually a valid JSON object
```
Comment (elias-ba) [inline lib/lightning/credentials/schema.ex]: Can we remove this comment ?

**Review by elias-ba — APPROVED** [review]
Hey @taylordowns2000 this is looking good. Thanks 👏🏽 

PS: I have just one tiny tiny change request about an unnecessary comment but that's not gonna block this PR.

File: lib/lightning/credentials/schema.ex (hunk 2 above)
Comment (taylordowns2000) [reply lib/lightning/credentials/schema.ex]: Why?

**Comment by elias-ba** [comment]
Hey @taylordowns2000, I did approve this PR but then I saw CodeCov complaining about the coverage so I pushed a commit to help out with the test coverage and fixed a bug I found along the way.

The code would crash when someone passed non-string values (like integers or atoms) for object fields. ExJsonSchema returns different error types like `%{expected: ["object"], actual: "integer"}` that weren't handled. Added a catch-all case for those.

I also added few tests for the `validate_json_object/1` function.

I also refactored that big case statement, Credo was complaining about complexity, so I split it into multiple function clauses.

Everything's looking great. Let me know what you think!

File: lib/lightning/credentials/schema.ex (hunk 2 above)
Comment (elias-ba) [reply lib/lightning/credentials/schema.ex]: Well the code was self explanatory, I couldn't see the necessity of that comment. I did remove it in my commit [here](https://github.com/OpenFn/lightning/pull/3438/commits/373385efe83665134272b7fc7baa92a8b4bb9921).

**Comment by taylordowns2000** [comment]
> Hey @taylordowns2000, I did approve this PR but then I saw CodeCov complaining about the coverage so I pushed a commit to help out with the test coverage and fixed a bug I found along the way.
> 
> The code would crash when someone passed non-string values (like integers or atoms) for object fields. ExJsonSchema returns different error types like `%{expected: ["object"], actual: "integer"}` that weren't handled. Added a catch-all case for those.
> 
> I also added few tests for the `validate_json_object/1` function.
> 
> I also refactored that big case statement, Credo was complaining about complexity, so I split it into multiple function clauses.
> 
> Everything's looking great. Let me know what you think!

looks great @elias-ba ! assuming you've done extensive UI click testing here, i'm happy to merge. can you confirm that you've tested not only the changed credential type, but also some basic regression testing on other credential field types? i want to make sure that this big refactor doesn't mess anything up! once you confirm that, let's merge!

**Comment by elias-ba** [comment]
Hey @taylordowns2000 I don't have 100% context of this PR but yes I did click test and it looked fine. I created a HTTP credential and filled in the TLS options code area and everything worked fine. See screenshots. I think you still may need to click test on your end too, but normally my changes wouldn't break anything as they are more tests and a bug fix. Please merge when you happy with this, on my end, I am happy with it.

Screenshot 2025-07-19 at 14 03 54
Screenshot 2025-07-19 at 14 06 09
Screenshot 2025-07-19 at 14 06 27
