### PR TITLE
fix: credential preservation during sandbox workflow merge

### LINKED ISSUE #3782: sandbox: after merging, credential seems to getting lost?
* Create a workflow with a credential one one step
* Create a sandbox
* Credential should be set on the sandbox workflow
* Merge it back to main
* Check the workflow on main
* Credential has gone?

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR **fixes** credential preservation during sandbox workflow merge. When merging a sandbox workflow back to its parent project, credentials (both project credentials and keychain credentials) were being lost because the merge process was copying the sandbox's credential IDs instead of preserving the parent's original credential IDs.

Closes #3782

## Validation steps

1. **Test the fix with project credentials:**
   ```bash
   mix test test/lightning/projects/merge_projects_test.exs:2141
   ```

2. **Test the fix with keychain credentials:**
   ```bash
   mix test test/lightning/projects/merge_projects_test.exs:2226
   ```

3. **Run the full merge test suite:**
   ```bash
   mix test test/lightning/projects/merge_projects_test.exs
   ```
   All tests should pass.

4. **Manual testing:**
   - Create a workflow with a credential in a parent project
   - Create a sandbox from the parent
   - Make changes to the sandbox workflow
   - Merge the sandbox back to the parent
   - Verify the credential is still attached to the job in the parent

## Additional notes for the reviewer

1. **Root cause**: The `build_merged_jobs` function in `merge_projects.ex` was extracting credential IDs directly from source (sandbox) jobs without checking if they should be remapped to target (parent) credential IDs.

2. **Fix approach**: When a source job matches a target job during merge, we now preserve the target's credential IDs instead of using the source's credential IDs. This ensures parent credentials remain intact.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/Header.tsx [hunk 1]
```diff
@@ -111,7 +111,7 @@ export function Header({
   // Global save shortcut: Ctrl/Cmd+S
   useHotkeys(
     "ctrl+s,meta+s", // Windows/Linux: Ctrl+S, Mac: Cmd+S
-    (event) => {
```
Comment (josephjclark) [inline assets/js/collaborative-editor/components/Header.tsx:114]: This has been autoformatted in a precommit (?????) and I can't do anything about it.
