### PR TITLE
fix: flickering of canvas and job editor

### LINKED ISSUE #4046: IDE flashes when version number changed in header due to loading states
**Describe the bug** When you have the FullScreenIDE open and switch between version numbers, there's quite a big flash because of loading states.

**Version number** v2.15.0-pre

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to collaborative editor for a workflow
2. Open full screen IDE (for example, click on a step and then click "Code")
3. Change the version number in the header

**Expected behavior** It changes smoothly
**Actual behaviour** There is a flash due to various loading states

**Screenshots** If applicable, add screenshots to help explain your problem.
Loading state looks like this, which causes the flash.

Image

Image

Image

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by doc-han**
## Description

This PR fixes several flickering on our canvas and IDE
https://www.loom.com/share/c3caf81473be467088372782d70706ce

Closes #4046 #4080 #4089

## Validation steps

1. *(How can a reviewer validate your work?)*

## Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [X] I have performed a **self-review** of my code.
- [X] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [X] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/LoadingBoundary.tsx [hunk 1]
```diff
@@ -38,6 +38,11 @@ export function LoadingBoundary({ children }: LoadingBoundaryProps) {
     hasWorkflowData &&
     (session.settled || !isInitialLoad);
 
+  // most of the states we depend on don't need to show the loading workflow screen I guess.
+  const subReady = hasWorkflowData && !isInitialLoad;
+
+  if (subReady) return <>{children}</>;
+
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/LoadingBoundary.tsx]: Initially, the loading screen is shown when
1. session context loading state changes
2. we don't have workflow data yet (**needed**)
3. session has settled `session.settled`
4. it's our initial load (**needed**)

Those marked **needed** are the ones this PR gives priority to and agrees that we don't show loading state if they've not changed.
