### PR TITLE
AI Assistant: Retry or Cancel Messages with Errors

### LINKED ISSUE #2704: AI Assistant: clear questions after error
In the AI assistant, if the connection is lost to the server (or, presumably, if any error occurs), the question tends to hang around like this:

Image

We should do something about this. Maybe we need to track the status of each message and use that to  control how its rendered?

We could just drop failed messages but I don't really want users to have to ask it again. Would prefer to see a "retry" or "cancel" option until we get a success

### PR DESCRIPTION
**Pull request by elias-ba**
### Description

This PR introduces the retry and cancel functionality for messages in the AI assistant. Users can now retry or cancel a failed message, ensuring better control and allowing to clean up the chat logs.

The retry feature updates a message's status to `:success` and uses its content to perform a new query with the AI Assistant. This allows users to address transient issues or reattempt queries after resolving any underlying problems. The cancel feature allows users to mark a message as `:cancelled`, immediately removing it from the chat logs.

Closes #2704 

### Validation steps

1. Set an invalid API key for the AI assistant in your env variables
2. Start a conversation with the AI assistant
3. Because your API key is invalid, you will receive an error message from Apollo
4. Notice next to the message you sent (left side of the message bubble) the presence of a `retry`button / icon
5. Click on it to see your message being retried
6. Keep generating more messages with errors
7. See that the following messages with errors have also the option to cancel them (`cancel`button / icon next to the `retry`button / icon)
8. Notice that you can cancel messages up until only one left in the chat session. You wont be able to cancel that one. This is guard we implemented to avoid empty chat sessions.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by elias-ba** [comment]
@josephjclark I have to fix the failing tests and probably add a few more tests for this feature, but while I do that, could you please check if this is looking good to you ? Thanks in advance

**Comment by josephjclark** [comment]
It's a good solution Elias and I like the behaviour.

I'm just thinking about a couple of things and may park this until next week, see where I settle.

The questions on my mind are:

- should we just auto-retry on a backoff? I don't know if that's any more helpful. I'll bet that in 95% of cases, hitting "retry" does nothing (if the server is offline or rate limited you've probably got to wait a while to get access back anyway).
- I'm still debating the wording of `remove` versus `cancel` :thinking:  It all depends on how you look at it. 
- When there are multiple errors, and I suspect this will happen often, I don't think the experience is so good:

image

I'm wondering if we should have a little error message underneath each failed message, just to make it clearer that that message didn't send?

This is nitpicky stuff and none of the questions or answers here really solve the problem. So maybe we'll just merge it and come back to it later.

Let me think about it!

**Review by josephjclark — APPROVED** [review]
Hey @elias-ba 

I am happy with this for now! I think it can be improved and we'll come back to it one day. But it's absolutely fine for now, and gives some important feedback and behaviour when occurs DO occur.

@jyeshe Can I ask for a quick technical review from you? Then we can get this merged.

File: lib/lightning/ai_assistant/ai_assistant.ex [hunk 1]
```diff
@@ -43,7 +45,15 @@ defmodule Lightning.AiAssistant do
 
   @spec get_session!(Ecto.UUID.t()) :: ChatSession.t()
   def get_session!(id) do
-    ChatSession |> Repo.get!(id) |> Repo.preload(messages: :user)
+    message_query =
+      from(m in ChatMessage,
+        where: m.status != :cancelled,
```
Comment (jyeshe) [inline lib/lightning/ai_assistant/ai_assistant.ex:50]: 👍

File: lib/lightning/ai_assistant/ai_assistant.ex [hunk 2]
```diff
@@ -236,4 +265,27 @@ defmodule Lightning.AiAssistant do
...
+          {:ok, ChatSession.t()} | {:error, Changeset.t()}
+  def update_message_status(session, message, status) do
+    Multi.new()
+    |> Multi.update(
+      :message,
+      ChatMessage.changeset(message, %{status: status})
+    )
+    |> Multi.run(:session, fn _repo, _changes ->
+      {:ok, get_session!(session.id)}
+    end)
```
Comment (jyeshe) [inline lib/lightning/ai_assistant/ai_assistant.ex:284]: I appreciate the concern with transactions. Can you simplify it a bit with `Repo.update`?

File: lib/lightning/ai_assistant/ai_assistant.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning/ai_assistant/ai_assistant.ex:50]: Yes @jyeshe, we return the error ones so that they can be retried.

File: lib/lightning_web/live/workflow_live/ai_assistant_component.ex [hunk 3]
```diff
@@ -884,4 +952,9 @@ defmodule LightningWeb.WorkflowLive.AiAssistantComponent do
       title
     end
   end
+
+  defp display_cancel_message_btn(session) do
```
[the remark this answers is not in the document]
Comment (elias-ba) [reply lib/lightning_web/live/workflow_live/ai_assistant_component.ex:956]: Thx for the catch, fixed it

**Review by jyeshe — APPROVED** [review]
Nice feature! Congrats my friend!
