### PR TITLE
fix: inspector dataclip selector bugs

### LINKED ISSUE #1714: 2 small bugs on "create new dataclip" dropdown with zero-retention enabled
See loom here: https://www.loom.com/share/d99b97b6424a4aa98974c058d9668361

Two small bugs:

- [ ] When created a new saved input by hand, the dataclip ID does not always appear in the dropdown menu. This seems inconsistent/flaky.
- [ ] When zero persistence is turned on if you create a work order by curling to a webhook url then view the inspector for the first step in the subsequent run you are blocked from selecting "create new dataclip". You can still do it, but only after selecting it then clicking that new "To create a new work order, first click here to select/build an input" link. We should not make the user go through _both_ screens. (In other words, if they select the "Create a new input" item in the dropdown, they should get the creation box right away!)

Note that we broke  #1718 out.

@midigofrank , I'm hoping this is directly related to your last issue. Ping me if you need help reproducing.

### PR DESCRIPTION
**Pull request by midigofrank**
## Notes for the reviewer

- Bumps `phoenix_liveview` version to `0.20.4`.  The version contains a fix for the html select tag changes. Read more here: https://github.com/phoenixframework/phoenix_live_view/pull/2659

### TODO

- [x] some tests are failing, which were passing before. Need to check why/if the version bump is causing it

- [x] Received feedback from: https://github.com/phoenixframework/phoenix_live_view/issues/3096 that we cannot mix stream with non-stream elements in the same container. Will work to have it in a separate element

## Related issue

Fixes #1714 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

File: test/lightning_web/live/attempt_live/show_test.exs [hunk 1]
```diff
@@ -225,12 +225,16 @@ defmodule LightningWeb.RunLive.ShowTest do
     |> has_nothing_yet?()
   end
 
+  # TODO: fix when https://github.com/phoenixframework/phoenix_live_view/issues/3096
+  # gets reslved. Currently returning `true`
```
Comment (taylordowns2000) [inline test/lightning_web/live/attempt_live/show_test.exs:229]: i see the issue is closed now. is there more to do here?

**Review by taylordowns2000 — APPROVED** [review]
the behavior here seems as expected. curious to see how it behaves when the worker no longer sends back a dataclip. but good from my end. see comment about the TODO please before merge

File: lib/lightning_web/live/run_live/streaming.ex [hunk 2]
```diff
@@ -210,6 +214,7 @@ defmodule LightningWeb.RunLive.Streaming do
 
       unquote(helpers())
       unquote(handle_infos())
+      @impl true
```
Comment (stuartc) [inline lib/lightning_web/live/run_live/streaming.ex:217]: One tiny thing here, instead of placing it above the unquote I think this can be inside the handle_asyncs macro above the first `handle_async` - I see thats the pattern with handle_infos...

**Review by stuartc — APPROVED** [review]

**Comment by taylordowns2000** [comment]
noting that there is still bug in an edge case, but that bug is fixed by #1718 

```ex
[error] GenServer #PID<0.2581.0> terminating
** (ArgumentError) construction of binary failed: segment 10 of type 'binary': expected a binary but got: nil
    (phoenix 1.7.10) lib/phoenix/socket/serializers/v2_json_serializer.ex:47: Phoenix.Socket.V2.JSONSerializer.encode!/1
    (phoenix 1.7.10) lib/phoenix/channel/server.ex:256: Phoenix.Channel.Server.reply/6
    (phoenix 1.7.10) lib/phoenix/channel/server.ex:504: Phoenix.Channel.Server.handle_in/1
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "run:fc1fdba5-f6c1-40e6-8119-a00e13add52b", event: "fetch:dataclip", payload: %{"id" => "6e2f0942-45f0-4c7a-bf7f-679f4fcd25d7"}, ref: "716", join_ref: "714"}
State: %Phoenix.Socket{assigns: %{id: "fc1fdba5-f6c1-40e6-8119-a00e13add52b", run: %Lightning.Run{__meta__: #Ecto.Schema.Metadata<:loaded, "runs">, id: "fc1fdba5-f6c1-40e6-8119-a00e13add52b", work_order_id: "918fac53-c040-4a9c-84f8-d2d49c2a9738", work_order: %Lightning.WorkOrder{__meta__: #Ecto.Schema.Metadata<:loaded, "work_orders">, id: "918fac53-c040-4a9c-84f8-d2d49c2a9738", state: :pending, last_activity: ~U[2024-02-08 08:11:06.800540Z], workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: %Lightning.Workflows.Workflow{__meta__: #Ecto.Schema.Metadata<:loaded, "workflows">, id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", name: "OpenHIE Workflow", edges: [%Lightning.Workflows.Edge{__meta__: #Ecto.Schema.Metadata<:loaded, "workflow_edges">, id: "806b4aa2-49a5-413b-ae76-07c144b8f66e", workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, source_job_id: nil, source_job: #Ecto.Association.NotLoaded<association :source_job is not loaded>, source_trigger_id: "cae544ab-03dc-4ccc-a09c-fb4edb255d7a", source_trigger: #Ecto.Association.NotLoaded<association :source_trigger is not loaded>, target_job_id: "d75e31a2-9e09-48d0-84c9-aab0697a9492", target_job: #Ecto.Association.NotLoaded<association :target_job is not loaded>, condition_type: :always, condition_expression: nil, condition_label: nil, enabled: true, delete: nil, inserted_at: ~N[2024-01-22 10:11:13], updated_at: ~N[2024-01-22 10:11:13]}, %Lightning.Workflows.Edge{__meta__: #Ecto.Schema.Metadata<:loaded, "workflow_edges">, id: "3cf11d69-ef5f-4ecb-9177-5db3a35af79e", workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, source_job_id: "ab598152-397d-4003-8b37-1583583e3b0b", source_job: #Ecto.Association.NotLoaded<association :source_job is not loaded>, source_trigger_id: nil, source_trigger: #Ecto.Association.NotLoaded<association :source_trigger is not loaded>, target_job_id: "615b429c-171a-4a75-9a82-b874b446e9e1", target_job: #Ecto.Association.NotLoaded<association :target_job is not loaded>, condition_type: :on_job_success, condition_expression: nil, condition_label: nil, enabled: true, delete: nil, inserted_at: ~N[2024-01-22 10:11:13], updated_at: ~N[2024-01-22 10:11:13]}, %Lightning.Workflows.Edge{__meta__: #Ecto.Schema.Metadata<:loaded, "workflow_edges">, id: "caddf991-703b-4d6d-8375-8ad08945ad75", workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, source_job_id: "ab598152-397d-4003-8b37-1583583e3b0b", source_job: #Ecto.Association.NotLoaded<association :source_job is not loaded>, source_trigger_id: nil, source_trigger: #Ecto.Association.NotLoaded<association :source_trigger is not loaded>, target_job_id: "d8395b2a-da7b-4975-8e61-3e7ec3d41db7", target_job: #Ecto.Association.NotLoaded<association :target_job is not loaded>, condition_type: :on_job_failure, condition_expression: nil, condition_label: nil, enabled: true, delete: nil, inserted_at: ~N[2024-01-22 10:11:13], updated_at: ~N[2024-01-22 10:11:13]}, %Lightning.Workflows.Edge{__meta__: #Ecto.Schema.Metadata<:loaded, "workflow_edges">, id: "28428f6a-75b8-4556-bad3-bfba1991d24f", workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, source_job_id: "d75e31a2-9e09-48d0-84c9-aab0697a9492", source_job: #Ecto.Association.NotLoaded<association :source_job is not loaded>, source_trigger_id: nil, source_trigger: #Ecto.Association.NotLoaded<association :source_trigger is not loaded>, target_job_id: "ab598152-397d-4003-8b37-1583583e3b0b", target_job: #Ecto.Association.NotLoaded<association :target_job is not loaded>, condition_type: :on_job_success, condition_expression: nil, condition_label: nil, enabled: true, delete: nil, inserted_at: ~N[2024-01-22 10:11:13], updated_at: ~N[2024-02-05 07:57:23]}], jobs: [%Lightning.Workflows.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "jobs">, id: "615b429c-171a-4a75-9a82-b874b446e9e1", body: "fn(state => state);\n", name: "Notify CHW upload successful", adaptor: "@openfn/language-http@latest", project_credential_id: nil, project_credential: nil, credential: nil, workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: nil, inserted_at: ~U[2024-01-22 10:11:15.619143Z], updated_at: ~U[2024-01-22 10:11:13.619172Z]}, %Lightning.Workflows.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "jobs">, id: "d8395b2a-da7b-4975-8e61-3e7ec3d41db7", body: "fn(state => state);\n", name: "Notify CHW upload failed", adaptor: "@openfn/language-http@latest", project_credential_id: nil, project_credential: nil, credential: nil, workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: nil, inserted_at: ~U[2024-01-22 10:11:16.620517Z], updated_at: ~U[2024-01-22 10:11:13.620547Z]}, %Lightning.Workflows.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "jobs">, id: "ab598152-397d-4003-8b37-1583583e3b0b", body: "fn(state => state);", name: "Send to OpenHIM to route to SHR", adaptor: "@openfn/language-http@latest", project_credential_id: nil, project_credential: nil, credential: nil, workflow_id: "94850d5a-0936-4e0d-9bde-9425ffa7dd2c", workflow: #Ecto.Association.NotLoaded<association :workflow is not loaded>, project: #Ecto.Association.NotLoaded<association :project is not loaded>, delete: nil, inserted_at: ~U[2024-01-22 10:11:14.617535Z], updated_at: ~U[2024-01-24 11:17:38.656905Z]}, %Lightning.Workflows.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "jobs">, id: "d75e31a2-9e09-48d0-84c9-aab0697a9492", body: "fn(state 321321323{{\n// fn(state => state);\n// fn(state => {\n//   return new Promise((resolve, reject) => {\n//     setTimeout(() => {\n//       console.log('wait 2s, and then resolve');\n//       resolve(state);\n//     }, 2);\n//   });\n// });", name: "Transform data to FHIR standard", adaptor: "@openfn/language-http@latest", project_credential_id: "f9cbcbda-2ce0-4ba2-816d-29dfe9456c39", project_credential: %Lightning.Projects.ProjectCredential{__meta__: #Ecto.Schema.Metadata<:loaded, "project_credentials">, id: "f9cbcbda-2ce0-4ba2-816d-29dfe9456c39", credential_id: "8e33817c-6515-4da5-9fd0-59143abfbfab", credential: #Lightning.Credentials.Credential<__meta__: #Ecto.Schema.Metadata<:loaded, "credentials">, id: "8e33817c-6515-4da5-9fd0-59143abfbfab", name: "empty", production: false, schema: "raw", scheduled_deletion: nil, user_id: "c23dc682-c138-440f-9e10-62488bb65a6e", user: #Ecto.Association.NotLoaded<association :user is not loaded>, project_credentials: #Ecto.Association.NotLoaded<association :project_credentials is not loaded>, projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, inserted_at: ~U[2024-02-03 22:13:11Z], updated_at: ~U[2024-02-05 08:02:05Z], ...>, project_id: "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", project: #Ecto.Association.NotLoaded<association :project  (truncated)
```

**Review by taylordowns2000 — APPROVED** [review]
