### PR TITLE
fix: auto-select newly created credentials in workflow editor

### LINKED ISSUE #4287: Newly created credential not automatically added
**Describe the bug** When I create a new credential for a step in a workflow, the credential is not automatically added to the step. I'm taken back to the select credential interface, which isn't _usually_ a problem, but becomes a big problem when I'm creating a generic credential type.

Why? Because I've just hit save and the thing I've created is _NEITHER_ selected _NOR_ displayed on the list view that I'm taken back to. I need to perform additional navigation to find the thing I just created, and then select it.

This should behave like it did in the legacy system... on create the credential you create should be selected automatically.

**Version number**

`v2.15.6`

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to a workflow with an HTTP step
2. Click connect
3. Click create new
4. Click advanced
5. Click raw
6. Save it
7. See the bug

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR fixes the credential auto-selection bug where newly created credentials from the ConfigureAdaptorModal were not automatically selected for the job.

Closes #4287

## Validation steps

1. Open the collaborative workflow editor
2. Click on a job to open the inspector
3. Click "Connect" to open the ConfigureAdaptorModal
4. Click "Create new credential"
5. Fill in and save the credential
6. **Verify**: The new credential should be automatically selected
7. Test both type of credentials

## AI Usage

- [x] Code generation (copilot but not intellisense)
- [ ] Strategy / design
- [ ] Learning or fact checking
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/inspector/JobForm.tsx [hunk 1]
```diff
@@ -150,8 +151,12 @@ export function JobForm({ job }: JobFormProps) {
         keychain_credential_id: is_project_credential ? null : credentialId,
       });
 
-      // Reload credentials in the background so the list is up to date
-      void requestCredentials();
+      // Wait for credentials to load before reopening modal
+      // This ensures the newly created credential appears in the list
+      await requestCredentials();
```
Comment (lmac-1) [inline assets/js/collaborative-editor/components/inspector/JobForm.tsx]: Should this be wrapped with a try / catch block? If this fails, I think the user could get stuck with no feedback because the modal won't reopen?

**Review by lmac-1 — APPROVED** [review]
Changes look great, nice work @elias-ba! I added one small comment to improve but it shouldn't block merging.

File: assets/js/collaborative-editor/components/inspector/JobForm.tsx (hunk 1 above)
Comment (elias-ba) [reply assets/js/collaborative-editor/components/inspector/JobForm.tsx]: Good catch, thanks Lucy! Added the try/catch - the modal will now reopen even if the credential refresh fails.
