### PR TITLE
Fix Monaco editor showing stale content on job switch

### LINKED ISSUE #4022: Canvas & IDE selected job and selected run not syncing properly
## Selected Job

When changing steps on the canvas, the IDE ~sometimes~ often shows another step's expression.

Is this related to having "step" and "job" parameters in the URL? Is that intentional?

`?step=uuid&v=38&job=uuid`

https://www.loom.com/share/d469b2b058004cde810e8aa0f6133ae4

## Selected Run

1. Run something from the IDE
2. Press esc to go back to the canvas
3. See that the run history isn't properly displayed on the canvas

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

This PR includes two improvements to the collaborative editor:

### 1. Fix Monaco editor showing stale content on job switch

The Monaco binding wasn't updating when switching jobs because the onMount callback had ytext in its dependencies, but Monaco only calls onMount once when the editor initially mounts.

This fix introduces an editorReady state variable that triggers the binding effect after the editor mounts, ensuring the Y.Text binding is properly created/destroyed when switching between jobs.

### 2. Simplify selectedRun state management in CollaborativeWorkflowDiagram

Replaced the useState/useEffect pattern with a direct read from searchParams since the useURLState hook is already reactive. This reduces complexity by removing unnecessary state synchronization while maintaining the single source of truth pattern within the component.

Closes #4022

### Monaco editor fix:
1. Open collaborative editor
2. Open the IDE for the first job
3. Close the IDE and select another job
4. Open the IDE for the second job
5. Verify that the job code displayed belongs to the second job (not stale content from the first)

### selectedRun state simplification:
1. Open collaborative editor with a workflow that has run history
2. Click on a run in the history panel
3. Verify the run is selected and displayed correctly
4. Verify the URL contains the `?run=<run-id>` parameter
5. Use browser back/forward buttons to navigate
6. Verify the selected run updates correctly based on URL changes

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/CollaborativeMonaco.tsx [hunk 1]
```diff
@@ -126,7 +118,7 @@ export function CollaborativeMonaco({
         bindingRef.current = undefined;
       }
     };
-  }, [ytext, awareness]);
+  }, [ytext, awareness, editorReady]);
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/CollaborativeMonaco.tsx:121]: If I'm getting it right. this `editorReady` is to make sure that ytext binding is triggered on mount since we deleted the code above from the useEffect.
