### PR TITLE
fix: save&run disabled after new workflow save

### LINKED ISSUE #4071: Save and Run Button Disabled for Users with Access
1. Click on create new workflow button and switch to collaborative editor
2. Click on the import button
3. Paste your YAML or upload a yaml file and click on “create” button
4. The left panel goes away but the save and run buttons at the top are disabled with the tooltip message “You do not have permission to edit this workflow”
5. The URL also does not update to the created workflow. It stays at `/new/collaborate` instead of `/workflow_id/collaborate`

### PR DESCRIPTION
**Pull request by doc-han**
## Description

This PR resolves an issue where save&run buttons were disabled after creating a new workflow

Closes #4071 

## Validation steps

1. Go to create a new workflow
2. Click the experimental icon(beaker) in the header to switch to the new editor
3. You'll notice we don't support templates there yet. Now use the import and then import some workflow via yaml. (example yaml provided below)
4. After clicking create, are your run & save buttons enabled? Are you able to perform any action as usual? If yes then we're good

## Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: test/lightning_web/channels/workflow_channel_test.exs [hunk 1]
```diff
@@ -334,6 +334,37 @@ defmodule LightningWeb.WorkflowChannelTest do
...
+
+      ref = push(new_socket, "get_context", %{})
+
+      assert_reply ref, :ok, response
+
+      # CRITICAL: For new unsaved workflows, fresh_workflow will be nil
+      # so latest_snapshot_lock_version should fall back to workflow.lock_version
+      assert %{latest_snapshot_lock_version: latest_lock_version} = response
+      # New workflows start at lock_version 0 (or nil, which should be handled)
+      assert latest_lock_version == 0 || is_nil(latest_lock_version)
```
Comment (elias-ba) [inline test/lightning_web/channels/workflow_channel_test.exs]: Shouldn't this assert be `assert latest_lock_version == 0` to make the test more precise and catch any unexpected nil values. Based on the code logic, we should always get 0 for new workflows since we create a workflow struct with implicit lock_version: 0 (Ecto schema default) and we fall back to workflow.lock_version when fresh_workflow is nil. Right ?

File: test/lightning_web/channels/workflow_channel_test.exs [hunk 2]
```diff
@@ -334,6 +334,37 @@ defmodule LightningWeb.WorkflowChannelTest do
...
+      # Verify we're in a new workflow context
+      assert new_socket.assigns.workflow.name == "Untitled workflow"
```
Comment (elias-ba) [inline test/lightning_web/channels/workflow_channel_test.exs:367]: Could we assert new_socket.assigns.workflow.lock_version == 0 too ? This was we verify the in-memory workflow actually has lock_version: 0

File: test/lightning_web/channels/workflow_channel_test.exs (hunk 1 above)
Comment (doc-han) [reply test/lightning_web/channels/workflow_channel_test.exs]: resolved

File: test/lightning_web/channels/workflow_channel_test.exs (hunk 2 above)
Comment (doc-han) [reply test/lightning_web/channels/workflow_channel_test.exs:367]: resolved

**Comment by doc-han** [comment]
> Hey @doc-han nice one. The fix is great. I could actually approve but I would love to draw your attention to the comments I left in my review. Also maybe confirm with @taylordowns2000 if we want to enable the 'Run' button during the creation mode. I could run my workflow before even saving it. The Run saved the workflow then ran but as a regular user that surprised me because I was expecting the button to just run. And after the run, I was directly in edit mode.
> 
> Image

Resolved this too. 
Made the buttons on the right of the header not accessible at this point in time

**Comment by taylordowns2000** [comment]
@theroinaochieng , is this still relevant after https://github.com/OpenFn/lightning/pull/4087 ?

**Comment by stuartc** [comment]
@taylordowns2000 you might be right, I'm going to review the other PR and circle back.

File: assets/js/collaborative-editor/components/left-panel/index.tsx [hunk 3]
```diff
@@ -40,7 +40,7 @@ export function LeftPanel({
 
   return (
     <div
-      className={`absolute inset-y-0 left-0 w-1/3 transition-transform duration-300 ease-in-out z-10 ${
```
Comment (stuartc) [inline assets/js/collaborative-editor/components/left-panel/index.tsx:43]: 😘

**Review by stuartc — APPROVED** [review]
