### PR TITLE
Delay purge user having project file(s)

### LINKED ISSUE #2919: Can't purge deleted users who have Project files
Sentry Issue: [LIGHTNING-K4](https://openfn.sentry.io/issues/5976778935/?referrer=github_integration)

```
Ecto.ConstraintError: constraint error when attempting to delete struct:

    * "project_files_created_by_id_fkey" (foreign_key_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `foreign_key_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.

  File "lib/ecto/repo/schema.ex", line 881, in anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
  File "lib/enum.ex", line 1700, in Enum."-map/2-lists^map/1-1-"/2
  File "lib/ecto/repo/schema.ex", line 865, in Ecto.Repo.Schema.constraints_to_errors/3
  File "lib/ecto/repo/schema.ex", line 842, in Ecto.Repo.Schema.apply/4
  File "lib/ecto/repo/schema.ex", line 611, in anonymous fn/13 in Ecto.Repo.Schema.do_delete/4
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jyeshe**
## Description

This PR changes the `purge-user` to postpone it for users having a project file. The project file is retained until the `history_retention_period` and after it's deleted the user will be deleted on the next scheduled job.

Closes #2919 

## Validation steps

* The real validation will be on Staging with GCS and there is a test cases for delaying the purging of a user with a project file and another for deleting the file on storage and on database when file expires.  

Without the same value as staging locally you can try to:
1. Create a work orders export
2. Try to purge this user 
3. When cron job runs it won't delete the user
4. Set the project file inserted_at to a expired date
5. Force the project "data_retention" job to run
6. It deletes the file (and the database record)
7. Force the accounts "purge_user" job to run
8. It deletes the user   

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/accounts.ex [hunk 1]
```diff
@@ -70,17 +71,26 @@ defmodule Lightning.Accounts do
...
       from(run in Lightning.Run,
-        join: user in Lightning.Accounts.User,
+        join: user in User,
         on: run.created_by_id == user.id,
         select: user.id,
         distinct: true
       )
 
+    users_with_files =
+      from(file in File,
```
Comment (midigofrank) [inline lib/lightning/accounts.ex:81]:
```suggestion
      from(file in Projects.File,
```
Can we use `Projects.File` to avoid conflicts with the `File` module?

File: lib/lightning/accounts.ex [hunk 2]
```diff
@@ -70,17 +71,26 @@ defmodule Lightning.Accounts do
...
+        distinct: true
+      )
+
     users_to_delete =
       from(u in User,
         where:
           u.scheduled_deletion <= ago(0, "second") and
-            u.id not in subquery(users_with_activities)
+            u.id not in subquery(users_with_activities) and
+            u.id not in subquery(users_with_files)
```
Comment (midigofrank) [inline lib/lightning/accounts.ex:93]: Given the recent performance improvement on deleting snapshots, can we just use `not exists` here as well? https://hexdocs.pm/ecto/Ecto.Query.API.html#exists/1

**Review by midigofrank — CHANGES_REQUESTED** [review]
This is great work @jyeshe, I only have 2 comments:

1. Can we use `Projects.File` instead of aliasing the whole module? Feels a bit weird to override core elixir module names.
2. Stu mentioned something around updating the snapshot delete query to use `not exists` instead of `not in` which drastically improved the performance. Was thinking we could do the same here

**Review by elias-ba — APPROVED** [review]
Great work @jyeshe 👏🏽

File: lib/lightning/accounts.ex (hunk 2 above)
Comment (jyeshe) [reply lib/lightning/accounts.ex:93]: well spot @midigofrank . I am getting a compile error with the parent_as to refer to the user. will get back to this during the weekend

Comment (jyeshe) [reply lib/lightning/accounts.ex]: done

Comment (jyeshe) [reply lib/lightning/accounts.ex]: done

**Comment by jyeshe** [comment]
Additionally I've made the file deletion idempotent.

**Review by midigofrank — APPROVED** [review]
