### PR TITLE
fix github sync modal in the workflow editor

### LINKED ISSUE #3177: "Save & Sync" button gives no action/feedback
1. Clicking "Save and Sync" from the modal inside the Inspector (see image) does nothing. (No error that I can see in the browser.)
2. Pressing `Command-S` from the Canvas no longer seems to initiative save & sync.
3. No sync appears to be initiated, though a toast message appears at the bottom when saving and syncing from the canvas.

Image

Update: when I then exit to the canvas, save the workflow (command-s), and save & sync from the canvas it seems like it might work, but the modal stays open on the page. 

**Version number**  `v2.12.1 (1.4.28)`

I have reproduced this locally on main:

- [ ] Yes
- [x] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to inspetor
2. Hit command-s to open the save & sync modal
3. Type your commit message and click save

**Expected behavior** A clear and concise description of what you expected to
happen.

I'd expect that a save & sync is initiated and that I see a toast at the bottom when it's been sent off succesfully.

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

This PR fixes the bug on the github sync modal in the workflow editor. The problem was that the modal was embedded inside the `#workflow-form`, which was always present. This PR creates a stand alone form for the github sync modal.

This PR also increases the priority of the `CtrlShiftS` binding. It was being overridden by `CtrlS`.

Closes #3177

## Validation steps

You need to have Github setup to validate this locally. Check the docs for the needed env vars: https://github.com/OpenFn/lightning/blob/main/DEPLOYMENT.md#github 

In the workflow editor, press `CtrlShiftS` or `CmdShiftS` if you're on mac. The github sync modal will appear.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Review by taylordowns2000 — APPROVED** [review]
looks good to me!

image

File: lib/lightning_web/live/workflow_live/github_sync_modal.ex [hunk 1]
```diff
@@ -25,7 +25,7 @@ defmodule LightningWeb.WorkflowLive.GithubSyncModal do
   @impl true
   def render(assigns) do
     ~H"""
-    <div>
+    <form id={@id <> "-form"} phx-submit="save">
```
Comment (jyeshe) [inline lib/lightning_web/live/workflow_live/github_sync_modal.ex:28]: Hey @midigofrank nice catch! Would you mind renaming the event for `save_gh`? I find it important because it is handled by the `WorkflowLive.Edit` which we know that needs to be refactored into smaller components.

Comment (midigofrank) [reply lib/lightning_web/live/workflow_live/github_sync_modal.ex:28]: Hey @jyeshe , good idea, I actually thought about and decided just to leave it as it was under the `def handle_event("save", _, _)`  callback.

The logic is tightly coupled with the usual `save action` with the only difference being the call to github sync and the flash message, so I just decided to leave it coupled given the time. 

Let me see if I can refactor it out easily

Comment (midigofrank) [reply lib/lightning_web/live/workflow_live/github_sync_modal.ex]: Hey @jyeshe , I have refactored it out into a different callback. Let me know your thoughts

**Review by jyeshe — APPROVED** [review]
Super, even better! Thanks!

**Comment by jyeshe** [comment]
The decoupling was great because it allows now the modal to handle itsown event, doesn't it? I 've approved as it was already greatly improved but if you have an extra time and could move the handler to the modal, it would be awesome.

**Comment by midigofrank** [comment]
@jyeshe I hear you, but moving the callback to the `live_component` is a little tricky, mostly because of naming. 

 It would have been easy if we could just make the `save_workflow/2` public, but we can't because we already have a `WorkflowLive.Helpers.save_workflow/2` which doesn't take in a socket.

 The alternative is to duplicate the `socket handling logic`, but this isn't ideal since it's directly tied to the `WorkflowLive.Edit` liveview.
