### PR TITLE
Handle dataclip JSON text search more gracefully

### LINKED ISSUE #1794: History Search: DBConnection.ConnectionError: tcp recv: closed
It seems as though search is timing out more and more frequently. To investigate.

When attempting to search through the Work order history (by logs, ids or input data) the requests times out with this error saying "There was an error loading the work orders" and logs error on Sentry.  See images and logs below.   

How to replicate using the _Openhie-2023_ project: 
1.  Go to history
2. Copy and paste `49 Meadow St` into the search bar 
3. Click search or press enter
Result: The request times out and returns an error. 

Image
***
Exception: 
When a filter is applied to reduce the data loaded, the search functionality works but it is also quite slow. 

How to replicate: 
1. Go to history
2. Set the workflow filter to `FHIR-to-FHIR` and `Time -> Received Date` to T-2 where T is today's date. 
3. Enter `49 Meadow St` into the search bar
4. Click search 

Result: See image below
Image

***
Sentry Issue: [LIGHTNING-86](https://openfn.sentry.io/issues/4700920542/?referrer=github_integration)

```
DBConnection.ConnectionError: tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
  File "lib/ecto/adapters/sql.ex", line 1047, in Ecto.Adapters.SQL.raise_sql_call_error/1
  File "lib/ecto/adapters/sql.ex", line 945, in Ecto.Adapters.SQL.execute/6
  File "lib/ecto/repo/queryable.ex", line 229, in Ecto.Repo.Queryable.execute/4
  File "lib/ecto/repo/queryable.ex", line 19, in Ecto.Repo.Queryable.all/3
  File "lib/ecto/repo/queryable.ex", line 151, in Ecto.Repo.Queryable.one/3
...
(3 additional frame(s) were not displayed)

(DBConnection.ConnectionError tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated))
```

### LINKED ISSUE #1803: Optimize search on history page
Placeholder for the epic to "fix" or optimize search. Note:

1. We don't partition stuff by time right now.
2. We don't have the fancy GIN indexes (for jsonb) that we used in v1.
3. We _might_ be able to seriously improve performance here via indexes and careful query refactor before reaching for some big ole search solution.

- [x] #1898
- [x] #1939 

Related bugs:
- https://github.com/OpenFn/lightning/issues/1794
- https://github.com/OpenFn/lightning/issues/968

Related future enhancement: https://github.com/OpenFn/lightning/issues/981

Related issue: Depending on how we solve this search functionality, we might potentially have solution for the filtering use case.
https://github.com/OpenFn/lightning/issues/1791

### LINKED ISSUE #1939: Allow dataclip body to be searched as text (tsvector)
We recently added a `gin` index to `dataclips.body`, however the search query is treating the body as a string.

In order to use a gin index on a JSONB type, the query should use a json operator (`@>`, `@@`, `@?`...).

So in order to search dataclips as text (and be performant), we need to:

1. Cast the json as a tsvector
  Attention should be paid as to the dictionary choice to ignore JSON syntax.
2. Store the vector in a new column (`body_search_vector`?)
3. Add a GIN index to the new column.
4. Change the history page query to use the search vector instead of casting the body as a string.

**NOTE**: re: dictionary choice, we need to make sure that this accommodates a variety of searching patterns - please can we document at least 5 varying  json document structure and/or search string variations. With tsvector it's entirely possible that compound words (camelCase) and other "not English words" might be ignored.

### PR DESCRIPTION
**Pull request by taylordowns2000**
## Validation Steps

1. Run the migrations to add `search_vector`, the new gin index, and the new trigger to `dataclips`.
2. Send a workorder to your a webhook trigger URL with some custom JSON
3. Go to history, search for something that only appears in the dataclip
4. Note that you can find whole strings for both keys and values 
5. Note that you can find partial strings for both keys and values when they _START_ a word
6. Note that you can't find partial strings when they occur in the middle or end of words... this is true for both `log_lines` and `dataclips`; it's OK for now, but we'll want to do better later.
7. Check out the new tests that lock in this functionality.

Fixes #1939
Fixes #1803
Fixes #1794  

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning_web/live/run_live/index.ex [hunk 1]
```diff
@@ -41,7 +41,8 @@ defmodule LightningWeb.RunLive.Index do
     cancelled: :boolean,
     killed: :boolean,
     exception: :boolean,
-    lost: :boolean
+    lost: :boolean,
+    rejected: :boolean
```
Comment (taylordowns2000) [inline lib/lightning_web/live/run_live/index.ex:45]: this is a separate fix — the filters weren't working for "rejected" and this does the trick!

File: lib/lightning_web/live/run_live/index.html.heex [hunk 2]
```diff
@@ -720,6 +720,7 @@
                 page={@page}
                 async_page={@async_page}
                 url={@pagination_path}
+                help_text="Use whole words or the start of words for better results; partial string matching often won't find substrings in the middle or at the end of a word."
```
Comment (taylordowns2000) [inline lib/lightning_web/live/run_live/index.html.heex:723]: added to make it easier for users to understand the limitations of this `tsquery`

File: priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs [hunk 3]
```diff
@@ -0,0 +1,42 @@
+defmodule Lightning.Repo.Migrations.GenerateDataclipSearchVectors do
+  require Logger
+  use Ecto.Migration
+
+  def change do
+    execute(
+      # Calculate the search vectors in batches of 1000 rows until all rows have
```
Comment (taylordowns2000) [inline priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs:7]: this was a great pattern to reuse @stuartc . thank you!

File: priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+      end,
+      ""
+    )
+  end
+
+  defp update_search_vector(limit) do
+    repo().query!(
+      """
+      UPDATE dataclips
+      SET search_vector = jsonb_to_tsvector('english_nostop', body, '"all"')
```
Comment (taylordowns2000) [inline priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs:30]: the `'"all"'` is magic... it tells postgres to include the keys and the values in the index

File: test/lightning/invocation_test.exs [hunk 5]
```diff
@@ -749,11 +806,238 @@ defmodule Lightning.InvocationTest do
...
+      %{
+        project: project,
+        dataclip: dataclip,
+        workorder: workorder,
+        run: run,
+        step: step
+      }
+    end
+
+    @tag skip: "Ooops. We don't support this yet."
```
Comment (taylordowns2000) [inline test/lightning/invocation_test.exs:829]: this is something i'd like to support in the future, but it would be a progressive enhancement from where are now.

**Review by jyeshe — CHANGES_REQUESTED** [review]
The search worked perfectly for both prefixes and complete words preserving the case insensitive behaviour. 

Only the tooltip was not displayed:
Screenshot from 2024-04-01 13-03-24

I have opened two issues on the UI related to the search box but not on the scope of indexing.

**Comment by taylordowns2000** [comment]
> The search worked perfectly for both prefixes and complete words (keys and values) preserving the case insensitive behaviour.
> 
> Only the tooltip was not displayed: Screenshot from 2024-04-01 13-03-24
> 
> I have opened two issues on the UI related to the search box but not on the scope of indexing.

Thank you @jyeshe ! Re: "tooltip not displayed" I can't recreate that problem. Looking closely at the images you've pasted though, it almost seems as though you're running on an old commit. Is that possible? Your screenshot has March 26th and the last commit on this PR was on March 29th

**Review by jyeshe — APPROVED** [review]
@taylordowns2000 Queries were validated and the tool tip is shown :100: With this last revision the search became case insensitive which is coherent with the `ts_query` output shown at:
https://www.postgresql.org/docs/current/functions-textsearch.html
