### PR TITLE
Fix digest email

### LINKED ISSUE #3616: Digest email only includes a few WO states
The digest email only includes a couple of work order states

### PR DESCRIPTION
**Pull request by taylordowns2000**
## Description

Fixes #3616 

## Validation steps

1. Review carefully and run the tests! (Or wait for a digest email, but that's harder to do.)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/digest_email_worker.ex [hunk 1]
```diff
@@ -133,6 +132,19 @@ defmodule Lightning.DigestEmailWorker do
     }
   end
 
+  # Builds search parameters for failed workorders by including all final states except :success.
+  # This ensures new failure states added to Run.final_states() are automatically included.
+  defp build_failed_status_params(base_params) do
+    failure_states = Lightning.Run.final_states() -- [:success]
```
Comment (elias-ba) [inline lib/lightning/digest_email_worker.ex]: I think this logic could be moved to the Run module as `Lightning.Run.failure_states()` to match the existing `Lightning.Run.final_states()` pattern.

**Benefits:**
1. Avoids recalculating the array subtraction every time this function is called
2. Centralizes failure state definition - if ever one day we decide to add a new failure state, they'll automatically be included here
3. Follows the same pattern as the existing `final_states()` function
4. Makes the intent more explicit

**Suggested implementation:**
```elixir
# In the Run module
def failure_states do
  final_states() -- [:success]
end
```

Then this line becomes:
```elixir
failure_states = Lightning.Run.failure_states()
```

This would future-proof the code against changes to the state definitions and provide a reusable function for other parts of the codebase that might need to identify failure states. What do you think about this approach?

**Review by elias-ba — APPROVED** [review]
Hey @taylordowns2000, this looks rock solid, and it's really well done. I loved reviewing it. Especially the comments are super helpful for reviewing the tests and validating the work. I have left one tiny non-blocking comment. I will approve this and it's up to you to address my comment or not. Thanks man 👏🏽
