### PR TITLE
Apply usage limit to bulk-reruns

### LINKED ISSUE #1931: Allow limiting run batches
Umbrella apps should be able to also limit the action of creating multiple runs at once (a batch).

**Version number** 

Any latest

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

Depends on umbrella app setup.

**Expected behavior** A clear and concise description of what you expected to
happen.

Return error on limit action on limit exceeded.

### PR DESCRIPTION
**Pull request by jyeshe**
## Validation Steps

Via automated tests and umbrella app only.

## Notes for the reviewer

Applies usage limit to bulk-reruns when selecting one or multiple work orders on History Page.

*Note:* Additionally avoids creating users on setup.

## Related issue

Fixes #1931 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning/work_orders.ex [hunk 1]
```diff
@@ -391,35 +396,54 @@ defmodule Lightning.WorkOrders do
...
-
-        do_retry(
-          run.work_order,
-          run.dataclip,
-          starting_job,
-          [],
-          attrs[:created_by]
-        )
-      end)
+    with project_id <- Keyword.fetch!(opts, :project_id),
```
Comment (jyeshe) [inline lib/lightning/work_orders.ex:399]: backend validation (double check)

File: lib/lightning/work_orders.ex [hunk 2]
```diff
@@ -391,35 +396,54 @@ defmodule Lightning.WorkOrders do
...
+      {:ok, Enum.count(results, fn result -> match?({:ok, _}, result) end)}
+    end
   end
 
   def retry_many([%RunStep{} | _rest] = run_steps, opts) do
-    results =
-      Enum.map(run_steps, fn run_step ->
-        retry(run_step.run_id, run_step.step_id, opts)
-      end)
+    with project_id <- Keyword.fetch!(opts, :project_id),
```
Comment (jyeshe) [inline lib/lightning/work_orders.ex:431]: another case for backend validation

File: lib/lightning_web/live/run_live/index.html.heex [hunk 3]
```diff
@@ -611,7 +611,14 @@
                           <button
                             type="button"
                             class="rounded bg-white px-2 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
-                            phx-click={show_modal("bulk-rerun-from-start-modal")}
+                            phx-click={
+                              with :ok <-
+                                     validate_bulk_rerun(
```
Comment (jyeshe) [inline lib/lightning_web/live/run_live/index.html.heex:616]: frontend validation

File: lib/lightning_web/live/run_live/index.html.heex [hunk 4]
```diff
@@ -623,7 +630,14 @@
                             id="bulk-rerun-from-job-modal-trigger"
                             type="button"
                             class="rounded bg-white px-2 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
-                            phx-click={show_modal("bulk-rerun-from-job-modal")}
+                            phx-click={
+                              with :ok <-
+                                     validate_bulk_rerun(
```
Comment (jyeshe) [inline lib/lightning_web/live/run_live/index.html.heex:635]: yet another frontend validation

**Review by taylordowns2000 — APPROVED** [review]

**Comment by taylordowns2000** [comment]
> Nicely done @jyeshe 🙌 . Just curious though, what if we standardize sending the number of items we want to limit. 
> 
> This way we will have only one `action` type.
> 
> `Action{type: :new_runs, amount: 1 | n}`

I love this. I'm fine with the current implementation but think @midigofrank 's suggestion here is spot on.

**Comment by jyeshe** [comment]
> Nicely done @jyeshe 🙌 . Just curious though, what if we standardize sending the number of items we want to limit. This way we will have only one `action` type. `Action{type: :new_runs, amount: 1 | n}`

Thank you @midigofrank for spotting it, I also prefer slimmer approaches. In case we need to customize the behaviour and message in the future then we can add the new type.
