### PR TITLE
Fix for LiveView error when viewing a Run/Step and the socket reconnects

### LINKED ISSUE #2148: Workflow edit LiveView crashes on reconnect when manual run input select is disabled
Sentry Issue: [LIGHTNING-6W](https://openfn.sentry.io/issues/4568097698/?referrer=github_integration)

```
FunctionClauseError: no function clause matching in LightningWeb.WorkflowLive.Edit.handle_event/3
  File "lib/lightning_web/live/workflow_live/edit.ex", line 744, in LightningWeb.WorkflowLive.Edit.handle_event/3
  File "lib/phoenix_live_view/channel.ex", line 507, in anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
  File "/app/deps/telemetry/src/telemetry.erl", line 321, in :telemetry.span/3
  File "lib/phoenix_live_view/channel.ex", line 260, in Phoenix.LiveView.Channel.handle_info/2
  File "gen_server.erl", line 1095, in :gen_server.try_handle_info/3
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by stuartc**
## Validation Steps

Open a previously run work order (via the inspect button) at any step.
When you see the editor/inspector page, either restart your server or wait for a socket timeout (if behind a reverse-proxy or load balancer).

## Related issue

Fixes #2148 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning_web/live/workflow_live/edit.ex [hunk 1]
```diff
@@ -910,10 +910,14 @@ defmodule LightningWeb.WorkflowLive.Edit do
     {:noreply, socket |> assign_manual_run_form(changeset)}
   end
 
+  # Handle empty manual run form submission, this happens when the dataclip
+  # dropdown is disabled and the socket reconnects.
+  def handle_event("manual_run_change", %{}, socket) do
```
Comment (midigofrank) [inline lib/lightning_web/live/workflow_live/edit.ex:915]: Shouldn't you just ignore the params completely? From the sentry log, the param isn't empty, it's: 
```elixir
%{"_target" => ["manual", "dataclip_id"]}
```

**Review by midigofrank — CHANGES_REQUESTED** [review]

File: lib/lightning_web/live/workflow_live/edit.ex (hunk 1 above)
Comment (stuartc) [reply lib/lightning_web/live/workflow_live/edit.ex:915]: Yeah I guess ignoring them entirely with `_params` is better. 👍
