### PR TITLE
2279 usage tracker fixes

### LINKED ISSUE #2276: Impact tracker not working in v2.6.3
Versions `v2.6.3` and later are not generating and reporting anonymous impact metrics

- likely due to how Oban cron options are merged

### LINKED ISSUE #2279: UsageTracking fixes

### PR DESCRIPTION
**Pull request by rorymckinley**
## Validation Steps

Set USAGE_TRACKING_ENABLED to true
Change the [DayWorker cron](https://github.com/OpenFn/lightning/blob/main/lib/lightning/config.ex#L114) to run every minute.
Start up Lightning locally and then, after a minute or two, check that both Dayworker and ResubmissionCandidatesWorker appear in the logs.

## Notes for the reviewer

Two changes, grouped by commit.

For the change to `.oban_opts` I am not happy with the code I added, it could probably do with a cleanup. In addition, the test is both brittle and lacks coverage. I am opening the PR now given the urgency for fixes to the issues.

Once I have capacity I would like to circle back to the tests.

## Related issue

Fixes #2276
Fixes #2279 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning/usage_tracking/run_service.ex [hunk 1]
```diff
@@ -15,11 +15,11 @@ defmodule Lightning.UsageTracking.RunService do
     |> finished_on(date)
   end
 
-  def unique_jobs(steps, date) do
+  def unique_job_ids(steps, date) do
     steps
     |> finished_on(date)
-    |> Enum.map(& &1.job)
-    |> Enum.uniq_by(& &1.id)
+    |> Enum.map(& &1.job.id)
```
Comment (stuartc) [inline lib/lightning/usage_tracking/run_service.ex:21]: I think this will have the same effect, if the job doesn’t exist the job assoc will be nil, you can get `job_id` off of the step. Am I not understanding this?

What constitutes active in this case?

Comment (rorymckinley) [reply lib/lightning/usage_tracking/run_service.ex]: @stuartc Well caught - that was a typo - corrected.

**Review by taylordowns2000 — APPROVED** [review]
