### PR TITLE
fix: error propagation on collab editor

### LINKED ISSUE #4069: Error state of (node/edges) not persisting in collab-editor
**Describe the bug** When I change the content of a node/edge to something that will error, the error doesn't seem to persist. 
eg. 
1. have two users on the same workflow and also on the form. eg. the JobForm or EdgeForm
2. user1 should change the value of the form to an error state.
3. you'll notice that the error doesn't persist. this is because user2 just being present cleans up the error state

**NOTE: Please pay attention to comments below this issue**

**Version number** The version of Lightning you have seen the bug on.

If you're running on a tagged version, include the number: `vX.Y.Z`

If you're running locally with an unreleased version, the commit sha: `84b1bdc`

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

from description.

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by doc-han**
## Description

This PR resolved how we handle error propagation on the collab editor.
- Two users can be on the same form, we'll giver client error priorities to who's actively editing the form and server error priority to who's not actively editing the form.

Closes #4069

## Validation steps

1. Open two windows/instances of the same workflow
2. Then try editing the same job/edge on both window
3. are the errors being represented well?

Before this PR, the errors we're getting cleaned up and not persisted

## Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/inspector/JobForm.tsx [hunk 1]
```diff
@@ -105,24 +104,14 @@ export function JobForm({ job }: JobFormProps) {
...
-    job,
-    changedFields => {
-      Object.entries(changedFields).forEach(([key, value]) => {
-        if (key in form.state.values) {
-          if (key === 'adaptor' && value) {
-            const { package: adaptorPackage } = resolveAdaptor(value);
-            if (adaptorPackage) {
-              form.setFieldValue('adaptor_package', adaptorPackage);
-            }
-          }
```
Comment (elias-ba) [inline assets/js/collaborative-editor/components/inspector/JobForm.tsx:124]: Is this removal intentional? If `adaptor_package` needs to be derived from `adaptor` when syncing from Y.Doc, couldn't this lead to a regression ?

File: assets/js/collaborative-editor/components/form/index.tsx [hunk 2]
```diff
@@ -53,11 +54,64 @@ const { useAppForm: useBaseAppForm } = createFormHook({
...
+
+  useValidation(form, errorPath, isServerUpdate);
 
   return form;
 }
+
+// we need a better deepEqual check
+function deepEqual(a: unknown, b: unknown) {
+  return JSON.stringify(a) === JSON.stringify(b);
+}
```
Comment (elias-ba) [inline assets/js/collaborative-editor/components/form/index.tsx:117]: Could we use this: https://www.npmjs.com/package/fast-deep-equal ?

File: assets/js/collaborative-editor/stores/createWorkflowStore.ts [hunk 3]
```diff
@@ -1198,7 +1198,11 @@ export const createWorkflowStore = () => {
    * @param errors - Field errors { fieldName: ["error1", "error2"] }
    *                 Empty array [] clears that field
    */
-  const setClientErrors = (path: string, errors: Record<string, string[]>) => {
+  const setClientErrors = (
+    path: string,
+    errors: Record<string, string[]>,
+    isServerUpdates: boolean = false
```
Comment (elias-ba) [inline assets/js/collaborative-editor/stores/createWorkflowStore.ts]: I note that we have elsewhere `isServerUpdate` (singular). Is this variable name with `s` at the end a typo ?

**Review by elias-ba — CHANGES_REQUESTED** [review]
Hey @doc-han this new architecture you are proposing is so much better. Nice job man. I have few observations. Would love to hear your thoughts.

Also it seems like the `isServerUpdate` detection logic is the core of this fix. I am wondering whether it would be valuable to add a test case verifying the priority behavior when two users edit simultaneously ?

File: assets/js/collaborative-editor/stores/createWorkflowStore.ts (hunk 3 above)
Comment (doc-han) [reply assets/js/collaborative-editor/stores/createWorkflowStore.ts]: yeah a typo

File: assets/js/collaborative-editor/components/form/index.tsx (hunk 2 above)
Comment (doc-han) [reply assets/js/collaborative-editor/components/form/index.tsx:117]: I wanted to have clearance with @stuartc on that given the npm registry is scary these days. I already background checked on this package and it seemed to have no dependencies which is good but the things that make it better than `JSON.stringify` are things we might not need now and also I saw `JSON.stringify` technique already being used in the repo elsewhere

File: assets/js/collaborative-editor/components/inspector/JobForm.tsx (hunk 1 above)
Comment (doc-han) [reply assets/js/collaborative-editor/components/inspector/JobForm.tsx:124]: I'll have to double check. I think it's safe to remove because both `adaptor` and `adaptor_package` come is through Ydoc.

Comment (doc-han) [reply assets/js/collaborative-editor/components/inspector/JobForm.tsx:124]: I've confirmed that both `adaptor` & `adaptor_package` values come through ydoc. Hence, we might not need to resolve whenever we get an update. 

We already handle such resolution in the `handleAdaptorSelect` function in this file

**Review by midigofrank — COMMENTED** [review]
Hey @doc-han , I have seen a very weird bug while testing:

I added an invalid job name and hit save, suddenly all jobs were marked with errors, telling me something about "uniqueness". 

Sadly, this only happened once, haven't been able to recreate. Could you try to see if you can recreate it on your end? I'm happy to approve if you're confident it's not related to these changes

**Comment by doc-han** [comment]
> Hey @doc-han , I have seen a very weird bug while testing:
> 
> I added an invalid job name and hit save, suddenly all jobs were marked with errors, telling me something about "uniqueness".
> 
> Sadly, this only happened once, haven't been able to recreate. Could you try to see if you can recreate it on your end? I'm happy to approve if you're confident it's not related to these changes

I think a way to reproduce that is to have multiple jobs with the same name before hitting save. We currently don't to client side validation for uniqueness. Hence, when you have multiple jobs with the same name, no error shows up until you hit save.

Similar to #4169 
It's related to what I was discussing with you this morning around why we do error merging on the server side.

**Comment by elias-ba** [comment]
Mhm 🤔 we should probably do something about that. At least open an issue for it. Because I think that's a very common user behavior to add multiple jobs then hit save one time. What do you guys think ?

**Comment by doc-han** [comment]
> Mhm 🤔 we should probably do something about that. At least open an issue for it. Because I think that's a very common user behavior to add multiple jobs then hit save one time. What do you guys think ?

I'm thinking #4169 is the issue
