### PR TITLE
Fix: Redesign version mismatch banner and improve collapsing history when run is selected

### LINKED ISSUE #4044: Mini History panel hides the toast message after running a workflow
Mini History panel hides the toast message after running a workflow

When you run a workflow and then add a new step, the Mini History panel opens and cannot be collapsed. Because of this, the toast message at the bottom of the screen gets pushed down and is hidden.

**Steps to Reproduce:**
1. Open a workflow in the Collab Editor.
2. Run the workflow.
3. Add a new step.
4. The Mini History panel opens and the toast message is hidden.

**Expected Behavior:**
The Mini History panel should be collapsible, and the toast message should always stay visible.

**Screenshot:**
https://www.loom.com/share/d4d9e86976784d0bb8db5b37c39ba8bd

Image

### PR DESCRIPTION
**Pull request by lmac-1**
## Description

This PR fixes the version mismatch banner layout issues and improves collapsing the history panel when a run is selected.

### Changes

**1. Improves the UX of the version mismatch banner:** 
- Simplified and made message shorter - now says:
```
    Canvas shows {version} (Selected run: {version}) 
    Canvas layout may differ from actual run
```
- Made it appear top centre on top of everything else (only if resized to a smaller screen)
- Made it dismissible
- Updated icon to be information rather than warning, less invasive
- Adds tests for this component

Before 
image  

After:
image 

**2. Improve history panel collapse behaviour with run chip**:
- There was a bug in main where if you tried to collapse history when a run was selected, nothing happened
- Now, when user collapses the `MiniHistory` panel, the selected run is maintained
- A minimal `RunChip` appears in the collapsed panel showing the truncated run ID with an X button
image

- This `RunChip` component is new (inline code taken from FullScreenIDE) and I've refactored FullScreenIDE to use the same component

image

Before: 
- If a run is selected in MiniHistory + user tries to collapse history -> nothing happens, panel stayed expanded.

Now:
- If a run is selected in MiniHistory + user tries to collapse history -> panel collapses, chip appears in 2nd line showing selected run
- User maintains run selection context even when panel is collapsed
- Click X on chip to explicitly deselect run and clear URL parameter
- Updating versions in VersionDropdown does not have any affect on collapse behaviour of history panel

Closes #4044

## Validation steps

**Version mismatch banner**
- Create or select a workflow with multiple versions
- Select a run from history (panel auto expands)
- Manually change the workflow version dropdown to a different version
- Verify compact banner appears at top-center with message: "Canvas shows vX (Selected run: vY"
- Click the X button to dismiss the banner
- Verify banner disappears
- Repeat the steps again with a different node + previous version -> banner should appear again

**Test collapse-to-deselect behaviour**
- Select a run from history 
- Verify that run is in the URL `?run=xxx`
- Click to collapse the MiniHistory panel (click where the title is)
- Verify that the panel collapses with a second row with `RunChip` with runID and x button to deselect run
- Click X on the run and verify that URL no longer contains `?run=xxx` parameter and that run is no longer selected on diagram
- Collapse/open history with runs in context and not in context
- Try changing versions on the version dropdown and make sure this does not open/close history. It should stay the same.

**Full screen IDE**
Verify that RunChip looks as expected and that "X" works: 
image

## Additional notes for the reviewer

**Banner placement:** The first iteration was a banner underneath the header (similar to multi-tab warning in old editor), but this pushed the canvas down. Considered putting it inside `MiniHistory` panel but felt too cluttered. Also tried bottom-left corner, but users might miss it there. This PR positions it top-center instead, avoiding layout shifts while maintaining visibility. Open to feedback on positioning or message clarity.

**Collapse history behaviour**:  When you share a URL with `?run=xxx`, the recipient will see the history panel collapsed by default (showing just the run chip), rather than auto-expanded:

image

This change prevents a bug where changing the version dropdown would unexpectedly re-open the collapsed history panel. The fix for auto-expanding required complex ref tracking and useEffect dependencies that felt a bit brittle. But, let me know if you'd prefer auto-expand when opening URLs with runs.
**NOTE:** If you've previously collapsed/expanded the panel, your preference is still remembered due to localStorage (this is the same as before). For example, if you have a run selected and history expanded and refresh the page, it will look the same.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [x] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [ ] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/diagram/CollaborativeWorkflowDiagram.tsx [hunk 1]
```diff
@@ -66,8 +73,17 @@ export function CollaborativeWorkflowDiagram({
   }, [selectedRunId, historyCollapsed, setHistoryPanelCollapsed]);
 
   const handleToggleHistory = useCallback(() => {
+    // If collapsing the panel and a run is selected, deselect it
+    if (!historyCollapsed && selectedRunId) {
+      handleDeselectRun();
+    }
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/diagram/CollaborativeWorkflowDiagram.tsx]: I don't know if we actually want to deselect the active run when the mini-history is collapsed. 
From our old editor, collapsing the panel has no effect on the canvas (because you might be collapsing in order to see some history nodes hidden by it)

I think this is something to discuss with a product person @theroinaochieng @taylordowns2000

**Review by doc-han — CHANGES_REQUESTED** [review]

**Comment by lmac-1** [comment]
@taylordowns2000 @doc-han thanks both for your reviews. I've updated the code so it now keeps the run in context when you collapse history. 

I've updated the PR description and title to reflect and describe these changes. Please have a read. I've also added some extra notes to "Additional notes for reviewer" for your consideration. Any questions, doubts or further changes, let me know! Thanks ☺️

**Review by taylordowns2000 — APPROVED** [review]
looks good @lmac-1 ! i've also standardized the badges (and called them badges, rather than "chips" to align with tailwind-ui) across elixir and react to deal with a vertical alignment issue. ready for this to go in.
