### PR TITLE
fix: infinite loading when reopening workflow in collaborative editor

### LINKED ISSUE #4164: Infinite loading when opening workflow "Any workflow 1"
**Describe the bug** When opening workflows "Any workflow 1" under the QA project with fast workers, the workflow editor gets stuck in an infinite loading state.

**Version number** v2.15.0-pre4

I have reproduced this locally on main:

- [ ] Yes
- [ x] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to  project '[qa-project-with-fast-workers](https://app.staging.openfn.org/projects/7ca57ff5-df60-4106-bc7c-ae5ea866c028/w)'
2. Click on 'Any workflow 1'
3. See the error; 

Additionally in the video I have created a new workflow from the same template which I did before. Not sure it's the template problem tho. 

**Expected behavior** Workflow should open normally

Loom: https://www.loom.com/share/4751e050c4de45ea8413dfec691cf843

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR **fixes** the infinite loading issue when reopening a workflow in the collaborative editor.

**1. `extract_lock_version` not handling `nil` values (`persistence.ex`)**

When a workflow is opened before first save, the Y.Doc gets `lock_version: nil`. The `extract_lock_version/1` function didn't handle the `{:ok, nil}` case from `Yex.Map.fetch/2`, causing it to fall through incorrectly. The `stale?/2` function was also refactored for clarity.

**2. `merge_updates` applying deltas to empty doc (`persistence_writer.ex`)**

This was the root cause of the infinite loading. When the `PersistenceWriter` batches multiple Yjs updates together, `merge_updates/1` was applying them to an empty `Yex.Doc.new()`. Since Yjs deltas only contain changes (not full state), applying them to an empty doc produced corrupted 2-byte outputs, losing all workflow data.

**Evidence from reproduction:**
- Before fix: merged updates = 2 bytes (corrupted/empty)
- After fix: merged updates = 969-1742 bytes (correct full state)

The fix loads the existing persisted state (checkpoint + updates) from the database before applying new deltas on top.

### How this caused the `nil` lock_version crash

1. **User creates new workflow** → Y.Doc initialized with `lock_version: nil`
2. **After 2s debounce** → First batch saved with full state (including `lock_version: nil`) ~1000 bytes ✓
3. **User saves workflow** → DB gets real `lock_version`, Y.Doc updated via `merge_saved_workflow_into_ydoc`
4. **This generates a delta update** → Only contains the `lock_version` change
5. **After 2s debounce** → `merge_updates` merges pending deltas
6. **BUG**: Deltas applied to empty doc → Produces 2-byte corrupted output, **lock_version update lost**
7. **User reopens workflow** → Loads first update (`lock_version: nil`) + corrupted update (2 bytes)
8. **Result**: Y.Doc has `lock_version: nil`, DB has real value → stale check fails → crash

Closes #4164 #4154

## Validation steps

1. Create a new workflow in collab editor and save it
2. Add a job node (but don't save)
3. Navigate back to workflows list
4. Open the workflow again
5. Verify workflow loads correctly (no infinite loading)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [x] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/collaboration/persistence_writer.ex [hunk 1]
```diff
@@ -355,13 +357,19 @@ defmodule Lightning.Collaboration.PersistenceWriter do
       {:error, exception}
   end
 
-  defp merge_updates([update]), do: update
+  defp merge_updates([update], _document_name), do: update
```
Comment (doc-han) [inline lib/lightning/collaboration/persistence_writer.ex:360]: The fix for my issue #4154  overlaps with what you're doing here. I want to get rid of this function all together. If there's a single update **doesn't mean that**

1. we don't want to generate a delta between the current state of the document(`_document_name`)
2. also, properly encode the changes using `Yex.encode_state_as_update!`

with 2. I don't think that just returning the single update is the same as passing it through a new doc and encoding.

Comment (doc-han) [reply lib/lightning/collaboration/persistence_writer.ex:360]: On my end, I've consistently reproduced the error whenever there's a single update coming through ydoc which leads to this function. checking whether I can reproduce on this branch.

Comment (doc-han) [reply lib/lightning/collaboration/persistence_writer.ex:360]: Awesome. I think this PR fixes #4154 also. just revalidated whether a single update coming through causes an issue and it actually doesn't. Hence the issue with #4154 also had to do with the corrupted bytes. Took me a long route to get to `merge_updates` function.

**Review by taylordowns2000 — COMMENTED** [review]
@elias-ba , sadly, i'm not able to reproduce the bug on `main` here so i cant approve this one either. when you're online this morning maybe you can help?
