### PR TITLE
QA: Fix AI Assistant message status not updating on Apollo timeout

### LINKED ISSUE #3497: Oban crash when Apollo times out
(Note that this comes immediately _after_ this ["Processor Timeout"](https://openfn.sentry.io/issues/6796142944/?environment=staging&project=6446500&query=is%3Aunresolved&referrer=issue-stream) warning.

Sentry Issue: [LIGHTNING-139](https://openfn.sentry.io/issues/6796142951/?referrer=github_integration)

```
Oban exception:
%Oban.TimeoutError{message: "Lightning.AiAssistant.MessageProcessor timed out after 31000ms", reason: :timeout}


meta:
  %{
  args: %{
    "message_id" => "2381d522-2a55-499f-b7fb-4feff4acc9d0",
    "session_id" => "d5e0210b-b906-4c3b-95d7-9aa587b5c01e"
  },
  id: 1932975,
  reason: %Oban.TimeoutError{
    message: "Lightning.AiAssistant.MessageProcessor timed out after 31000ms",
    reason: :timeout
  },
  state: :discard,
  max_attempts: 1,
  queue: "ai_assistant",
  worker: "Lightning.AiAssistant.MessageProcessor",
  prefix: "public",
  result: nil,
  conf: %Oban.Config{
    dispatch_cooldown: 100,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    insert_trigger: true,
    log: false,
    name: Lightning.Oban,
    node: "[email]",
    notifier: {Oban.Notifiers.Postgres, []},
    peer: {Oban.Peers.Database, []},
    plugins: [
      {Oban.Plugins.Cron,
       [
         crontab: [
           {"* * * * *", Lightning.Workflows.Scheduler},
           {"* * * * *", ObanPruner},
           {"*/5 * * * *", Lightning.Janitor},
           {"0 10 * * *", Lightning.DigestEmailWorker,
            [args: %{"type" => "daily_project_digest"}]},
           {"0 10 * * 1", Lightning.DigestEmailWorker,
            [args: %{"type" => "weekly_project_digest"}]},
           {"0 10 1 * *", Lightning.DigestEmailWorker,
            [args: %{"type" => "monthly_project_digest"}]},
           {"17 */2 * * *", Lightning.Projects,
            [args: %{"type" => "data_retention"}]},
           {"*/10 * * * *",
            Lightning.KafkaTriggers.DuplicateTrackingCleanupWorker},
           {"15 2 * * *", Lightning.Accounts,
            [args: %{"type" => "purge_deleted"}]},
           {"30 2 * * *", Lightning.Credentials,
            [args: %{"type" => "purge_deleted"}]},
           {"45 2 * * *", Lightning.Projects,
            [args: %{"type" => "purge_deleted"}]},
           {"0 3 * * *", Lightning.WebhookAuthMethods,
            [args: %{"type" => "purge_deleted"}]}
         ]
       ]}
    ],
    prefix: "public",
    queues: [
      scheduler: [limit: 1],
      workflow_failures: [limit: 1],
      background: [limit: 1],
      history_exports: [limit: 1],
      ai_assistant: [limit: 10]
    ],
    repo: Lightning.Repo,
    shutdown_grace_period: 120000,
    stage_interval: 1000,
    testing: :disabled
  },
  kind: :error,
  job: %Oban.Job{
    __meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">,
    id: 1932975,
    state: "executing",
    queue: "ai_assistant",
    worker: "Lightning.AiAssistant.MessageProcessor",
    args: %{
      "message_id" => "2381d522-2a55-499f-b7fb-4feff4acc9d0",
      "session_id" => "d5e0210b-b906-4c3b-95d7-9aa587b5c01e"
    },
    meta: %{},
    tags: [],
    errors: [],
    attempt: 1,
    attempted_by: ["[email]",
     "4d820558-8b0f-4c01-9b63-96ba79b35780"],
    max_attempts: 1,
    priority: 0,
    attempted_at: ~U[2025-08-07 09:40:10.121204Z],
    cancelled_at: nil,
    completed_at: nil,
    discarded_at: nil,
    inserted_at: ~U[2025-08-07 09:40:09.920614Z],
    scheduled_at: ~U[2025-08-07 09:40:09.920614Z],
    conf: %Oban.Config{
      dispatch_cooldown: 100,
      engine: Oban.Engines.Basic,
      get_dynamic_repo: nil,
      insert_trigger: true,
      log: false,
      name: Lightning.Oban,
      node: "[email]",
      notifier: {Oban.Notifiers.Postgres, []},
      peer: {Oban.Peers.Database, []},
      plugins: [
        {Oban.Plugins.Cron,
         [
           crontab: [
             {"* * * * *", Lightning.Workflows.Scheduler},
             {"* * * * *", ObanPruner},
             {"*/5 * * * *", ...},
             {...},
             ...
           ]
         ]}
      ],
      prefix: "public",
      queues: [
        scheduler: [limit: 1],
        workflow_failures: [limit: 1],
        background: [limit: 1],
        history_exports: [limit: 1],
        ai_assistant: [limit: 10]
      ],
      repo: Lightning.Repo,
      shutdown_grace_period: 120000,
      stage_interval: 1000,
      testing: :disabled
    },
    conflict?: false,
    replace: nil,
    unique: nil,
    unsaved_error: %{
      reason: %Oban.TimeoutError{
        message: "Lightning.AiAssistant.MessageProcessor timed out after 31000ms",
        reason: :timeout
      },
      stacktrace: [],
      kind: :error
    }
  },
  attempt: 1,
  tags: []
}
(%{
  memory: 39840,
  reductions: 380034,
  duration: 31001691526,
  queue_time: 200590000
})

```

### PR DESCRIPTION
**Pull request by elias-ba**
## Description
This PR fixes an issue where AI Assistant messages would get stuck in "pending" state when Apollo times out, preventing users from seeing error feedback or retrying.

This PR fixes also a bug in the Workflow Canvas where the users could still enable or disable a workflow when viewing in snapshot mode.

Closes #3497 

@elias-ba believes that #3498 will also be addressed by this PR - I am linking it here but not tagging for closure as it must be verified separately.

## Validation steps
1. **Test Apollo timeout handling:**
   - Temporarily set a very low timeout in MessageProcessor (e.g., `def timeout(_job), do: 10`)
   - Send a message in the AI Assistant
   - Verify the message shows error status in the UI after timeout
   - Verify the retry button appears and works

2. **Test normal flow still works:**
   - Restore normal timeout
   - Send a regular AI message
   - Verify it processes successfully

3. **Test ObanManager safety net:**
   - Check logs for `[AI Assistant] Updating message X to error status after exception`
   - Verify Sentry receives proper "AI Assistant Timeout" events (need to configure Sentry)

4. **Test bug when viewing a snapshot in workflow canvas**
    - Open a snapshot
    - See that workflow enable / disable toggle is not rendered

## Additional notes for the reviewer
1. The core issue was that we were broadcasting stale session data. After updating a message status in the DB, we now reload the session to get fresh data before broadcasting.

2. Added a safety net in `ObanManager` that catches AI assistant queue exceptions and ensures messages don't get stuck in pending state.

3. Fixed the timeout buffer calculation - removed hardcoded `10` that was overriding the dynamic calculation.

4. No database migrations needed - only runtime behavior changes.

## AI Usage
Please disclose how you've used AI in this work (it's cool, we just want to know!):
- [ ] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist
- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/oban_manager.ex [hunk 1]
```diff
@@ -23,17 +36,146 @@ defmodule Lightning.ObanManager do
...
+  def handle_event(
+        [:oban, :job, :stop],
+        measure,
+        %{job: %{queue: "ai_assistant"}} = meta,
+        _pid
+      ) do
+    handle_ai_assistant_stop(measure, meta)
+  end
+
+  def handle_event([:oban, :job, :stop], _measure, _meta, _pid), do: :ok
```
Comment (taylordowns2000) [inline lib/lightning/oban_manager.ex:60]: is this necessary? if there isn't a match, will it simply fall through or without a match were we getting no-match errors when running runs/doing other oban stuff?

File: lib/lightning/oban_manager.ex [hunk 2]
```diff
@@ -23,17 +36,146 @@ defmodule Lightning.ObanManager do
...
+
+  defp handle_ai_assistant_exception(measure, meta) do
```
Comment (taylordowns2000) [inline lib/lightning/oban_manager.ex]: these two defps are a LOT of code to have in the generic oban_manager. should they be moved to some sort of module that relates to ai chat? (maybe `message_processor` or `ai_assistant`?)

Comment (elias-ba) [reply lib/lightning/oban_manager.ex]: Yeah I like the idea

File: lib/lightning/oban_manager.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning/oban_manager.ex:60]: Sorry @taylordowns2000 I don't quite understand the questions here

File: lib/lightning/oban_manager.ex (hunk 2 above)
Comment (elias-ba) [reply lib/lightning/oban_manager.ex]: Great, I moved them in the MessageProcessor module. Thanks for the idea

File: lib/lightning/oban_manager.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning/oban_manager.ex:60]: If you're asking whether the `:stop` is necessary or not. I would say yes it is, it allows us to verify what status the job did stop with, and we take actions depending on the status. Kind of a catch all

Comment (taylordowns2000) [reply lib/lightning/oban_manager.ex:60]: No, I'm wondering why you have a `do: :ok` here:

```ex
def handle_event([:oban, :job, :stop], _measure, _meta, _pid), do: :ok
```

**Comment by elias-ba** [comment]
Hey @taylordowns2000, thanks for the approval.

I agree with you, this doesn’t address the workflow diagram bug involving trigger duplication and node collapsing. I spent about an hour investigating it last Friday and have some strong hypotheses about the cause, though I’m not fully certain yet. I opened this issue this morning so I can dig into it properly on Monday: #3506

**Review by midigofrank — CHANGES_REQUESTED** [review]
Hey @elias-ba , I'm a little worried about the approach used here. I think using telemetry events to update the message status would be over-relying on Oban.

It is a timeout during the http call right? Can't we just handle that instead of using telemetry?

**Comment by elias-ba** [comment]
> Hey @elias-ba , I'm a little worried about the approach used here. I think using telemetry events to update the message status would be over-relying on Oban.
> 
> It is a timeout during the http call right? Can't we just handle that instead of using telemetry?

Hey @midigofrank, great question. The thing is, we do want to this for any type of failure event, including when Oban fails. This is a direct consequence of us relying on Oban to process the messages.

**Comment by midigofrank** [comment]
> Hey @midigofrank, great question. The thing is, we do want to this for any type of failure event, including when Oban fails. This is a direct consequence of us relying on Oban to process the messages.

I get that but it still feels like we're outsourcing a core logic to Oban. The sentry exceptions are fine because the app can work fine without them, but marking a message status as failed because of apollo timeout is a core thing.

EDIT:
Handling this within would make it easy to swap out Oban with another thing like a Task

**Comment by elias-ba** [comment]
Hey @midigofrank, I agree with you on the coupling aspect of this design and that error handling belongs in the domain layer. Since this PR is focused on a specific QA bug fix, I’ve opened [an issue here](https://github.com/OpenFn/lightning/issues/3514) to track your idea and implement it properly in a follow-up. That feels more responsible (and cheaper) than introducing these structural changes here. What do you think?

**Comment by midigofrank** [comment]
Okay, that sounds good
