### PR TITLE
Fix blank modal showing when you click to show webhook auth method password

### LINKED ISSUE #3154: Webhook Auth Method Editing Fails with Unexpected Redirect
Users encounter an unexpected redirect when attempting to save or edit webhook authentication methods, preventing them from successfully updating their webhook configurations.

**Version number** v.2.11.2

If you're running on a tagged version, include the number: Also shows up on staging: v.2.11.3-pre.2

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to project settings
2. Click on webhook security
3. Try to edit an existing auth method
4. See When you click the username or password field they are unclickable
5. See when you click the show button on the password field, you get a get a weird blank modal
6. See error**Expected behavior** A clear and concise description of what you expected tohappen.

See this Loom video: https://www.loom.com/share/b55e8304f0184d67a46826af2278668e?sid=1c72af9d-27aa-492b-949a-39ea9e09a35c

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

This PR fixes an issue where after clicking to show the password or api key, the modal goes blank. It seems liveview doesn't like changing/replacing of the root html tag, which is what we were doing. 

When you click `show` on the password/api field of the form, the intention is to show you a page to `reauthenticate`. What we were doing previously is matching against the `render/1` function and changing the root html.

Please ignore the large diff, all I have done is moved the 2 `render/ heads` into 2 different function components 

Closes #3154

## Validation steps

1. Go to project settings page and click to add a new webhook auth method under the `Webhook Security` tab. 
2. Click to edit that auth method. A modal will appear. 
3. On the `password/api key` field, click the `show` button. 
4. A form to re-authenticate the user appears. Previously, this blank

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Review by taylordowns2000 — APPROVED** [review]

File: lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex [hunk 1]
```diff
@@ -270,157 +270,163 @@ defmodule LightningWeb.WorkflowLive.WebhookAuthMethodFormComponent do
...
-          <%= if @error_msg do %>
-            <div class="alert alert-danger" role="alert">
-              {@error_msg}
-            </div>
+    <div id={"write_webhook_auth_method_#{@id}"}>
+      <%= if @action == :edit and @show_2fa_options do %>
+        <.authenticate_user_form {assigns} />
+      <% else %>
+        <.webhook_auth_method_form {assigns} />
+      <% end %>
```
Comment (jyeshe) [inline lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex:280]: Nice move! I think we should do the same, creating function components for this `case do` https://github.com/OpenFn/lightning/blob/9d8efdf36d94e558692e8e12a2b86775f650acac/lib/lightning_web/live/workflow_live/webhook_auth_method_form_component.ex#L356

**Review by jyeshe — CHANGES_REQUESTED** [review]
Looks great Frank. I missed only two things: 
- adapting any test case to cover this a bit. I think we would benefit as well
- creating (sub)components for webhook auth possibilities: basic and api

**Review by jyeshe — APPROVED** [review]
Well done Frank!
