### PR TITLE
Finish implementation of "delete user"

### LINKED ISSUE #747: Finish implementation of "delete user"
@elias-ba has confirmed that in resolution of this issue he will handle every user relation in the app:

- [x] credential.user_id
- [x] invocation_reason.user_id
- [x] project_user.user_id

## Initial bug report

**Describe the bug** 
Every day, we check for users that have been scheduled for deletion and delete users. The oban job is running ok, but the command is failing because of database constraints which means that users that _should_ be deleted aren't 

**Version number** `v0.4.6`
I have reproduced this locally on main:
- [x] Yes
- [ ] No

**To Reproduce** 

1. In runtime.exs, update line 39 to check users for deletion every minute `{"* * * * *", Lightning.Accounts, args: %{"type" => "purge_deleted"}},` 
2. Run Lightning
3. Log in as a superuser
4. Delete a user
5. Edit the scheduled for deletion time to 1 minute from now
6. Wait one minute
7. See user is not deleted and there is an error in the terminal (stack trace posted below)

**Expected behaviour** 
The user should be deleted and removed from any project they are part of. 
When a user is scheduled for deletion, check if any of their resources (ex: credentials) are being used in existing projects. 

**Additional context** 

Stack trace below: 
```
[error] Oban exception:
%RuntimeError{message: "you are attempting to change relation :project_users of\nLightning.Projects.Project but the `:on_replace` option of this relation\nis set to `:raise`.\n\nBy default it is not possible to replace or delete embeds and\nassociations during `cast`. Therefore Ecto requires the parameters\ngiven to `cast` to have IDs matching the data currently associated\nto Lightning.Projects.Project. Failing to do so results in this error message.\n\nIf you want to replace data or automatically delete any data\nnot sent to `cast`, please set the appropriate `:on_replace`\noption when defining the relation. The docs for `Ecto.Changeset`\ncovers the supported options in the \"Associations, embeds and on\nreplace\" section.\n\nHowever, if you don't want to allow data to be replaced or\ndeleted, only updated, make sure that:\n\n  * If you are attempting to update an existing entry, you\n    are including the entry primary key (ID) in the data.\n\n  * If you have a relationship with many children, all children\n    must be given on update.\n\n"}
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:238: Ecto.Changeset.Relation.on_replace/2
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:409: Ecto.Changeset.Relation.reduce_delete_changesets/5
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:121: Ecto.Changeset.Relation.cast/5
    (ecto 3.9.4) lib/ecto/changeset.ex:832: Ecto.Changeset.cast_relation/4
    (lightning 0.4.6) lib/lightning/projects/project.ex:37: Lightning.Projects.Project.changeset/2
    (lightning 0.4.6) lib/lightning/projects.ex:112: Lightning.Projects.update_project/2
    (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (lightning 0.4.6) lib/lightning/accounts.ex:34: Lightning.Accounts.purge_user/1
    (elixir 1.14.2) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (lightning 0.4.6) lib/lightning/accounts.ex:76: Lightning.Accounts.perform/1
    (oban 2.14.2) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
    (oban 2.14.2) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1
    (elixir 1.14.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.2) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

meta:
  %{
  args: %{"type" => "purge_deleted"},
  attempt: 1,
  conf: %Oban.Config{
    dispatch_cooldown: 100,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    log: false,
    name: Oban,
    node: "ambers-MacBook-Air",
    notifier: Oban.Notifiers.Postgres,
    peer: Oban.Peers.Postgres,
    plugins: [
      {Oban.Plugins.Cron,
       [
         crontab: [
           {"* * * * *", Lightning.Jobs.Scheduler},
           {"* * * * *", ObanPruner},
           {"* * * * *", Lightning.Accounts,
            [args: %{"type" => "purge_deleted"}]},
           {"0 10 * * *", Lightning.DigestEmailWorker,
            [args: %{"type" => "daily_project_digest"}]},
           {"0 10 * * MON", Lightning.DigestEmailWorker,
            [args: %{"type" => "weekly_project_digest"}]},
           {"0 10 1 * *", Lightning.DigestEmailWorker,
            [args: %{"type" => "monthly_project_digest"}]}
         ]
       ]}
    ],
    prefix: "public",
    queues: [
      scheduler: [limit: 1],
      workflow_failures: [limit: 1],
      background: [limit: 1],
      runs: [limit: 4]
    ],
    repo: Lightning.Repo,
    shutdown_grace_period: 60000,
    stage_interval: 1000,
    testing: :disabled
  },
  id: 8224,
  job: %Oban.Job{
    __meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">,
    id: 8224,
    state: "executing",
    queue: "background",
    worker: "Lightning.Accounts",
    args: %{"type" => "purge_deleted"},
    meta: %{},
    tags: [],
    errors: [],
    attempt: 1,
    attempted_by: ["ambers-MacBook-Air"],
    max_attempts: 1,
    priority: 0,
    attempted_at: ~U[2023-03-29 09:18:00.289256Z],
    cancelled_at: nil,
    completed_at: nil,
    discarded_at: nil,
    inserted_at: ~U[2023-03-29 09:18:00.026985Z],
    scheduled_at: ~U[2023-03-29 09:18:00.026985Z],
    conf: %Oban.Config{
      dispatch_cooldown: 100,
      engine: Oban.Engines.Basic,
      get_dynamic_repo: nil,
      log: false,
      name: Oban,
      node: "ambers-MacBook-Air",
      notifier: Oban.Notifiers.Postgres,
      peer: Oban.Peers.Postgres,
      plugins: [
        {Oban.Plugins.Cron,
         [
           crontab: [
             {"* * * * *", Lightning.Jobs.Scheduler},
             {"* * * * *", ObanPruner},
             {"* * * * *", Lightning.Accounts,
              [args: %{"type" => "purge_deleted"}]},
             {"0 10 * * *", Lightning.DigestEmailWorker,
              [args: %{"type" => "daily_project_digest"}]},
             {"0 10 * * MON", Lightning.DigestEmailWorker,
              [args: %{"type" => "weekly_project_digest"}]},
             {"0 10 1 * *", Lightning.DigestEmailWorker,
              [args: %{"type" => "monthly_project_digest"}]}
           ]
         ]}
      ],
      prefix: "public",
      queues: [
        scheduler: [limit: 1],
        workflow_failures: [limit: 1],
        background: [limit: 1],
        runs: [limit: 4]
      ],
      repo: Lightning.Repo,
      shutdown_grace_period: 60000,
      stage_interval: 1000,
      testing: :disabled
    },
    conflict?: false,
    replace: nil,
    unique: nil,
    unsaved_error: %{
      kind: :error,
      reason: %RuntimeError{
        message: "you are attempting to change relation :project_users of\nLightning.Projects.Project but the `:on_replace` option of this relation\nis set to `:raise`.\n\nBy default it is not possible to replace or delete embeds and\nassociations during `cast`. Therefore Ecto requires the parameters\ngiven to `cast` to have IDs matching the data currently associated\nto Lightning.Projects.Project. Failing to do so results in this error message.\n\nIf you want to replace data or automatically delete any data\nnot sent to `cast`, please set the appropriate `:on_replace`\noption when defining the relation. The docs for `Ecto.Changeset`\ncovers the supported options in the \"Associations, embeds and on\nreplace\" section.\n\nHowever, if you don't want to allow data to be replaced or\ndeleted, only updated, make sure that:\n\n  * If you are attempting to update an existing entry, you\n    are including the entry primary key (ID) in the data.\n\n  * If you have a relationship with many children, all children\n    must be given on update.\n\n"
      },
      stacktrace: [
        {Ecto.Changeset.Relation, :on_replace, 2,
         [
           file: 'lib/ecto/changeset/relation.ex',
           line: 238,
           error_info: %{module: Exception}
         ]},
        {Ecto.Changeset.Relation, :reduce_delete_changesets, 5,
         [file: 'lib/ecto/changeset/relation.ex', line: 409]},
        {Ecto.Changeset.Relation, :cast, 5,
         [file: 'lib/ecto/changeset/relation.ex', line: 121]},
        {Ecto.Changeset, :cast_relation, 4,
         [file: 'lib/ecto/changeset.ex', line: 832]},
        {Lightning.Projects.Project, :changeset, 2,
         [file: 'lib/lightning/projects/project.ex', line: 37]},
        {Lightning.Projects, :update_project, 2,
         [file: 'lib/lightning/projects.ex', line: 112]},
        {Enum, :"-each/2-lists^foreach/1-0-", 2,
         [file: 'lib/enum.ex', line: 975]},
        {Lightning.Accounts, :purge_user, 1,
         [file: 'lib/lightning/accounts.ex', line: 34]},
        {Enum, :"-each/2-lists^foreach/1-0-", 2,
         [file: 'lib/enum.ex', line: 975]},
        {Lightning.Accounts, :perform, 1,
         [file: 'lib/lightning/accounts.ex', line: 76]},
        {Oban.Queue.Executor, :perform, 1,
         [file: 'lib/oban/queue/executor.ex', line: 129]},
        {Oban.Queue.Executor, :call, 1,
         [file: 'lib/oban/queue/executor.ex', line: 74]},
        {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', ...]},
        {Task.Supervised, :reply, 4, [...]},
        {:proc_lib, :init_p_do_apply, 3, ...}
      ]
    }
  },
  kind: :error,
  max_attempts: 1, (truncated)
```

### PR DESCRIPTION
**Pull request by elias-ba**
## Related issue

Fixes #747 

## Checklist before requesting a review

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

### CODE REVIEW

**Review by amberrignell — CHANGES_REQUESTED** [review]

File: test/lightning/accounts_test.exs [hunk 1]
```diff
@@ -282,36 +284,120 @@ defmodule Lightning.AccountsTest do
...
+      refute Repo.all(Credentials.Credential)
+             |> Enum.any?(fn x -> x.user_id == user_1.id end)
+
+      assert Repo.all(Credentials.Credential)
+             |> Enum.any?(fn x -> x.user_id == user_2.id end)
     end
   end
 
   describe "The default Oban function Accounts.perform/1" do
+    test "Users with ongoing activities in live projects are never deleted" do
```
[the remark this answers is not in the document]
Comment (elias-ba) [reply test/lightning/accounts_test.exs:381]: Done

File: lib/lightning/accounts.ex [hunk 2]
```diff
@@ -24,33 +45,54 @@ defmodule Lightning.Accounts do
...
-                Enum.find(p.project_users, fn pu -> pu.user_id == id end)
-                |> Map.get(:id)
-            }
-          }
-        }
-      )
+    |> Enum.map(fn p ->
+      {p, %{"project_users" => project_users_to_params(p.project_users, id)}}
     end)
+    |> Enum.each(fn {project, param} ->
```
Comment (stuartc) [inline lib/lightning/accounts.ex:54]: Why are we using params to work with changesets here? Usually params are used to work with requests from outside the application, like forms and http etc.

This should do the same thing.

```elixir
Ecto.assoc(%User{id: id}, :project_users) |> Repo.delete_all()
```

There's nothing wrong with working with params, they can be very useful when generating new records from nothing. But in this case, it can be solved with a query.

File: lib/lightning/accounts.ex [hunk 3]
```diff
@@ -24,33 +45,54 @@ defmodule Lightning.Accounts do
...
+
+    # Set null all jobs using credentials
+    :ok =
+      from(job in Lightning.Jobs.Job,
+        where: job.project_credential_id in ^user_project_credentials_ids
+      )
+      |> Repo.all()
+      |> Enum.each(fn job ->
+        Lightning.Jobs.update_job(job, %{credential_id: nil})
+      end)
```
Comment (stuartc) [inline lib/lightning/accounts.ex:83]: Again this can be addressed with a query, avoiding loading stuff into memory.

```suggestion
project_credentials_for_user =
  Ecto.assoc(user, [:credentials, :project_credentials])

from(j in Job,
  join: pc in subquery(project_credentials_for_user),
  on: pc.id == j.project_credential_id
)
|> Repo.update_all(set: [project_credential_id: nil])
```

Please look at all the queries here where you are iterating over lists and see how it can be written using queries only.

See: 
https://hexdocs.pm/ecto/Ecto.html#assoc/3
https://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3
https://hexdocs.pm/ecto/Ecto.Repo.html#c:delete_all/2

File: lib/lightning/accounts.ex [hunk 4]
```diff
@@ -24,33 +45,54 @@ defmodule Lightning.Accounts do
...
+
+    # Set null all jobs using credentials
+    :ok =
+      from(job in Lightning.Jobs.Job,
+        where: job.project_credential_id in ^user_project_credentials_ids
+      )
+      |> Repo.all()
+      |> Enum.each(fn job ->
+        Lightning.Jobs.update_job(job, %{credential_id: nil})
```
Comment (stuartc) [inline lib/lightning/accounts.ex:82]: Jobs don't have a `credential_id`. They have a credential via a `project_credential_id`. 

I'm a bit concerned the tests didn't pick this up. 

There could also be a cascade rule that makes this update unnecessary, i.e. the deletion of a project credential sets `project_credential_id` to `nil`.

**Review by stuartc — CHANGES_REQUESTED** [review]
Please address my comments, I'll take a closer look at the tests after that.

File: lib/lightning_web/live/components/user_deletion_modal.ex [hunk 5]
```diff
@@ -83,6 +95,15 @@ defmodule LightningWeb.Components.UserDeletionModal do
           id="scheduled_deletion_form"
         >
           <span>This user's account and credential data will be deleted</span>
+
+          <%= if has_activity_in_projects?(@user) do %>
```
[the remark this answers is not in the document]
Comment (elias-ba) [reply lib/lightning_web/live/components/user_deletion_modal.ex:99]: Handled

File: lib/lightning_web/live/components/user_deletion_modal.ex [hunk 6]
```diff
@@ -65,6 +69,14 @@ defmodule LightningWeb.Components.UserDeletionModal do
   defp logout_after_deletion(%{assigns: %{logout: false}} = socket),
     do: push_redirect(socket, to: socket.assigns.return_to)
 
+  defp has_activity_in_projects?(%User{} = user) do
+    project_credentials_count =
+      Credentials.count_project_credentials_for_user(user)
+
+    invocation_reasons_count = Invocation.count_invocation_reasons_for_user(user)
+    project_credentials_count != 0 or invocation_reasons_count != 0
+  end
```
[the remark this answers is not in the document]
Comment (elias-ba) [reply lib/lightning_web/live/components/user_deletion_modal.ex:78]: Moved

File: lib/lightning/accounts.ex (hunk 3 above)
Comment (elias-ba) [reply lib/lightning/accounts.ex]: Done

File: lib/lightning/accounts.ex (hunk 2 above)
Comment (elias-ba) [reply lib/lightning/accounts.ex]: Done

File: lib/lightning/accounts.ex (hunk 4 above)
Comment (elias-ba) [reply lib/lightning/accounts.ex]: I confirm there's a nillify rule. Thanks

**Comment by elias-ba** [comment]
> Please address my comments, I'll take a closer look at the tests after that.

Hey @stuartc I have addressed all your change requests. Please continue your review and let me know if there's anything other stuff to handle. Thanks in advance

File: CHANGELOG.md [hunk 7]
```diff
@@ -25,6 +25,8 @@ and this project adheres to
   [#800](https://github.com/OpenFn/Lightning/issues/800)
 - Better errors when using magic functions: "no magic yet" and "check
   credential" [#812](https://github.com/OpenFn/Lightning/issues/812)
+- Finish implementation of "delete user"
+  [#747](https://github.com/OpenFn/Lightning/issues/747)
```
Comment (stuartc) [inline CHANGELOG.md:29]: @elias-ba please move this into the Unreleased section

File: lib/lightning/accounts.ex [hunk 8]
```diff
@@ -24,33 +27,15 @@ defmodule Lightning.Accounts do
...
     end)
 
-    # Remove credentials
+    # Remove user from projects
+    Ecto.assoc(%User{id: id}, :project_users) |> Repo.delete_all()
+
+    # Delete the credentials of the user.
+    # Note that there's a nilify constraint that set all project_credentials associated to this user to nil
     Credentials.list_credentials_for_user(id)
     |> Enum.each(&Credentials.delete_credential/1)
```
Comment (stuartc) [inline lib/lightning/accounts.ex:36]: Can this not be done with just a query?

File: lib/lightning/invocation.ex [hunk 9]
```diff
@@ -252,6 +253,14 @@ defmodule Lightning.Invocation do
...
   end
 
+  def count_invocation_reasons_for_user(%User{id: id}) do
+    from(invocation_reason in Lightning.InvocationReason,
+      where: invocation_reason.user_id == ^id,
+      select: count(invocation_reason.id)
+    )
+    |> Repo.one()
+  end
+
```
Comment (stuartc) [inline lib/lightning/invocation.ex:263]: This looks like it's only being used in tests, please move it there - we don't want to add interfaces that aren't used in the rest of the application.

File: lib/lightning/accounts.ex [hunk 10]
```diff
@@ -24,33 +27,15 @@ defmodule Lightning.Accounts do
...
-              "delete" => "true",
-              "user_id" => id,
-              "id" =>
-                Enum.find(p.project_users, fn pu -> pu.user_id == id end)
-                |> Map.get(:id)
-            }
-          }
-        }
-      )
-    end)
```
Comment (stuartc) [inline lib/lightning/accounts.ex:49]: Just double checking here, this isn't needed anymore because deleting the user deletes project_user records as well right?

File: test/lightning/accounts_test.exs [hunk 11]
```diff
@@ -282,36 +284,120 @@ defmodule Lightning.AccountsTest do
...
+    end
+
+    test "purging user deletes all project credentials that involve this user's credentials" do
+      user = user_fixture()
+
+      CredentialsFixtures.project_credential_fixture(user_id: user.id)
+      CredentialsFixtures.project_credential_fixture(user_id: user.id)
+      CredentialsFixtures.project_credential_fixture()
+
+      assert Credentials.count_project_credentials_for_user(user) == 2
```
Comment (stuartc) [inline test/lightning/accounts_test.exs:351]: Regarding the function that was added, I think this can be written as:

```
from(pc in Ecto.assoc(user, [:credentials, :project_credentials]))
|> Repo.aggregate(:count, :id)
```

Comment (stuartc) [reply test/lightning/accounts_test.exs:351]: You can put that in a function inside the test module for reuse.

**Review by stuartc — CHANGES_REQUESTED** [review]

**Comment by amberrignell** [comment]
@elias-ba see screenshot below for bug: when a user is scheduled for deletion, they still show up in the project members list but without a name. When showing project members, we should only see active users (users that haven't been disabled). 

Screenshot 2023-05-10 at 14 59 55

**Comment by amberrignell** [comment]
When a user clicks delete, two options should appear: cancel deletion and delete now. 
image

File: lib/lightning/accounts.ex (hunk 8 above)
Comment (elias-ba) [reply lib/lightning/accounts.ex:36]: Audit is involved when deleting a credential. See

```
  def delete_credential(%Credential{} = credential) do
    Multi.new()
    |> Multi.delete(:credential, credential)
    |> Multi.insert(:audit, fn _ ->
      Audit.event("deleted", credential.id, credential.user_id)
    end)
    |> Repo.transaction()
  end
```

I am wondering if this is not a good enough reason ?

File: test/lightning/accounts_test.exs (hunk 11 above)
Comment (elias-ba) [reply test/lightning/accounts_test.exs]: Done. Thanks

File: lib/lightning/invocation.ex (hunk 9 above)
Comment (elias-ba) [reply lib/lightning/invocation.ex]: Done. Thanks.

**Comment by elias-ba** [comment]
> @elias-ba see screenshot below for bug: when a user is scheduled for deletion, they still show up in the project members list but without a name.
> 
> Expected: all project_users names should appear in the list (even if they are scheduled for deletion). When they are deleted, they should no longer be in the list.
> 
> --> the reason we are not removing them from project_users when they are scheduled for deletion is so that if the deletion is cancelled, the user can still access these projects.
> 
> Screenshot 2023-05-10 at 14 59 55

This is now solved.

**Comment by elias-ba** [comment]
> When a user clicks delete, two options should appear: cancel deletion and delete now. image

This is now implemented.

File: lib/lightning/accounts.ex (hunk 8 above)
Comment (stuartc) [reply lib/lightning/accounts.ex:42]: Nah that makes sense, it's pretty unlikely that a user will have hundreds or thousands of credentials.

**Review by stuartc — APPROVED** [review]
Nice one dude, I made a small change to the `with` statement in `user_deletion_modal.ex` which makes it a bit clearer imo.
