### PR TITLE
Can't retry workorders that failed without a run

### LINKED ISSUE #1417: Can't retry workorders that failed without a run
FunctionClauseError: no function clause matching in Lightning.WorkOrders.retry_many/2

Sentry Issue: [LIGHTNING-7Q](https://openfn.sentry.io/issues/4639503297/?referrer=github_integration)

```
FunctionClauseError: no function clause matching in Lightning.WorkOrders.retry_many/2
  File "lib/lightning/work_orders.ex", line 303, in Lightning.WorkOrders.retry_many/2
  File "lib/lightning_web/live/run_live/index.ex", line 287, in LightningWeb.RunLive.Index.handle_event/3
  File "lib/phoenix_live_view/channel.ex", line 487, in anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
  File "/app/deps/telemetry/src/telemetry.erl", line 321, in :telemetry.span/3
  File "lib/phoenix_live_view/channel.ex", line 246, in Phoenix.LiveView.Channel.handle_info/2
...
(3 additional frame(s) were not displayed)

(FunctionClauseError no function clause matching in Lightning.WorkOrders.retry_many/2)
```

### PR DESCRIPTION
**Pull request by midigofrank**
## Related issue

Fixes #1417 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning/work_orders.ex [hunk 1]
```diff
@@ -296,33 +350,30 @@ defmodule Lightning.WorkOrders do
...
         select: %{
-          id: ar.id,
+          id: att.id,
           row_num:
             row_number()
             |> over(
               partition_by: att.work_order_id,
-              order_by: coalesce(r.started_at, r.inserted_at)
+              order_by: coalesce(att.started_at, att.inserted_at)
             )
```
Comment (stuartc) [inline lib/lightning/work_orders.ex:363]: Do we still need to partition/create row numbers?

Actually I'm not sure I understand why we need to find any attempts - if we're only given a workorder; can we not create a new attempt based on the workorder?

File: lib/lightning/work_orders.ex [hunk 2]
```diff
@@ -228,15 +228,74 @@ defmodule Lightning.WorkOrders do
...
+  @spec retry(
+          Attempt.t() | Ecto.UUID.t(),
+          [
+            work_order_option(),
+            ...
+          ]
+          | []
+        ) ::
+          {:ok, Attempt.t()} | {:error, Ecto.Changeset.t(Attempt.t())}
+
```
Comment (stuartc) [inline lib/lightning/work_orders.ex:253]: Don't we have the `retry/2` spec further up? Two other things I'm curious about:

1. What happened to the default (`\\ [] `)? 
2. Why the `...`, should any extra options be typed either by union or added to the `work_order_option` type?

**Review by stuartc — COMMENTED** [review]
@midigofrank good work, I left some comments; it seems we may have some opportunity to simplify this since things have changed/are a little simpler than they were.
