### PR TITLE
Fix Duplicated Credential Types

### LINKED ISSUE #2100: Generic Oauth clients can appear multiple times in the credential type selector
Here, there should only be one "Salesforce Sandbox" credential type. Occurs on `v2.5.0-pre`

There are two ways of recreating this bug:
1. Adding a new credential through the canvas
- Attempt to create a new credential from the workflow canvas by clicking "New Credential"
- Create a new credential from one of your Oauth clients
- Now try to add a new credential by clicking "new credential" 

2. This can also be recreated by switching selecting a new credential type in the list of available credentials on the form.

image

And sometimes it really goes wild 😎 

image

### PR DESCRIPTION
**Pull request by elias-ba**
## Related issue

Fixes #2100 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

File: lib/lightning_web/live/credential_live/credential_form_component.ex [hunk 1]
```diff
@@ -529,10 +538,7 @@ defmodule LightningWeb.CredentialLive.CredentialFormComponent do
                   </div>
                 </fieldset>
               </div>
-              <div
-                :if={@action == :edit and @allow_credential_transfer}
-                class="space-y-4"
-              >
+              <div :if={@action == :edit and true} class="space-y-4">
```
Comment (taylordowns2000) [inline lib/lightning_web/live/credential_live/credential_form_component.ex:541]: elias to change back to `@allow_credential_transfer`

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
one small change on allow/true

File: lib/lightning_web/live/credential_live/credential_form_component.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning_web/live/credential_live/credential_form_component.ex]: Thanks this is done.
