### PR TITLE
Ide logs and waiting messages

### LINKED ISSUE #4255: New logs appended below old logs on IDE-based runs
**Describe the bug**

When a new run is started from the IDE, the logs for that new run get appended to the previous run's logs. Instead, the old run logs should be cleared before we stream in new logs.

https://www.loom.com/share/9de4bfb83efa43e88763a1104a947709

**Version number** `v2.15.1`

I have reproduced this locally on main:

- [ ] Yes
- [x] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to the IDE
2. Start a run.
3. Start _another_ run.
4. See the logs for the second run get added to Monaco after the logs for the first run. (Instead of replacing them.)

### LINKED ISSUE #4257: The waiting for worker/installing adaptors screen got lost
When waiting for logs to appear on the IDE

### PR DESCRIPTION
**Pull request by taylordowns2000**
## Description

This PR fixes #4255 and fixes #4257 by clearing logs when a new run is provided, and by implementing a little typewriter animation with waiting messages.

## Validation steps

1. Run a run from the IDE
2. Retry it, and see the log lines are cleared first
3. Retry it, and notice the waiting message

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by doc-han** [comment]
Trying to review this PR, I'm asking myself why we mount a new react tree inside the existing one. This was a pattern used when elixir managed our several react mounts. Probably Claude picking that pattern into the collab editor.
https://github.com/OpenFn/lightning/blob/ebb4c9e41ad54e0c5bd5e95ace0d6e0e10b920a4/assets/js/collaborative-editor/components/run-viewer/LogTabPanel.tsx#L49-L52

File: assets/js/collaborative-editor/components/run-viewer/LogTabPanel.tsx [hunk 1]
```diff
@@ -19,12 +58,29 @@ export function LogTabPanel() {
...
+  const [initialText, setInitialText] = useState(''); // The typed-out initial message
+  const [cyclingText, setCyclingText] = useState('');
+  const animationRef = useRef<ReturnType<typeof setTimeout> | null>(null);
+  const currentMessageRef = useRef<string>('');
+  const initialTextRef = useRef<string>(''); // Mirror of initialText
+  const cyclingTextRef = useRef<string>(''); // Mirror of cyclingText
+  const animationPhaseRef = useRef<
+    'typing-initial' | 'typing' | 'paused' | 'deleting' | 'waiting'
+  >('typing-initial');
+  const runStateRef = useRef<string | undefined>(undefined);
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/run-viewer/LogTabPanel.tsx]: These useRefs scare me.

we use them as an escape hatch so we can update some state value without causing a re-render. Looking at `cyclingText` and `cyclingTextRef`. I see that whenever `cyclingText` is set using `setCyclingText` we also update the value in the ref at `cyclingTextRef`. which tells me one is redundant. Same with `initialTextRef`.
