### PR TITLE
Fix workflow canvas “reading x” crash

### LINKED ISSUE #3530: Cannot read properties of undefined (reading 'x') error on canvas
**Describe the bug** When a user creates a workflow then uses the AI assistant to modify the workflow, the workflow completely disappears and an error `cannot read properties of undefined (reading 'x')` appears

**Version number** v2.14.2

**To Reproduce** Steps to reproduce the behavior:
Here's a Loom on how to reproduce this: https://www.loom.com/share/0b63e3c140bf467693c337a6a572c940

**Expected behavior** A user should be able to modify their workflow using the AI assistant

**Screenshots** If applicable, add screenshots to help explain your problem.

Image

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR fixes a crash on the workflow canvas: **“Cannot read properties of undefined (reading 'x')”**. The error appeared when templates were switched quickly or when the viewport resized while some nodes didn’t yet have valid positions. The fix is minimal and localized:

* Added `util/safe-bounds.ts` with `hasXY`, `safeGetNodesBounds`, `safeFitBounds`, and `safeFitBoundsRect` to guard all bounds/fit calls.
* Filtered nodes passed to React Flow to only those with finite `x/y` (`rfNodes`) so `getNodesBounds` and `fitBounds` never see incomplete positions.
* Replaced direct `getNodesBounds`/`fitBounds` usage in `WorkflowDiagram` and `layout/animate` with the safe wrappers, and added small promise handlers where appropriate to avoid unhandled rejections.

Closes #3530

## Validation steps

1. Open **New Workflow** and select each base template; confirm the diagram renders and there are no errors.
2. Rapidly switch between different templates several times; the diagram should always update without blank states or errors.
3. Toggle the AI assistant drawer open and closed; the view should smoothly re-fit without errors.
4. Use the AI Assistant to generate multiple changes / workflows. Click around to render them. You shouldn't see any crash
5. Resize the browser window repeatedly; the canvas should maintain context and avoid any `x/y` errors.
6. Click around on the canvas and template list quickly; the app should remain stable.
7. Click **Fit view** and **Run auto layout**; both should complete without errors.

## Additional notes for the reviewer

There is a separate, pre-existing UX quirk where switching templates extremely quickly can momentarily race the debounced “generate workflow code” hook, causing a brief stale render. That behavior is out of scope for this fix and unaffected by these changes; the crash is resolved.

## AI Usage

Please disclose how you've used AI in this work:

* [ ] Code generation (copilot but not intellisense)
* [x] Learning or fact checking
* [ ] Strategy / design
* [ ] Optimisation / refactoring
* [ ] Translation / spellchecking / doc gen
* [ ] Other
* [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

* [x] I have performed a **self-review** of my code.
* [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
* [ ] I have updated the **changelog**.
* [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/workflow-diagram/util/safe-bounds.ts
Comment (doc-han) [inline assets/js/workflow-diagram/util/safe-bounds.ts:1]: I pledge to do a refactor in WorkflowDiagram which will look at all this once again.

File: assets/js/workflow-diagram/WorkflowDiagram.tsx [hunk 1]
```diff
@@ -240,11 +245,21 @@ export default function WorkflowDiagram(props: WorkflowDiagramProps) {
...
+        const viewBounds = {
+          width: workflowDiagramRef.current?.clientWidth ?? 0,
+          height: workflowDiagramRef.current?.clientHeight ?? 0,
+        };
+        layout(newModel, setModel, flow, viewBounds, {
+          duration: props.layoutDuration ?? LAYOUT_DURATION,
+          forceFit: props.forceFit,
+        }).then(positions => {
+          chartCache.current.positions = positions;
+        });
```
Comment (doc-han) [inline assets/js/workflow-diagram/WorkflowDiagram.tsx:262]: This part resolved the issue but then the question is that, do we know at what point in time we're triggering this layout animation?
Do we have control?

**Review by theroinaochieng — APPROVED** [review]
