### PR TITLE
Disable AI assistant submit button incase the job isn't saved yet

### LINKED ISSUE #2479: AI Assitant crashes on a job that is not saved yet
After creating a new job on the workflow and before saving it, the AI Assistant crashes when the user tries to send an AI query.

**Version number** 
v2.9.0

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

scenario A)

Create a new project
Create a new workflow but don't save it
Click on the job and on AI Assistant tab
It blinks and shows logs an exception when sending an AI question/query
scenario B)

On an existing workflow
Create a job but don't save it
Click on the job and on AI Assistant tab
It blinks and shows logs an exception when sending an AI question/query

**Expected behavior**

Depends on the requirement. A suggestion is to disable the AI Assistant tab when the job is not yet saved.

### PR DESCRIPTION
**Pull request by midigofrank**
### Description

This PR disables AI assistant submit button incase the job isn't saved yet

Closes #2479 

### Validation steps
You need to have `OPENAI_API_KEY` and `APOLLO_ENDPOINT` envs in order to validate this

1. Open up an existing workflow and add a new job. Alternatively, you can create a new workflow and open up the inspector
2. In the AI assistant tab, you'll see that the button to send the message is disabled. When you hover the button you'll get a tooltip saying `Save the job first in order to use the AI Assistant`

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.

### CODE REVIEW

**Comment by josephjclark** [comment]
Just need to flag that this may conflict with #2478

File: test/support/workflow_live_helpers.ex [hunk 1]
```diff
@@ -201,10 +201,10 @@ defmodule Lightning.WorkflowLive.Helpers do
     |> render_hook("push-change", %{patches: patches})
   end
 
-  def add_job_patch(name \\ "") do
+  def add_job_patch(name \\ "", id \\ Ecto.UUID.generate()) do
```
Comment (stuartc) [inline test/support/workflow_live_helpers.ex:204]: TIL that putting a function call inside a default _doesn't_ evaluate it on compilation. 

I totally expect that function to be called and all default values would be the same.

**Review by stuartc — APPROVED** [review]
