### PR TITLE
Collab Editor: Show server validation errors

### LINKED ISSUE #3781: Y.js Sync Race Condition: yjsJob.toJSON is not a function
## Issue Description

When transitioning from the old workflow editor to the collaborative editor after making changes (specifically adding edges), the collaborative editor fails to load with the error:

```
Uncaught TypeError: yjsJob.toJSON is not a function
    at createWorkflowStore.ts:305
```

This error prevents the workflow from loading and causes the React component to crash.

## Reproduction Steps

**Reliable reproduction:**
1. Open an existing workflow in the old workflow editor (non-collaborative)
2. Add a new edge connecting two jobs
3. Save the workflow
4. Navigate to the collaborative editor for the same workflow
5. **Result**: Error occurs and workflow diagram appears empty

### The Error Location

The error occurs in `createWorkflowStore.ts` in the `jobsObserver` function:

```typescript
const jobsObserver = () => {
  updateState(draft => {
    const yjsJobs = jobsArray.toArray() as Y.Map<unknown>[];
    draft.jobs = yjsJobs.map(yjsJob => yjsJob.toJSON() as Workflow.Job);
    //                                 ^^^^^^^^ Fails here
  }, "jobs/observerUpdate");
};
```

### The Initialization Flow

1. **Backend (Elixir)**: `WorkflowChannel` joins → `Collaborate.start()` → `DocumentSupervisor` starts
2. **Backend**: `Persistence.bind()` loads workflow from DB via `Session.initialize_workflow_document()`
3. **Backend**: `WorkflowSerializer.serialize_to_ydoc()` converts Elixir workflow struct to Y.Doc format using `Yex.MapPrelim.from()`
4. **Backend**: Y.Doc syncs to client via WebSocket
5. **Frontend**: Phoenix Channel receives binary Y.js sync messages
6. **Frontend**: `StoreProvider` detects `session.isConnected = true` and calls `workflowStore.connect()`
7. **Frontend**: `workflowStore.connect()` attaches observers and **immediately calls them** (lines 355-359)
8. **Error**: Observers try to call `.toJSON()` on items that aren't fully deserialized Y.Maps yet

### Current Behavior in createWorkflowStore.ts

```typescript
// After attaching observers (line ~340)
// Initial sync from Y.Doc to state
workflowObserver();
jobsObserver();      // ← Crashes here
triggersObserver();
edgesObserver();
positionsObserver();
```

The code manually invokes all observers immediately after connecting, assuming the Y.Doc is ready.

### Console Logs Show

```
StoreProvider.tsx:168  Debug  Connecting workflowStore
createWorkflowStore.ts:341  Debug  Attaching observers
createWorkflowStore.ts:222  Debug  notify {jobs: 0, triggers: 0, edges: 0}
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                          Arrays are EMPTY!
```

Even though the Y.Arrays have `length > 0`, the items inside aren't Y.Map instances yet - they're still being deserialized by Y.js.

### Theory 1: Timing - Manual Observer Calls Too Early

The manual observer calls (lines 355-359) run before Y.js has finished deserializing the sync data:

- Y.js receives binary data via `yjs_sync` message
- Creates Y.Array slots with the correct length
- Begins deserializing items into Y.Map instances (asynchronous)
- **Our code runs here** ← Too early!
- Y.js finishes deserialization (after our code already crashed)

**Evidence**:
- The error only happens when transitioning from old editor (data needs migration)
- Y.Arrays have length but items aren't Y.Maps
- Y.js is fundamentally asynchronous

### Theory 2: Y.Doc State Flags Not Reliable

The current check in `StoreProvider.tsx`:

```typescript
if (session.ydoc && session.provider && session.isConnected) {
  stores.workflowStore.connect(...)
}
```

Only checks if the Phoenix Channel is connected (`isConnected`), not if Y.Doc has:
- Received sync data (`isSynced`)
- Processed/deserialized the data
- Populated Y.Arrays with actual Y.Map instances

**Evidence**:
- `session.isSynced` flag exists but isn't checked
- Even `isSynced=true` might not guarantee data is fully deserialized

### Theory 3: Architectural Mismatch

Y.js observers are designed to fire **reactively** in response to Y.Doc changes, not be called manually. The manual observer calls might be fighting against Y.js's intended architecture.

**From Y.js documentation:**
> Observers are triggered automatically when the document changes

Our code calls them manually during initialization, which may bypass Y.js's readiness guarantees.

### Option 1: Remove Manual Observer Calls (Simplest)

**Idea**: Trust Y.js to fire observers automatically when data is ready.

**Rationale**:
- Y.js will automatically fire observers when deserialization completes
- This is the intended Y.js architecture
- Removes the race condition entirely

**Risk**:
- Need to verify that observers DO fire for initial data (not just changes)
- UI might show empty state briefly before observers fire

### Option 2: Add Y.Doc Readiness Check

**Idea**: Verify Y.Doc actually has valid Y.Map data before running observers.

**Rationale**:
- Defensive programming
- Handles both timing and data readiness
- Falls back to automatic observer firing if data isn't ready

**Risk**:
- More complex logic
- Might still race if Y.js hasn't even started deserialization

### Option 3: Wait for session.isSynced AND Data Ready

**Idea**: Combine multiple checks in `StoreProvider.tsx`.

**Rationale**:
- `isSynced` means Y.Doc has received sync messages
- Might give Y.js more time to deserialize

**Risk**:
- `isSynced` might not guarantee deserialization is complete
- Still might need Option 1 or 2 as well

### Option 4: Add Defensive Filters in Observers

**Idea**: Make observers handle partially-synced data gracefully.

**Rationale**:
- Handles partial sync gracefully
- Observers won't crash on non-Y.Map items

**Risk**:
- Silently drops data if items aren't ready
- Might hide real bugs where Y.Arrays contain wrong data
- Workaround rather than fixing root cause

## Questions for Further Investigation

1. **Do Y.js observers fire for initial data, or only changes?**
   - If only changes, we NEED manual initial observer calls
   - If initial data too, we should remove manual calls

2. **What exactly does `session.isSynced` guarantee?**
   - Is it just "message received" or "data deserialized"?
   - Can we rely on it?

3. **Is this specific to edges, or all data types?**
   - The issue was noticed after adding edges
   - Jobs and triggers might have different serialization timing

4. **Why doesn't this happen when creating new workflows?**
   - New workflows have no persisted state
   - Might be a difference in timing between loading from DB vs. creating fresh

5. **Are there Y.js lifecycle events we should be listening to?**
   - Does Y.js emit events when sync/deserialization is complete?
   - Could we wait for those instead of guessing readiness?

## Additional Context

- This issue was discovered while implementing EdgeInspector migration to TanStack Form (PR #3770)
- The same error also occurs with `job.get is not a function` in other parts of the store
- Related to Y.js CRDT deserialization timing, not a bug in our data structures
- Only affects transition from old editor → new editor, not new workflows

## Next Steps

We need to:
1. Test whether Y.js observers fire for initial data or only changes
2. Understand the exact guarantees of `session.isSynced`
3. Determine if removing manual observer calls breaks anything
4. Consider a combination of solutions for robustness

The cleanest solution would be Option 1 (remove manual calls) if Y.js observers fire for initial data. Otherwise, Option 2 or 3 might be necessary.

---

**Related Files:**
- `assets/js/collaborative-editor/stores/createWorkflowStore.ts` (lines 355-359)
- `assets/js/collaborative-editor/contexts/StoreProvider.tsx` (lines 162-179)
- `lib/lightning/collaboration/workflow_serializer.ex` (lines 140-157)
- `lib/lightning/collaboration/persistence.ex` (line 50)

### LINKED ISSUE #3783: Server-Side Validation Errors in Collaborative Editor (Y.Doc Integration)
## Problem

When a user tries to save a workflow with validation errors (like duplicate workflow name, blank job name, etc.), only that user sees the error via a toast notification. Other collaborators are unaware of the validation state, and errors don't persist across page refresh or reconnection.

This creates confusion in collaborative editing scenarios where:
- User A attempts to save with invalid data
- User B doesn't see the validation errors
- User B wonders why the workflow isn't saving
- Errors disappear on page refresh, requiring users to re-trigger validation

## Proposed Solution

Implement server-side validation error handling where validation errors are written directly to Y.Doc by the server and displayed inline in form fields for all collaborators.

### User Experience

When any user triggers a save that fails validation:
1. Validation errors appear inline below the relevant form fields
2. All connected users see the same errors in real-time
3. Errors persist across page refresh until resolved
4. Errors clear automatically when validation passes on successful save

### Technical Approach

Leverage the existing Y.Doc infrastructure used throughout the collaborative editor:

1. **Extend Y.Doc schema** to include an `errors` map at the top level
2. **Server writes errors** to Y.Doc when validation fails (similar to how `lock_version` is updated)
3. **Client observes errors** using the same deep observer pattern as jobs/triggers/edges
4. **Form fields display errors** by injecting Y.Doc errors into TanStack Form field meta
5. **Server clears errors** on successful save

## Error Format

Errors should use flat dot-notation keys for easy lookup:

```typescript
{
  "errors": {
    "name": "a workflow with this name already exists in this project.",
    "jobs.abc-123.name": "job name has already been taken",
    "concurrency": "must be greater than or equal to 1"
  }
}
```

### Key Format:
- Workflow fields: `"name"`, `"concurrency"`
- Job fields: `"jobs.{job-id}.name"`, `"jobs.{job-id}.body"`
- Trigger fields: `"triggers.{trigger-id}.cron_expression"`
- Edge fields: `"edges.{edge-id}.condition_expression"`

### Phase 1: Extend Y.Doc Schema
- Add `errors` map to Y.Doc TypeScript type definitions
- Add `errors` field to Workflow.State interface
- Update WorkflowSerializer to initialize empty errors map
- Add error clearing in session reset logic

### Phase 2: Server-Side Error Writing
- Modify `save_workflow` to write validation errors to Y.Doc on failure
- Create helper functions to format Ecto changeset errors for Y.Doc
- Modify `merge_saved_workflow_into_ydoc` to clear errors on success
- Add unit tests for error writing/clearing

### Phase 3: Client-Side Error Observation
- Add Y.Doc errors observer to WorkflowStore
- Create error management commands: `setError`, `clearError`, `clearAllErrors`
- Export errors getter for component access
- Add unit tests for errors observer

### Phase 4: Form Field Error Integration
- Create `useServerValidation` hook to inject Y.Doc errors into TanStack Form
- Integrate hook into WorkflowSettings (when form-based version is merged)
- Integrate hook into JobInspector with prefix filtering
- Add hook unit tests

### Phase 5: Testing
- Add integration tests for Phoenix Channel error handling
- Add React component tests for error display
- Optional: Add E2E tests for multi-user scenarios

### Functional Requirements
- [ ] Server writes validation errors to Y.Doc when save fails
- [ ] All connected users see validation errors in real-time
- [ ] Errors display inline below form fields using existing ErrorMessage component
- [ ] Errors clear automatically when validation passes
- [ ] Nested entity errors (jobs, triggers, edges) display correctly

### Manual Testing
- [ ] User A saves workflow with duplicate name → error appears for all users
- [ ] User B changes workflow name and saves → error clears for all users
- [ ] Page refresh preserves validation errors until resolved
- [ ] Nested errors (e.g., job name duplicate) display in JobInspector
- [ ] Multiple validation errors display simultaneously
- [ ] No console errors or warnings in browser DevTools

### Backend (Elixir)
- `lib/lightning/collaboration/workflow_serializer.ex`
- `lib/lightning/collaboration/session.ex`
- `test/lightning/collaboration/session_test.exs`
- `test/lightning_web/channels/workflow_channel_test.exs`

### Frontend (TypeScript/React)
- `assets/js/collaborative-editor/types/session.ts`
- `assets/js/collaborative-editor/types/workflow.ts`
- `assets/js/collaborative-editor/stores/createWorkflowStore.ts`
- `assets/js/collaborative-editor/hooks/useServerValidation.ts` (new file)
- `assets/js/collaborative-editor/components/inspector/JobInspector.tsx`
- `assets/js/collaborative-editor/components/inspector/WorkflowSettings.tsx`

## What We're NOT Doing

- Real-time pre-save validation (validation only occurs on save attempt)
- Changing Phoenix Channel error responses (backward compatibility)
- Adding optimistic client-side name checking
- Persisting errors to database (errors only live in Y.Doc during session)
- Implementing error snackbar/banner (errors only display inline)
- Handling network disconnection edge cases

## Performance Considerations

- Error map overhead: ~50-200 bytes per error (negligible)
- Network bandwidth: Errors sync via Y.js binary protocol (efficient)
- Memory impact: Minimal - errors are simple key-value pairs
- Estimated total latency (error trigger to display): <200ms

## References

- Y.Doc architecture: `.claude/guidelines/store-structure.md`
- Form validation: TanStack Form documentation
- Observer pattern: Existing implementation in `createWorkflowStore.ts`

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

Show server validation errors in the collab editor forms

  ### Problem
  Previously, validation errors only appeared as toast notifications to the user who triggered the save. Other collaborators had no visibility into validation failures, and
  errors didn't persist across page refreshes.

  ### Solution
  Leverages Lightning's existing Y.Doc infrastructure to sync validation errors:

  1. **Server writes errors to Y.Doc** when validation fails
  2. **Clients observe errors** via WorkflowStore deep observers
  3. **Forms automatically display errors** through enhanced `useAppForm` hook
  4. **Errors clear on successful save** automatically

  ### Key Frontend Changes

  #### Enhanced `useAppForm` Hook
  Now automatically injects server validation errors from Y.Doc into form fields:

  ```typescript
  // Workflow-level form
  const form = useAppForm({ defaultValues: { name: "" } });

  // Entity-specific form (jobs, triggers, edges)
  const form = useAppForm({ defaultValues: { name: "" } }, jobs.${jobId});
```
  - Accepts optional `errorPath` parameter for nested entities
  - Converts paths to JSONPath expressions for error lookup
  - Uses new `useServerValidation` hook to sync Y.Doc errors to form fields

  #### `useServerValidation` Hook
  Core hook bridging Y.Doc errors with TanStack Form:
  - Subscribes to WorkflowStore's `errors` map
  - Uses JSONPath to navigate nested error structures
  - Injects errors into form field meta as `onServer` validation errors
  - Automatically clears stale errors

  #### WorkflowStore Error Management
  - Added `errors` map to Y.Doc schema with deep observer
  - New actions: `setError()`, `clearError()`, `clearAllErrors()`
  - Follows existing Pattern 1 (Y.Doc → Observer → Immer → Notify)

  #### Visual Indicators
  - New `extractNodeErrors()` utility extracts nested entity errors
  - WorkflowDiagram attaches errors to jobs/triggers/edges for visual display

  ### Key Backend Changes

  **Session error handling** (`lib/lightning/collaboration/session.ex`):
  - Writes validation errors to Y.Doc when save fails
  - Clears errors map on successful save
  - Formats Ecto changeset errors into nested structure with entity IDs as keys

  ### Error Structure

  ```typescript
  {
    name: ["can't be blank"],           // workflow-level
    jobs: {
      "job-uuid": { name: ["too long"] } // nested entities
    }
  }
```
Closes #3783
Closes #3781

## Validation steps

1. Try changing the workflow name to an existing one and click save. An error should appear below the field
2. Do the same for job names

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [ ] Strategy / design
- [x] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/hooks/useServerValidation.ts [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+    });
+
+    // Inject new server errors into form fields
+    Object.entries(relevantErrors).forEach(([fieldName, errorMessages]) => {
+      // Check if this field exists in the form
+      if (fieldName in form.state.values) {
+        // Take the first error message from the array (if it exists)
+        const errorMessage =
+          Array.isArray(errorMessages) && errorMessages.length > 0
+            ? errorMessages[0]
```
Comment (elias-ba) [inline assets/js/collaborative-editor/hooks/useServerValidation.ts]: Is there a future plan to show multiple error messages per field? 🤔

**Review by elias-ba — APPROVED** [review]
Hey @midigofrank great work. I added a commit after running `bin/fomat` and also tiny improvements in some comments. 👏🏽

File: assets/js/collaborative-editor/hooks/useServerValidation.ts (hunk 1 above)
Comment (midigofrank) [reply assets/js/collaborative-editor/hooks/useServerValidation.ts]: Hey @elias-ba , nope there is no plan. That's just how changeset errors are returned. A field can have multiple error messages depending on the validations

Comment (elias-ba) [reply assets/js/collaborative-editor/hooks/useServerValidation.ts]: Yeah @midigofrank I know that. I was wondering what happens when we have two errors for the same field ? For example password should have special chars and password should be more than 8 chars. Just curious !

**Comment by stuartc** [comment]
@midigofrank just fyi, I've been smashing away on this yesterday and today. What you left is very good, but we now need to take it further - I'm working on getting the errors to merge and sync AND have tanstack receive them when it mounts; it's much harder than it sounds especially when there is more than one editor. So yeah this isn't ready to merge, no fault of yours mind you!

I've pushed what I have so far, it's a bit of a mess right now. But yeah we can chat on Monday. No need to dig into it.

**Review by stuartc — APPROVED** [review]
