### PR TITLE
Restore intellisense to the Collaborative Editor

### LINKED ISSUE #4386: code assist support got dropped somewhere
Details to follow

- Code assist 100% used to work based on adaptor typescript (I've just confirmed against an old branch)
- Both legacy editor and collab editor seem to be broken
- At first glance I can't see any support for it in collab editor at all

### PR DESCRIPTION
**Pull request by josephjclark**
## Description

This PR fixes intellisense and code complete in the collaborative editor (it fixes the legacy editor too)

I've basically asked Claude to copy across the legacy solution and do a little refactoring.

Closes #4386 

Note that magic metadata appears to not work. I'll look at that separately.

## Validation steps

- Open a step with the common adaptor
- Over over any operation. You should get a pop-up with docs about that function. try `fn()`!
- Go to a new line. Hit ctrl+space
- You should be presented with a list of valid operations for that adaptor

Also note that the only things in the pick list should be adaptor  functions - no basic JS clutter

## AI Usage

Please disclose whether you've used AI anywhere in this PR (it's cool, we just
want to know!):

- [x] I have used Claude Code
- [ ] I have used another model
- [ ] I have not used AI

You can read more details in our
[Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

File: assets/js/collaborative-editor/components/CollaborativeMonaco.tsx [hunk 1]
```diff
@@ -82,6 +95,24 @@ export const CollaborativeMonaco = forwardRef<
         insertSpaces: true,
         automaticLayout: true,
         fixedOverflowWidgets: true,
+        dragAndDrop: false,
```
Comment (josephjclark) [inline assets/js/collaborative-editor/components/CollaborativeMonaco.tsx]: TODO double check these options

File: assets/js/collaborative-editor/components/CollaborativeMonaco.tsx [hunk 2]
```diff
@@ -354,6 +455,10 @@ export const CollaborativeMonaco = forwardRef<
 
   return (
     <div className={cn('relative', className || 'h-full w-full')}>
+      {/* Loading indicator */}
```
Comment (josephjclark) [inline assets/js/collaborative-editor/components/CollaborativeMonaco.tsx]: TODO remove this stupid comment

File: assets/js/editor/Editor.tsx [hunk 3]
```diff
@@ -96,6 +96,7 @@ type Lib = {
 };
 
 async function loadDTS(specifier: string): Promise<Lib[]> {
+  console.log('> loadDTS', specifier);
```
Comment (josephjclark) [inline assets/js/editor/Editor.tsx]: TODO revert difs here

**Review by doc-han — CHANGES_REQUESTED** [review]
MIGAAA!

It works but only after I've switched the adaptor. 
eg. 
1. I select a salesforce adaptor from the canvas, then I visit the job code
2. The intellisense doesn't seem to work
3. Now I switch adaptor from salesforce to http. I see intellisense working.

could it be that it's downloading?

**Comment by josephjclark** [comment]
@doc-han I think the problem is `@latest`. If the adaptor version is set to `@latest` then types will fail to load. If a specific version is set then it's OK.

I'll take a little look but I suspect that's an older bug - a smear in the old greatness

**Comment by josephjclark** [comment]
@doc-han I've raised out https://github.com/OpenFn/kit/issues/1245 - this is a long standing bug in kit. I may raise a fix separately, I think it's cheap

**Comment by josephjclark** [comment]
@doc-han the severity of this shouldn't be too high: for new steps, when you pick an adaptor, it'll select the actual latest version, not `@latest`. So unless a) you have an old step which is saved to `@latest`, or b you specically choose `@latest`, it'll work just fine.

**Comment by elias-ba** [comment]
Fixed the failing JS tests with two changes:

1. The Monaco mock was missing the `languages.typescript` API that CollaborativeMonaco now uses for intellisense. Updated both the global mock and the local one in the diff test.
2. Also added a mock for `loadDTS` it was making network calls during tests that failed silently, causing vitest to exit with code 1 even though all tests passed.

**Comment by josephjclark** [comment]
Thank you @elias-ba !!!

**Comment by josephjclark** [comment]
@doc-han @theroinaochieng would love to get this into the demo release tomorrow

**Review by doc-han — APPROVED** [review]

File: assets/js/collaborative-editor/components/CollaborativeMonaco.tsx [hunk 4]
```diff
@@ -99,6 +124,27 @@ export const CollaborativeMonaco = forwardRef<
...
+        document.body.appendChild(overflowNode);
+        overflowNodeRef.current = overflowNode;
+
+        // Update editor options with overflow container
+        // @ts-ignore - overflowWidgetsDomNode exists but isn't in updateOptions type
+        editor.updateOptions({
+          overflowWidgetsDomNode: overflowNode,
+          fixedOverflowWidgets: true,
+        });
+      }
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/CollaborativeMonaco.tsx]: Doesn't monaco have a default `fixedOverflowWidgets` which is good enough? that's what monaco uses to keep all our tooltip high in z-index. I"m wondering why we had to create a new node to be appended to body.

**Comment by doc-han** [comment]
@josephjclark change log not added.

File: assets/js/collaborative-editor/components/CollaborativeMonaco.tsx (hunk 4 above)
Comment (josephjclark) [reply assets/js/collaborative-editor/components/CollaborativeMonaco.tsx]: Great catch!

This is old legacy editor code, introduced when we had problems with the z index. Feels fine without it in the collab editor. I'll cut it out

**Comment by josephjclark** [comment]
@theroinaochieng I'd like to merge this to main and release it alongside single-session AI stuff. It's got some important  fixes for demos IMO. It does increase the risk and QA effort of the release though
