### PR TITLE
Workflow Templates: Bug Fixes, Tests, Clean up 🐛 🧹 🧪 

### LINKED ISSUE #3156: Importer not updating canvas properly
The workflow.yaml importer in #3015 isn't updating the canvas ([video of bug here](https://www.loom.com/share/1ce332f633de423d8aeade16edcab45e)) on the template browser.

When the workflow is used and saved, a hard refresh will display it on the canvas, but somehow it's not updating on the fly as it was before. ([Here, at 5:50 is a video](https://www.loom.com/share/313d2549ced14070afcacc43f1793a5f?t=350) of how it was working before. Maybe related to the changes that was required to fix the canvas zooming?)

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR cleans up the implementation of workflow templates, adds more tests, and fixes few bugs caught during QA testing.

Fixes #3156 #3157 #3142

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning_web/components/new_inputs.ex [hunk 1]
```diff
@@ -367,6 +372,69 @@ defmodule LightningWeb.Components.NewInputs do
...
+            "phx-no-feedback:border-slate-300 phx-no-feedback:focus:border-slate-400 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500",
+            @errors == [] &&
+              "border-slate-300 focus:border-slate-400 focus:outline-indigo-600",
+            @errors != [] &&
+              "border-danger-400 focus:border-danger-400 focus:outline-danger-400",
+            @class
+          ]}
+          {@rest}
+        />
+        <input type="hidden" name={@name} id={@id} value={serialize_tags(@tags)} />
```
Comment (midigofrank) [inline lib/lightning_web/components/new_inputs.ex:403]: 🤔 same `name` and `id` ? How is it still sending in an array then? 
Also, I'm getting this error when I open the publish workflow template
Screenshot 2025-04-28 at 10 05 23

File: test/lightning_web/live/workflow_live/edit_test.exs
Comment (midigofrank) [inline test/lightning_web/live/workflow_live/edit_test.exs:1]: What happened to using template description as the workflow name? This assertion in the test was based on that, we should change the flow in this test if that's no longer the case: https://github.com/OpenFn/lightning/pull/3158/files#diff-0154dd02431d46e202854c77ec847e07b719c34ce039e47ccc59253916f4fec9R192

**Review by midigofrank — CHANGES_REQUESTED** [review]
Great job @elias-ba. I've left 2 comments. 
There is a lot of ceremony around the `TagInput`, is it possible to have either the client or server just do `one of the many` actions? Like for instance, have the front end handle everything and just send `comma separated tags` or just an `array`?

File: test/lightning_web/live/workflow_live/edit_test.exs
Comment (midigofrank) [reply test/lightning_web/live/workflow_live/edit_test.exs:1]: I meant using the search term, not template description

**Review by taylordowns2000 — APPROVED** [review]
Approved from UX side. Happy for a merge after @midigofrank and @elias-ba discuss Frank's change request

File: test/lightning_web/live/workflow_live/edit_test.exs
Comment (elias-ba) [reply test/lightning_web/live/workflow_live/edit_test.exs:1]: @midigofrank the link / diff you shared there opens up my files changes in this PR. Can you check if it's the right diff you wanted to share ?

Comment (elias-ba) [reply test/lightning_web/live/workflow_live/edit_test.exs:1]: Thx for the quick call @midigofrank. To sum up on this one:

This guy would already pick a template and click next (EditTest L190)

```
view |> element("button#toggle_new_workflow_panel_btn") |> render_click()
```

And this guy would apply the name to the workflow (EditTest L193-L197)

```
workflow_name = "My Workflow"
view
|> form("#workflow-form")
|> render_change(workflow: %{name: workflow_name})
```

File: lib/lightning_web/components/new_inputs.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning_web/components/new_inputs.ex]: This is now fixed @midigofrank !

File: lib/lightning_web/components/new_inputs.ex [hunk 2]
```diff
@@ -367,6 +384,82 @@ defmodule LightningWeb.Components.NewInputs do
...
+          class="inline-flex items-center rounded-md bg-blue-50 p-2 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10 mr-1 my-1"
+          data-tag={tag}
+        >
+          {tag}
+          <button
+            type="button"
+            class="group relative -mr-1 h-3.5 w-3.5 rounded-sm hover:bg-gray-500/20"
+          >
+            <span class="sr-only">Remove</span>
+            <Heroicons.x_mark class="h-3 w-3 stroke-gray-600/50 group-hover:stroke-gray-600/75" />
```
Comment (midigofrank) [inline lib/lightning_web/components/new_inputs.ex:455]:
```suggestion
            <.icon name="hero-x-mark" class="h-3 w-3 stroke-gray-600/50 group-hover:stroke-gray-600/75" />
```
fyi, we moved away from rendering icons from the lib directly because it renders the whole svg

File: assets/js/hooks/index.ts [hunk 3]
```diff
@@ -384,23 +384,118 @@ export const OpenAuthorizeUrl = {
...
-export const EditScope = {
+export const TagInput = {
   mounted() {
-    this.el.addEventListener('dblclick', _e => {
-      const scopeValue = this.el.dataset.scope;
-      const eventType = this.el.dataset.eventType;
-      this.pushEventTo(this.el, eventType, { scope: scopeValue });
+    this.container = this.el;
+    this.textInput = this.el.querySelector('input[type="text"]');
+    this.hiddenInput = this.el.querySelector('input[type="hidden"]');
```
Comment (midigofrank) [inline assets/js/hooks/index.ts:391]: can we just have these explicitly specified in the hook definition? 
`<div phx-hook="TagInput" data-text-el={el-id} data-hidden-el={hidden-el-id} data-tag-list={el-id}>`

Comment (midigofrank) [reply assets/js/hooks/index.ts:391]: Also, we can raise an exception when these elements aren't found

**Review by midigofrank — CHANGES_REQUESTED** [review]

File: lib/lightning_web/components/new_inputs.ex (hunk 2 above)
Comment (elias-ba) [reply lib/lightning_web/components/new_inputs.ex]: Fixed

File: assets/js/hooks/index.ts (hunk 3 above)
Comment (elias-ba) [reply assets/js/hooks/index.ts]: Done, thanks

**Review by midigofrank — APPROVED** [review]
