### PR TITLE
Fix cutting-off tooltips

### LINKED ISSUE #972: Tooltip for credential select in Job Edit form is cut off
The hover tooltip is cut off by the job edit box

image

### PR DESCRIPTION
**Pull request by elias-ba**
## Notes for the reviewer

In this PR, I've proposed a solution to enhance the way we render tooltips by leveraging the Tippy.js library in conjunction with hooks.

One of the primary motivations behind choosing [Tippy.js](https://github.com/atomiks/tippyjs) is its extensive customizability, allowing us to control nearly every facet of the tooltip programmatically.

Given that the issue I'm addressing is categorized as a 1-point issue, I've intentionally avoided delving deep into its engineering intricacies (Ex: I have written a custom CSS to handle the style of the tooltip - I know that there's a better way to do this using Tippy's props). Instead, I've focused on an efficient solution that meets our needs while ensuring future adaptability due to Tippy's flexibility.

## Related issue

Fixes #972 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

### CODE REVIEW

File: assets/js/hooks/index.ts [hunk 1]
```diff
@@ -16,6 +17,15 @@ export const Flash = {
   },
 } as PhoenixHook<{ timer: ReturnType<typeof setTimeout> }>;
 
+export const Tooltip = {
+  mounted() {
+    let content = this.el.ariaLabel;
+    tippy(this.el, {
+      content: `${content}`,
```
Comment (stuartc) [inline assets/js/hooks/index.ts:24]: Why is the `content` variable inside a string interpolation? Is this to ensure it's not undefined or null?

If that's the case, can you instead _not_ call `tippy` if the `ariaLabel` is falsey, and call `console.debug` with a message saying that the Tooltip hook was mounted but the element doesn't have a label.

Also I don't see an `destroyed` function, are we sure that `tippy` doesn't have/need an destroy/cleanup functions?

**Review by stuartc — CHANGES_REQUESTED** [review]
Looks good at first glance, left a comment about the hook... I'll fire this up in my browser and check it out after the changes.

File: assets/js/hooks/index.ts (hunk 1 above)
Comment (stuartc) [reply assets/js/hooks/index.ts]: @elias-ba I have made the changes here: https://github.com/OpenFn/Lightning/pull/1017/commits/f1675e007fbc8bf291b1c1e4e7c40f839b4af06b

**Review by stuartc — APPROVED** [review]
