### PR TITLE
Do not send oauth refresh run channel errors to sentry

### LINKED ISSUE #3155: RunChannel: Something went wrong when retrieving the credential
Image

Sentry Issue: [LIGHTNING-WG](https://openfn.sentry.io/issues/6292995020/?referrer=github_integration)

```
RunChannel replied with error
```

Update: We've got a lead on a possible error in runs that could be related to this. See https://openfn.slack.com/archives/C0394D0GBUN/p1749107942234809 for details.

### LINKED ISSUE #3332: Better Error Messaging for "RunChannel: Something went wrong when retrieving the credential"
As a user of the editor, I would like to know what happened to my credential when something goes wrong retrieving my credential and how to proceed to resolve the error.

Image

Currently users whose tokens expire (and other scenarios? ) get an error` RunChannel: Something went wrong when retrieving the credential` The error shows up as an exception but there's no feedback to the customer about what went wrong or what next steps to take.

Before we mute Sentry alerting with https://github.com/OpenFn/lightning/pull/3297, we need to display to the user what's happening and how to proceed.

### LINKED ISSUE #3334: Isolate failed to refresh token errors from "something went wrong"
- [ ] Isolate the "failed to refresh token" errors from the "something went wrong" errors
- [ ] Remove the "failed to refresh token" errors from Sentry

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

Do not send oauth refresh token run channel errors to sentry and improve credential failures run error messages
Screenshot 2025-06-30 at 11 49 17

Fixes #3334 
Fixes #3332

## Additional notes for the reviewer

An error is logged when the refresh token of an oauth credential expires or is invalid. That may still find it's way to Sentry because of https://github.com/OpenFn/lightning/pull/3209

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

**Comment by midigofrank** [comment]
Hey @stuartc , do we really want to log all errors? The one that has Oauth errors is already being logged: https://github.com/OpenFn/lightning/blob/main/lib/lightning_web/channels/run_channel.ex#L118

**Comment by stuartc** [comment]
Ah good point @midigofrank, can you make sure that logger message isn't just a stacktrace. We want to know the credential id at least, and make sure we know the response from the oauth provider, so could you change that existing log to do that. Ask @eliaswalyba for help on recreating the error if necessary. Then anyone else can merge.

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@midigofrank , @stuartc , @theroinaochieng my read on this PR is that it would silence Sentry. Are you certain we want to silence these? Are we looking at the same thing here? 

image

This is still the most frequent error I can see on Sentry. 486 occurrences of us telling our users "we tried to run your run, but broke a thing and we don't know how to fix it" in the last 30d.

**Comment by midigofrank** [comment]
Hey Taylor, yes you've read it right. Thing is, at this point we already
know that the cause of those errors is either Oauth refresh tokens have
expired or are just invalid. Meaning the errors are just spamming Sentry
currently.

We discussed that we need a way to tell users about this, something like a
better log message or an alert. The solution is more of a product question

**Comment by stuartc** [comment]
@taylordowns2000 

So what we have here with the run channel errors to Sentry, Frank is absolutely
right. We already know about these errors. 99% of the time, or as far as we
know, we can't really do anything about them. They are "natural" failures. Now,
if there are other issues with these credential errors. We don't really have a
plan right now to find out what is different about a regular refresh error and
one that we don't know about. For example, there is something wrong with our
software. So right now the objective is to lower the noise in Sentry.

There is a different but related discussion about:

1. what we tell the user and
2. how do we detect failures that are not anticipated ones that we have control
   over.

**Comment by josephjclark** [comment]
But these look like generic errors? They could be raised by anything no? I get that we don't want to report oauth errors to sentry - that's cool. But  I worry that we're cutting out other stuff that might be valuable

**Comment by taylordowns2000** [comment]
@josephjclark , I _think_ this may be held out until the parent bug is closed:

- Bug: https://github.com/OpenFn/lightning/issues/3155

- Sub issue 1: https://github.com/OpenFn/lightning/issues/3334 (this PR closes this one, but there are some unaddressed change requests from @stuartc to make the error handling more granular)

- Sub issue 2: https://github.com/OpenFn/lightning/issues/3332

So maybe "not ready for review" yet

**Comment by midigofrank** [comment]
Alright, these new changes separates the "oauth token refresh errors" from the rest. Just waiting to reproduce the error to confirm.

Also we're now sending the response from the provider to the worker. @josephjclark do you think it's possible to log this returned error as part of #3332?

File: lib/lightning_web/channels/run_channel.ex [hunk 1]
```diff
@@ -114,19 +114,41 @@ defmodule LightningWeb.RunChannel do
...
         })
 
+      {:error, :reauthorization_required} ->
+        Logger.error("oauth refresh token has expired", credential_id: id)
+
+        {:reply,
+         {:error,
+          %{
+            message: "Your oauth token has expired",
+            fix: "Visit your credentials page and reauthorize the credential"
```
Comment (taylordowns2000) [inline lib/lightning_web/channels/run_channel.ex]: love love love @midigofrank and @elias-ba

Comment (taylordowns2000) [reply lib/lightning_web/channels/run_channel.ex]: wait, @elias-ba and @midigofrank , can we do something like:

`Visit #{Application.host_url}/credentials and open the #{credential.name} to reauthorize.`

That link will be nicely formatted and clickable when it appears in the Monaco log viewer.

Comment (midigofrank) [reply lib/lightning_web/channels/run_channel.ex]: Hmm, yeah good point

**Comment by midigofrank** [comment]
@stuartc I've added the `credential_id` as part of the log metadata

**Review by taylordowns2000 — COMMENTED** [review]
does this require an additional change on the worker side? i'm still seeing this error:

image

**Review by taylordowns2000 — APPROVED** [review]

**Review by elias-ba — APPROVED** [review]
@midigofrank I really love this, 👏🏽 ❤️

**Comment by midigofrank** [comment]
There's a related worker issue here: https://github.com/OpenFn/kit/pull/950

**Comment by midigofrank** [comment]
Hey @elias-ba @josephjclark , I have resorted to just send the message as a string instead of an object. I was trying to format the object in https://github.com/OpenFn/kit/pull/950 for the logs and just wasn't successful. The worker was escaping the `\n`s in the error message when it's inside the object. 

As it is right now, it should just work with the previous worker versions because it is a string 
Screenshot 2025-06-30 at 11 49 17

**Review by stuartc — APPROVED** [review]
Good work!
