### PR TITLE
Fix put project credentials on new credential

### LINKED ISSUE #2993: Newly created credentials don't get added to projects
When I create a new credential and carefully add it to 4-5 projects, then click save, it creates the credential but doesn't add it to those proejcts. I have to go back and do it again.

`v2.10.16 (1.4.18)`

### PR DESCRIPTION
**Pull request by jyeshe**
## Description

This PR fixes putting the project credentials relations on a new credential.

Closes #2993

## Validation steps

1. Select a credential to create
2. Still on the Add Credential modal, select on "Grant project access to this credential" a project and add it
3. Repeat for another project before saving the credential
4.  Save the credential and it shows associated to the credential the projects you've selected.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning_web/live/credential_live/credential_form_component.ex [hunk 1]
```diff
@@ -688,16 +688,9 @@ defmodule LightningWeb.CredentialLive.CredentialFormComponent do
        ) do
     user_id = Ecto.Changeset.fetch_field!(changeset, :user_id)
 
-    project_credentials =
-      Ecto.Changeset.fetch_field!(changeset, :project_credentials)
-      |> Enum.map(fn %{project_id: project_id} ->
-        %{"project_id" => project_id}
-      end)
```
Comment (jyeshe) [inline lib/lightning_web/live/credential_live/credential_form_component.ex:695]: This overwrites the associations that were set previously.

Comment (midigofrank) [reply lib/lightning_web/live/credential_live/credential_form_component.ex:695]: Hey @jyeshe , did you try to edit it after creation? I think this was set so that you can edit as a whole

Comment (midigofrank) [reply lib/lightning_web/live/credential_live/credential_form_component.ex:695]: Just tested. Works!!

**Review by midigofrank — APPROVED** [review]
Nicely done 🙌

File: lib/lightning_web/live/credential_live/credential_form_component.ex (hunk 1 above)
Comment (jyeshe) [reply lib/lightning_web/live/credential_live/credential_form_component.ex:695]: Thanks Frank, it was a surgical on `:new`

**Review by elias-ba — APPROVED** [review]
Thanks @jyeshe, this is very well done
