### PR TITLE
2823 metrics authorization return 401

### LINKED ISSUE #2823: Change authorization behaviour for /metrics endpoint.
Currently the `/metrics` endpoint uses the protection approach suggested by the author or Promex. If authorization fails, the promex plug is not loaded and a 404 is returned. 

This has, so far, worked well. Recently I have encountered a potential consumer of metrics that will make the initial request sans credentials (whether using Basic or Bearer auth). It expects the host to reply with an HTTP 401 after which it will send a second request that contains the appropriate `Authorization` header.

This issue is to implement an alternative Authorization mechanism that will return HTTP 401 on Authorization failure.

### PR DESCRIPTION
**Pull request by rorymckinley**
### Description

Some HTTP clients may require Lightning to reply with an HTTP 401 before they send through a request that contains the correct Authorization header.

This change replaces the original implementation with an authorisation model that will respond with an HTTP 401 rather than just not mounting the endpoint. I added the `PromexWrapper` module to increase the chance that the `MetricsAuth` struct is loaded before `Promex.Plug`. I also added some additional test coverage to try help prevent accidental rearranging of the sequence.

The initial change to production code is [here](https://github.com/OpenFn/lightning/pull/2836/commits/a9bdcbf948fcdc2871a2724c194e7084f30034f5). I tried to keep the code as close to the  [original code](https://github.com/OpenFn/lightning/blob/main/lib/lightning_web/prom_ex_plug_authorization.ex) as possible to make comparison easier.

The code is then refactored [here](https://github.com/OpenFn/lightning/pull/2836/commits/d4fe763f663a78506934a86fb04382380b564ba4).

Closes #2823 

### Validation steps

Set the following env variables:
- `PROMEX_ENABLED` to `true`
- `PROMEX_METRICS_ENDPOINT_AUTHORIZATION_REQUIRED` to `yes`
- `PROMEX_METRICS_ENDPOINT_TOKEN` to `foobar`
- `PROMEX_ENDPOINT_SCHEME` to `http`

Start your local Lightning instance.

Use curl to confirm that you can still access the metrics:

```
$ curl -H "Authorization: Bearer foobar" http://localhost:4000/metrics
```
```
# HELP lightning_prom_ex_phoenix_endpoint_port_info The configured port of the Endpoint module.
# TYPE lightning_prom_ex_phoenix_endpoint_port_info gauge
lightning_prom_ex_phoenix_endpoint_port_info{endpoint="LightningWeb.Endpoint",port="4000"} 1
# HELP lightning_prom_ex_phoenix_endpoint_url_info The configured URL of the Endpoint module.
# TYPE lightning_prom_ex_phoenix_endpoint_url_info gauge
lightning_prom_ex_phoenix_endpoint_url_info{endpoint="LightningWeb.Endpoint",url="http://localhost:4000"} 1
.....
```

Use curl to confirm that you cannot access metrics if your authorization details are incorrect:

```
curl -H "Authorization: Bearer fooba" http://localhost:4000/metrics
```

```
Unauthorized
```

### Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning_web/plugs/promex_wrapper.ex [hunk 1]
```diff
@@ -0,0 +1,9 @@
+defmodule LightningWeb.Plugs.PromexWrapper do
+  @moduledoc """
+  Ensures that the MetricsAuth plug always comes before the PromEx plug.
+  """
+  use Plug.Builder
+
+  plug LightningWeb.Plugs.MetricsAuth
+  plug PromEx.Plug, prom_ex_module: Lightning.PromEx
```
Comment (jyeshe) [inline lib/lightning_web/plugs/promex_wrapper.ex:8]: Neat stuff :sparkles:

**Review by jyeshe — APPROVED** [review]
Great refactoring and it works as expected!

**Review by midigofrank — APPROVED** [review]
Nicely done @rorymckinley.
