### PR TITLE
Set max_frame_size to 11MB

### LINKED ISSUE #2339: 40mb dataclips can crash the web app
In version `v2.7.11`, when large dataclips (~38MB) are sent back to Lightning from the `ws-worker` between steps, the app can crash.

Still investigating this, but below are a few timestamps where it seems that a crash was caused by a large dataclip:

### Log Timestamps around app crashes
- 13:22 to 13:23 UTC
- 13:59 to 14:02 UTC

```js
fn(state => {
  const targetSizeMB = 40;

  // Calculate the number of characters needed (1 char = 2 bytes in UTF-16)
  const targetSizeChars = (targetSizeMB * 1024 * 1024) / 2;

  // Create a base string to use
  const baseString = "A".repeat(100); // 100 characters long

  // Calculate the number of times the base string needs to be repeated
  const repeatCount = Math.ceil(targetSizeChars / baseString.length);

  // Create the large array
  const largeArray = [];
  for (let i = 0; i < repeatCount; i++) {
    largeArray.push(baseString);
  }

  // Create the final JSON object
  const largeJsonObject = {
    data: largeArray
  };

  return { largeJsonObject };
})
```

### PR DESCRIPTION
**Pull request by stuartc**
### Description

`max_frame_size` needs to be set at the socket in endpoint, not in the Endpoint config.

Setting it to 11MB statically for now, no easy way to make this dynamic since `socket` doesn't appear to use plug builder (i.e. can't use Replug).

What happens when a worker sends a payload that is too big it drops the connection on the floor, not exactly what we want but ok for now I guess. The worker will see a timeout error on the socket.

Fixes #2339

### Validation steps

Setting the limit to 1MB and changing the endpoint to:

```diff
diff --git a/lib/lightning_web/endpoint.ex b/lib/lightning_web/endpoint.ex
index 2c4f4f7ad..410c855ee 100644
--- a/lib/lightning_web/endpoint.ex
+++ b/lib/lightning_web/endpoint.ex
@@ -16,7 +16,11 @@ defmodule LightningWeb.Endpoint do
     websocket: [connect_info: [session: @session_options]]
 
   socket "/worker", LightningWeb.WorkerSocket,
-    websocket: [error_handler: {LightningWeb.WorkerSocket, :handle_error, []}],
+    websocket: [
+      error_handler: {LightningWeb.WorkerSocket, :handle_error, []},
+      compress: true,
+      max_frame_size: 1_000
+    ],
     longpoll: false
 
   # Serve at "/" the static files from "priv/static" directory.
```

When a generate an output data clip thats more than a megabyte:

```js
fn(state => {
  return new Promise((resolve) => {
    setTimeout(() => {  // ignore the timeout...
      let big = new Array(1024 * 1024).fill('z').join('');
      resolve({...state, step: 1, big})
      }, 10000);
  })
});
```  

Then the socket gets dropped on the floor:

```
[info] [SRV] ✘ 5d83a439-da2f-4e40-a35e-c34b5262a848 :: step:complete :: ERR: timeout
[info] [SRV] ✘ Error: timeout
[info]     at Object.callback (file:///Users/stuart/Sourcecode/lightning/assets/node_modules/@openfn/ws-worker/dist/start.js:923:12)
...
```

### Additional notes for the reviewer

There will be complementary work on the worker side to stop big data clips _before_ they get sent. So in the long run this acts as a safety net for DoS and bugs.

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.

### CODE REVIEW

File: lib/lightning_web/endpoint.ex [hunk 1]
```diff
@@ -16,7 +16,11 @@ defmodule LightningWeb.Endpoint do
     websocket: [connect_info: [session: @session_options]]
 
   socket "/worker", LightningWeb.WorkerSocket,
-    websocket: [error_handler: {LightningWeb.WorkerSocket, :handle_error, []}],
+    websocket: [
+      error_handler: {LightningWeb.WorkerSocket, :handle_error, []},
+      compress: true,
+      max_frame_size: 11_000_000
```
Comment (jyeshe) [inline lib/lightning_web/endpoint.ex:22]: I am wondering if the compression works before or after the frame size is validated.

**Review by jyeshe — APPROVED** [review]
