### PR TITLE
fix: Disable AI Assistant when Apollo not configured

### LINKED ISSUE #4354: Regression: AI Assistant still available when Apollo isn't set up
**Describe the bug** On a local Lightning build, the AI assistant is still available for users to type in messages despite not having Apollo set up locally. This causes users to send messages and wait for responses that won't come because of the missing set up. 

I have reproduced this locally on main:

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by lmac-1**
### Problem
AI Assistant button was clickable when Apollo wasn't configured, causing silent failures where messages sent but never received responses.

### Solution
- Disable AI chat button when `APOLLO_ENDPOINT` or `AI_ASSISTANT_API_KEY` are missing
- Show tooltip: "Your instance does not have build-time AI enabled. Contact your administrator or support@openfn.org to configure it."
- Disable Cmd+K keyboard shortcut

Closes #4354

## Validation steps

1. Verify that it solves the scenario defined in #4354 
2. Also locally, comment out `APOLLO_ENDPOINT` or `AI_ASSISTANT_API_KEY` environment variables and confirm that AI assistant button is disabled. There should be a tooltip text advising the user. Make sure you can't open panel either with Cmd/Ctrl + K

## Additional notes for the reviewer

1. I haven't been able to replicate the exact case described by Roina re local builds.. so I just want someone else to confirm that this definitely fixes that scenario. 

## AI Usage

Please disclose whether you've used AI anywhere in this PR (it's cool, we just
want to know!):

- [x] I have used Claude Code
- [ ] I have used another model
- [ ] I have not used AI

You can read more details in our
[Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed an AI review of my code (we recommend using `/review`
      with Claude Code)
- [ ] I have implemented and tested all related **authorization policies**.
      (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/AIAssistantPanelWrapper.tsx [hunk 1]
```diff
@@ -66,7 +66,11 @@ import { MessageList } from './MessageList';
  * - Persists width in localStorage
  * - Syncs open/closed state with URL query param (?chat=true)
  */
-export function AIAssistantPanelWrapper() {
+export function AIAssistantPanelWrapper({
+  aiAssistantEnabled = false,
+}: {
+  aiAssistantEnabled?: boolean;
+} = {}) {
```
Comment (elias-ba) [inline assets/js/collaborative-editor/components/AIAssistantPanelWrapper.tsx]: The = {} default destructuring can be removed since the prop is always passed, right ?

File: assets/js/collaborative-editor/components/Header.tsx [hunk 2]
```diff
@@ -240,6 +242,13 @@ export function Header({
   // When ?v= is present, user is viewing a specific version (even if latest)
   const isPinnedVersion = params['v'] !== undefined && params['v'] !== null;
 
+  // Determine AI button disabled message based on priority
+  const aiButtonDisabledMessage = !aiAssistantEnabled
+    ? 'Your instance does not have build-time AI enabled. Contact your administrator or support@openfn.org to configure it.'
```
Comment (elias-ba) [inline assets/js/collaborative-editor/components/Header.tsx:247]: Why do we use the expression "build-time AI" here ? Is that clear to the end user ? I know that expression because I have heard it being used internally multiple times. Is it the case for the end user in Lesotho using this app ? Wouldn't they stay minutes thinking about that term and asking themselve what does this mean ? Why not just use the term "AI Assistant" ? cc @taylordowns2000

Comment (lmac-1) [reply assets/js/collaborative-editor/components/Header.tsx:247]: @taylordowns2000 I used the message you mentioned on Slack but let me know if it should be changed. I agree that "AI assistant" could be a bit clearer for the user. 

This error message will trigger when the env variables aren't set up for AI assistant - can someone also confirm that's the scenario Roina was reporting (with local builds, etc.)?

File: assets/js/collaborative-editor/components/AIAssistantPanelWrapper.tsx (hunk 1 above)
Comment (lmac-1) [reply assets/js/collaborative-editor/components/AIAssistantPanelWrapper.tsx]: Done! Nice catch.

File: assets/js/collaborative-editor/components/Header.tsx (hunk 2 above)
Comment (lmac-1) [reply assets/js/collaborative-editor/components/Header.tsx:247]: @theroinaochieng we just need clarification / confirmation of this message. If it's okay we can approve and merge, if not I can make the update.
