### PR TITLE
fix: make template preview read-only in collaborative editor

### LINKED ISSUE #4203: Regression: Templates are editable
**Describe the bug** Users can now add nodes, edit job names and edit templates before creating a workflow

**Version number** The version of Lightning you have seen the bug on.

If you're running on a tagged version, include the number: `vX.Y.Z`

If you're running locally with an unreleased version, the commit sha: `84b1bdc`

I have reproduced this locally on main:

- [ ] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR **fixes** the template preview read-only behavior in the collaborative editor. Users viewing a template or AI-generated workflow preview can no longer edit until they click "Create". This prevents confusing bugs where edits would be lost.

Closes #4203

## Validation steps

1. Go to a project and click "New Workflow"
2. Select a template from the template browser
3. Verify the workflow renders on canvas with the details overlay
4. Verify you **cannot**:
   - Toggle the workflow enable/disable switch
   - Click the "Code" button in the job inspector
   - Click the "Run" button in the job or trigger inspector
   - Add new nodes to the canvas
5. Click "Create" to save the workflow
6. Verify all editing features are now enabled
7. Do the same for AI generated templates and for the YAML imported workflows too

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: assets/js/collaborative-editor/components/NewRunButton.tsx [hunk 1]
```diff
@@ -29,8 +29,8 @@ export function NewRunButton({
 }: NewRunButtonProps) {
   const { canRun, tooltipMessage } = useCanRun();
 
-  // Allow parent to add additional disabled conditions
-  const isDisabled = disabledProp ?? !canRun;
+  // Disable if parent requests OR if canRun is false
+  const isDisabled = disabledProp || !canRun;
```
Comment (doc-han) [inline assets/js/collaborative-editor/components/NewRunButton.tsx:33]: I think `??` was used so that when `disabledProps` is `false`, that is treated as an expected value and we wouldn't fallback to `canRun`

**Review by doc-han — APPROVED** [review]

**Review by taylordowns2000 — APPROVED** [review]
fantastic. thanks @elias-ba

**Comment by theroinaochieng** [comment]
Works great. Thanks @elias-ba

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
@elias-ba , please update the changelog then merge

File: assets/js/collaborative-editor/components/NewRunButton.tsx (hunk 1 above)
Comment (elias-ba) [reply assets/js/collaborative-editor/components/NewRunButton.tsx:33]: Hey dude, good catch on the intent there! You're right that `??` was probably deliberate. It lets `disabled={false}` explicitly override the `canRun` check.

The issue we ran into was with template preview mode. When a user is viewing a template before clicking "Create", we pass `disabled={isReadOnly}` to prevent running. But `isReadOnly` evaluates to `false` for normal workflows, and with `??`, that `false` was being treated as "explicitly enabled", which meant it completely bypassed the `canRun` check.

So a user could have a workflow that wasn't saved yet (`canRun: false`), but because `isReadOnly` was `false`, the button would still be enabled.

Switching to `||` means the button is disabled if *either* condition is true. The parent says so OR the workflow can't be run. This felt like the safer default for a "Run" button.

That said, if there's a use case where we need `disabled={false}` to force-enable the button regardless of `canRun`, we could make this more explicit, maybe separate props like `forceEnabled` or rename things to be clearer.

What do you think?

Comment (doc-han) [reply assets/js/collaborative-editor/components/NewRunButton.tsx:33]: Alright. makes sense. so if I'm getting it right. disabled should always depend on both conditions and never just one of them.
