### PR TITLE
Fix job editor switches to the snapshot version when body is changed

### LINKED ISSUE #2306: Editor switches to the snapshot/readonly mode without user toggling snapshot mode
When inspecting a job in snapshot mode I switched to the latest version to edit the job code. After typing a few characters, the editor switches to the snapshot version and read-only mode. When this happens, the snapshot version, toggle, and snapshot ID chip still indicate that the "latest" version is selected.

https://www.loom.com/share/22a7de9164354895b0b489f174080aa9

### LINKED ISSUE #2308: Misaligned "Retry from here" button on inspector page
There is a regression on the inspector page where there is a mismatch between the heights of the button and the dropdown as shown below.  
image

### PR DESCRIPTION
**Pull request by midigofrank**
### Description

This PR fixes the bug on the inspector that switches the job editor back to the snapshot version whenever the user types anything in. You can check the issue #2306 for a video on this

Closes #2306 
Closes #2308 

### Validation steps
In order to validate this, we'll need to have a workflow with at least one job in it. 
We'll create a manual work order using the job as it is, then later update the job body to have something else.
This way, we'll have a work order with an older version of the job body.

**These instructions assume you've done the the above**

1. Open up the inspector from the executed step of the work order in the history page
2. The inspector will open up in "snapshot mode". Now toggle to switch to the latest version
3. Notice that the job editor content gets updated to the latest job body.
4. If you try changing the job body, the content gets updated and the editor doesn't switch back to the snapshot version

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.

### CODE REVIEW

File: lib/lightning_web/live/workflow_live/editor_pane.ex [hunk 1]
```diff
@@ -78,6 +78,8 @@ defmodule LightningWeb.WorkflowLive.EditorPane do
     {:noreply, socket}
   end
 
+  # NOTE: This is dead code and should probably be removed. All events are
```
Comment (elias-ba) [inline lib/lightning_web/live/workflow_live/editor_pane.ex:81]: Maybe we should remove it in this work, what do you think ?

**Review by elias-ba — APPROVED** [review]
@midigofrank this is looking good to me, great job 👏. I left a comment but up to you to handle it or not.

File: lib/lightning_web/live/workflow_live/editor_pane.ex (hunk 1 above)
Comment (midigofrank) [reply lib/lightning_web/live/workflow_live/editor_pane.ex:81]: I don't feel confident enough to remove it at this time. I was thinking of removing it as a follow-up when everything is tested and works fine

**Review by christad92 — APPROVED** [review]
Loooooveeee eeeeeett!! 

Thanks mate!
