### PR TITLE
Fix retry many workorders when built for job

### LINKED ISSUE #2591: Retrying multiple work orders of workflows fails
This occurs when I select two or more work orders of different workflows and click "Retry" on the history page. it returns a notification that the runs have been enqueued but does not show the enqueued runs on the history table.

When I select multiple work orders of the same workflow, it works as expected. 

Sentry Issue: [LIGHTNING-KG](https://openfn.sentry.io/issues/5998931040/?referrer=github_integration)

```
KeyError: key :edges not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
  File "lib/lightning/work_orders.ex", line 665, in Lightning.WorkOrders.determine_starting_job/1
  File "lib/lightning/work_orders.ex", line 530, in anonymous fn/5 in Lightning.WorkOrders.enqueue_many_for_retry/2
  File "lib/ecto/multi.ex", line 973, in anonymous fn/5 in Ecto.Multi.operation_fun/2
  File "lib/ecto/multi.ex", line 883, in Ecto.Multi.apply_operation/5
  File "lib/enum.ex", line 2528, in Enum."-reduce/3-lists^foldl/2-0-"/3
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jyeshe**
### Description

This PR fixes the enqueue work on retry many work orders when the work order was originally built for manual job (without a trigger).

Closes #2591 

### Validation steps

1. Create work order for job (a manual one)
2. Go to history page
3. Select the work order along with another one and click on retry
4. Check that it has run 

### Additional notes for the reviewer

This change affects the scenario when the work order doesn't have a run (on rejected work orders for example). When there is a run, it gets the job from the starting trigger.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/work_orders.ex [hunk 1]
```diff
@@ -661,39 +661,35 @@ defmodule Lightning.WorkOrders do
...
   end
 
   defp workorders_with_dataclips_query(workorder_ids) do
     from(w in WorkOrder,
-      left_join: d in assoc(w, :dataclip),
-      where: w.id in ^workorder_ids,
-      preload: [
-        :workflow,
-        :dataclip,
-        trigger: [edges: :target_job]
```
Comment (jyeshe) [inline lib/lightning/work_orders.ex:688]: uses workflow edges instead (it is always available)

**Review by elias-ba — APPROVED** [review]
Thanks @jyeshe

**Review by stuartc — APPROVED** [review]
