### PR TITLE
Remove Credentials for Collaborators Removed from a Project

### LINKED ISSUE #2942: When removing a collaborator, remove their credentials from the project
Today, we don't remove a user's credentials from a project (that uses the credentials) if we are removing the user as a project collaborator. This potential threatens the security of the project and can lead to failed runs if the credential details/permissions change in the future. 

When a user is removed as a collaborator in a project, we should remove credentials owned by them. This will ensure that we keep the project secured and that a future change to the credential does not impact the project.

When removing a collaborator, the confirmation message reads "Are you sure you want to remove "rita zagoni" from this project? They will no longer have access. Do you wish to proceed with this action?" but we should extend it to say: 

> Are you sure you want to remove "user.name" from this project? 
>
>They will no longer have access and their owned credentials [list of credentials] will be removed from this project. 
>
>Do you wish to proceed with this action?

### PR DESCRIPTION
**Pull request by elias-ba**
## Description

This PR adds functionality to automatically remove a user's credentials from a project when removing that user from the project.

Closes #2942 

## Validation steps

1. Create a project with multiple users
2. Add credentials owned by these users to the project
3. Remove a user from the project
4. Verify that credentials owned by the removed user are no longer available in the project
5. Verify the confirmation dialog shows the correct credentials that will be removed

PS: Demo video available [here](https://www.loom.com/share/8d47e7334ae845318093d206f465b666?sid=824b6f1c-068e-4b89-9308-20319f947f3c)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/projects.ex [hunk 1]
```diff
@@ -431,8 +431,32 @@ defmodule Lightning.Projects do
...
+    project_user =
+      %{user_id: user_id, project_id: project_id} =
+      Repo.preload(project_user, [:user, :project])
+
+    from(pc in Lightning.Projects.ProjectCredential,
+      join: c in Lightning.Credentials.Credential,
+      on: c.id == pc.credential_id,
+      where: c.user_id == ^user_id and pc.project_id == ^project_id
+    )
+    |> Repo.delete_all()
```
Comment (midigofrank) [inline lib/lightning/projects.ex:458]: Can we wrap these operations in a transaction? The chances of one failing while the other succeeds is very minimal but just to be safe

File: lib/lightning_web/live/project_live/settings.ex [hunk 2]
```diff
@@ -665,7 +686,7 @@ defmodule LightningWeb.ProjectLive.Settings do
       <div class="px-6">
         <p class="text-sm text-gray-500">
           Are you sure you want to remove "{@project_user.user.first_name} {@project_user.user.last_name}" from this project?
-          They will nolonger have access.
+          They will no longer have access{@credentials_text} will be removed from this project.
```
Comment (midigofrank) [inline lib/lightning_web/live/project_live/settings.ex:689]: Hmm 🤔 , this will read: `They will no longer have access will be removed from this project` when the user has no credential in the project.  Could you double check?

**Review by midigofrank — CHANGES_REQUESTED** [review]
Great job @elias-ba . Left a few comments

File: lib/lightning_web/live/project_live/settings.ex (hunk 2 above)
Comment (elias-ba) [reply lib/lightning_web/live/project_live/settings.ex]: Thanks for the catch, this is fixed

File: lib/lightning/projects.ex (hunk 1 above)
Comment (elias-ba) [reply lib/lightning/projects.ex]: Thanks man, I just wrapped them in a transaction

**Comment by elias-ba** [comment]
Hey man, thanks for the review. I just handled you changes request. Are you happy giving me another round of review ?

**Review by midigofrank — APPROVED** [review]
