### PR TITLE
Fix Session crashes when workflow has `deleted_at` field

### LINKED ISSUE #4245: Session crashes when workflow has deleted_at field
Sentry Issue: [LIGHTNING-18M](https://openfn.sentry.io/issues/7000126742/?referrer=github_integration)

```
MatchError: no match of right hand side value: {:error, {%ErlangError{original: :invalid_variant, reason: nil}, [{Yex.Nif, :map_set, [%Yex.Map{doc: %Yex.Doc{reference: #Reference<0.3258196940.470941698.73409>, worker_pid: #PID<0.468923.0>}, reference: <<105, 100, 0, 82, 111, 111, 116, 0, 8, 119, 111, 114, 107, 102, 108, 111, 119, 0, 1, 16, 1, 1, 1, 14, 20, 95, 116, 97, 103, 0, 2, 6, 32, 2, 1, 2, 0, 14, 0, ...>>}, #Reference<0.3258196940.470941698.73594>, "deleted_at", ~U[2025-12-10 12:26:32Z]], []}, {Yex.Doc, :transaction, 3, [file: ~c"lib/doc.ex", line: 170]}, {Lightning.Collaboration.Persistence, :reconcile_workflow_metadata, 2, [file: ~c"lib/lightning/collaboration/persistence.ex", line: 162]}, {Lightning.Collaboration.Persistence, :bind, 3, [file: ~c"lib/lightning/collaboration/persistence.ex", line: 32]}, {Yex.Sync.SharedDoc, :init, 2, [file: ~c"lib/protocols/shared_doc.ex", line: 124]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 2229]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 2184]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}]}}
  File "lib/lightning/collaboration.ex", line 81, in Lightning.Collaborate.start_document/2
  File "lib/lightning/collaboration.ex", line 59, in Lightning.Collaborate.start/1
  File "lib/lightning_web/channels/workflow_channel.ex", line 57, in LightningWeb.WorkflowChannel.join/3
  File "lib/phoenix/channel/server.ex", line 391, in Phoenix.Channel.Server.channel_join/4
  File "lib/phoenix/channel/server.ex", line 305, in Phoenix.Channel.Server.handle_info/2
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

Yex doesn't support DateTime structs. Workflows with `deleted_at` fields were causing the Y.Doc server to crash

Closes #4245

## Validation steps

I was able to reproduce this through tests. You can check the test file

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [x] Code generation (copilot but not intellisense)
- [x] Learning or fact checking
- [x] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [ ] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/collaboration/persistence.ex [hunk 1]
```diff
@@ -167,7 +167,12 @@ defmodule Lightning.Collaboration.Persistence do
       Yex.Map.set(workflow_map, "name", workflow.name)
 
       # Update deleted_at if present
-      Yex.Map.set(workflow_map, "deleted_at", workflow.deleted_at)
+      # Convert DateTime to string for Yex compatibility (Yex doesn't support DateTime structs)
+      Yex.Map.set(
+        workflow_map,
+        "deleted_at",
+        workflow.deleted_at && to_string(workflow.deleted_at)
```
Comment (elias-ba) [inline lib/lightning/collaboration/persistence.ex]: There's already a `datetime_to_string/1` helper in `workflow_serializer.ex` (lines 281–282) that does exactly this:

```elixir
defp datetime_to_string(nil), do: nil
defp datetime_to_string(%DateTime{} = dt), do: DateTime.to_iso8601(dt)
```

For consistency with the existing pattern in `workflow_serializer.ex` (lines 73–74), the fix could reuse this helper. That would require either extracting it into a shared location or duplicating it.

Comment (midigofrank) [reply lib/lightning/collaboration/persistence.ex]: Great catch man
