### PR TITLE
Fix handling of metadata-related errors

### LINKED ISSUE #3367: Lightning displays incorrect message in job editor when adaptor does not support metadata
**Describe the bug**

Given a job that uses an adaptor that does not support metadata (e.g. http), when you view the metadata tab in the job editor, you are presented with `An error occurred while loading metadata: enoent`. This is because Lightning is not correctly handling the case where the CLI is reporting that the adaptor does not support metadata.

**Version number** 

https://github.com/OpenFn/lightning/commit/7641d342408c3d0361c96455958abde4bc3e49bf

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

See the description above.

**Expected behavior** 

To show the message that the adaptor does not support 'magic functions'.

**Screenshots**

**Additional context**

Pretty sure we need to look here: https://github.com/OpenFn/lightning/blob/main/lib/lightning/metadata_service.ex#L112

### PR DESCRIPTION
**Pull request by rorymckinley**
## Description

When Lightning checks the metadata response for an adaptor, it does not correctly deal with two cases:

- When metadata is not supported, it treats the error message as a path, resulting in:

Screenshot From 2025-07-07 16-37-02

- When there is a credential error (URL is borked, bad creds), it should show a message indicating that there may be an issue with the credential, but instead it shows that the adaptor does not support metadata:

Screenshot From 2025-07-07 16-37-41

Closes #3367 

## Validation steps

- In local Lightning, setup a dummy http credential and then modify a job to use the `http` adaptor with this credential.
- Click to 'Edit' the Job, wait a few seconds for the backend to fetch the adaptor and then navigate to the Metadata tab in the job editor.
- You should see a message similar to the below:

image

- Return to the Workflow editor.
- Create a DHIS2 credential with broken creds (e.g. `https://play.im.dhis2.org/stable-2-42-0` with `foo` and `bar` as the username and password respectively).
- Change your job to use the dhis2 adaptor (version earlier than 7.x.x) and then edit the job.
- Wait for Lighting to fetch the adaptor and then click on the Metadata tab and you should see the below error:

image

## Additional notes for the reviewer

Colonel Sanders (of KFC fame) was an "actual" colonel. He was given the honorific title of "Kentucky Colonel" in 1935. He would later capitalise on this by adjusting his appearance and dress to match that of a Confederate colonel as he identified the branding potential of being 'Colonel Sanders'.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning/metadata_service.ex [hunk 1]
```diff
@@ -110,13 +110,17 @@ defmodule Lightning.MetadataService do
...
   defp get_output_path(result) do
-    path =
+    last_message =
       result
       |> CLI.Result.get_messages()
       |> List.last()
 
     cond do
-      path ->
+      is_map(last_message) ->
```
Comment (rorymckinley) [inline lib/lightning/metadata_service.ex:119]: There is arguably some room to refactor the cond here, but this fix has already taken a lot of time (due to my ignorance) so I thought I would leave that for another day as I think this PR already complies with the Boy Scout principle :).

**Review by elias-ba — APPROVED** [review]
Nice one @rorymckinley, thanks

**Review by stuartc — APPROVED** [review]
