### PR TITLE
Fix users unable to change workflow concurrency settings

### LINKED ISSUE #3459: Cannot save workflow concurrency
**Describe the bug**
https://www.loom.com/share/2c5c11ecca0e491c8c67739bb528f11b?sid=d583a128-7c61-4217-b285-92b7ae31c9eb

I have reproduced this locally on main:

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by midigofrank**
## Description

This PR adds `concurrency` and `enable_job_logs` to the workflow params to ensure they're picked by the changeset.

Initially, clicking on `save button` would submit the `#workflow-form`, but currently it doesn't, it only sends the `save` event without any params. The current functionality assumes that all the needed changes have been added to the `Ecto.Changeset`. 

Closes #3459 

## Validation steps

1. Login as a project admin
2. Open the workflow settings panel
3. Update the concurrency and `console.log()` toggle
4. Click the save button
5. The updated values should stick and not get reset.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

## Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

### CODE REVIEW

File: lib/lightning_web/live/workflow_live/workflow_params.ex [hunk 1]
```diff
@@ -86,7 +86,14 @@ defmodule LightningWeb.WorkflowNewLive.WorkflowParams do
...
        when is_function(accessor) do
     Map.merge(
-      changeset |> to_serializable([:project_id, :name, :positions]),
+      changeset
+      |> to_serializable([
+        :project_id,
+        :name,
+        :concurrency,
+        :enable_job_logs,
+        :positions
```
Comment (elias-ba) [inline lib/lightning_web/live/workflow_live/workflow_params.ex:95]: Nice 😋

**Review by elias-ba — APPROVED** [review]
Hey @midigofrank this looks rock solid. Nice one 👏🏽
