### PR TITLE
include workflow and job names in provisioning error messages

### LINKED ISSUE #2140: Improve error messaging on CLI by specifying job names/edges  in error messages
When using openfn deploy  in the CLI to migrate projects, users sometimes get back error messages on incorrect job names and edge condition labels, etc .

 **It would be super valuable to be able to see which job name and edge condition the error is related to** without having to manually go through have 200+ jobs. 

This is NOT a priority but would be important to have at some point.

It would be great if we can format error messages like `workflow-1/job-3: invalid character in job name`

example incorrect job name: `Fetch & upsert` 
(containing special character except for `-`)

### PR DESCRIPTION
**Pull request by midigofrank**
## Validation Steps
**In case you don't know how the cli works:**
 https://docs.openfn.org/documentation/deploy/portability#using-the-cli-to-deploy-or-describe-projects-projects-as-code

**NOTE**: 
- You don't have to install the cli from npm. You can access it from `./priv/openfn/bin/openfn` in lightning's dir
- You can generate your access token from: http://localhost:4000/profile/tokens
- Ensure you've set openfn endpoint in your `config.json` as  http://localhost:4000

**How to test**
1. Pull a one your projects from your local server
2. Modify the project spec to make it invalid.
    - You can invalidate a job by omitting the `body`.
    - You can invalidate a trigger by omitting the `type`
    - You can invalidate an edge by omitting the `condition`
    - Just try anything crazy to invalidate your spec
3. `deploy` your changes and check the error that's logged.
You'll notice that errors are nested within their respective `name` as the key. For example:
 ```json
{
  "errors": {
    "workflows": {
      "workflow-one": {
        "jobs": {
          "first-job": {
            "body": ["Code editor cannot be empty."]
          }
        },
        "edges": {
          "webhook->first-job": {
            "condition_type": ["This field can't be blank."]
          }
        }
      }
    }
  }
}
```

## Notes for the reviewer
I need some hawk eyes in: https://github.com/OpenFn/lightning/pull/2173/files#diff-02e93bdaa66dc3a7f4e5d81498248bc08eebfc718db6159d00142b4e8dacc709.

I kind of implemented my own version of [Ecto.Changeset.traverse_errors/2](https://hexdocs.pm/ecto/Ecto.Changeset.html#traverse_errors/2). I just ripped open it's implementation and changed it to fit our usecase

## Related issue

Fixes #2140 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

### CODE REVIEW

**Review by christad92 — COMMENTED** [review]
tested and works. 
image

File: lib/lightning_web/controllers/api/provisioning_controller.ex [hunk 1]
```diff
@@ -21,17 +21,30 @@ defmodule LightningWeb.API.ProvisioningController do
...
+          |> put_status(:unprocessable_entity)
+          |> put_view(json: LightningWeb.ChangesetJSON)
+          |> render("provisioning_error.json", changeset: changeset)
+
+        {:error, error} ->
+          conn
+          |> put_status(:unauthorized)
+          |> put_view(LightningWeb.ErrorView)
+          |> render(:"401", error: error)
+      end
```
Comment (stuartc) [inline lib/lightning_web/controllers/api/provisioning_controller.ex:47]: Nice one, good spotting handling other errors like the limiter. 👍

File: lib/lightning_web/controllers/changeset_json.ex [hunk 2]
```diff
@@ -15,4 +16,124 @@ defmodule LightningWeb.ChangesetJSON do
...
+    %{errors: traverse_provision_errors(changeset)}
+  end
+
+  # inspired by: https://github.com/elixir-ecto/ecto/blob/v3.11.2/lib/ecto/changeset.ex#L4037
+  defp traverse_provision_errors(%Ecto.Changeset{errors: errors} = changeset) do
+    errors
+    |> Enum.reverse()
+    |> merge_keyword_keys()
+    |> merge_related_keys(changeset)
+  end
```
Comment (stuartc) [inline lib/lightning_web/controllers/changeset_json.ex:30]: Why not recursively use `traverse_errors`? I mean I see you said it was inspired by, could we not use it in this case - and recurse or does it expect atom keys or something?

**Review by christad92 — APPROVED** [review]

File: lib/lightning_web/controllers/changeset_json.ex [hunk 3]
```diff
@@ -15,4 +16,124 @@ defmodule LightningWeb.ChangesetJSON do
...
+        Map.put(acc, field, child)
+      end
+    else
+      acc
+    end
+  end
+
+  defp traverse_nested_changesets(changesets, child_name_func) do
+    Enum.reduce(changesets, %{}, fn changeset, acc ->
+      child = traverse_provision_errors(changeset)
```
Comment (stuartc) [inline lib/lightning_web/controllers/changeset_json.ex:125]: Since this function calls `traverse_provision_error` it's specifically for provisioning errors, but the name of the function calling it is pretty generic.

I'd suggest moving the Provisioning error functions into a separate module for now instead of loading up ChangesetJSON with model/domain specific functions.

**Review by stuartc — CHANGES_REQUESTED** [review]
This is great dude, and good job spotting the limiter errors.

Could you address my comment about moving the provisioning error specific functions.

I think this is different enough (and specific enough) to get it's own json renderer module, so instead of using `ChangesetJSON`, make a `ProvisioningJSON` module.

**Review by jyeshe — CHANGES_REQUESTED** [review]
@midigofrank as you've asked, I have done some tricky things (:
on jobs added an 'invented' credential:
```
jobs:
      Transform-data-to-FHIR-standard:
        name: Transform data to FHIR standard
        adaptor: '@openfn/language-http@latest'
        credential: 'invented'
```
on edges added a typo (`standart`) on the source_job:
```
edges:
      webhook->Transform-data-to-FHIR-standard:
        source_trigger: webhook
        target_job: Transform-data-to-FHIR-standard
        condition_type: always
        enabled: true
      Transform-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-SHR:
        source_job: Transform-data-to-FHIR-standart
        target_job: Send-to-OpenHIM-to-route-to-SHR
        condition_type: on_job_success
        enabled: true
```
on triggers played with webhook type to `cron` but I understand that the `webhook` might be just a label.
The output of `./priv/openfn/bin/openfn deploy -c config.json ` was:
Screenshot from 2024-06-05 12-20-54

full edited project.yaml:
```
name: openhie-project
# description:
# credentials:
# globals:
workflows:
  OpenHIE-Workflow:
    name: OpenHIE Workflow
    jobs:
      Transform-data-to-FHIR-standard:
        name: Transform data to FHIR standard
        adaptor: '@openfn/language-http@latest'
        credential: 'invented'
        # globals:
        body: |
          fn(state => state);
          
      Send-to-OpenHIM-to-route-to-SHR:
        name: Send to OpenHIM to route to SHR
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-upload-successful:
        name: Notify CHW upload successful
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-upload-failed:
        name: Notify CHW upload failed
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
    triggers:
      webhook:
        type: cron
        enabled: true
    edges:
      webhook->Transform-data-to-FHIR-standard:
        source_trigger: webhook
        target_job: Transform-data-to-FHIR-standard
        condition_type: always
        enabled: true
      Transform-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-SHR:
        source_job: Transform-data-to-FHIR-standart
        target_job: Send-to-OpenHIM-to-route-to-SHR
        condition_type: on_job_success
        enabled: true
      Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-successful:
        source_job: Send-to-OpenHIM-to-route-to-SHR
        target_job: Notify-CHW-upload-successful
        condition_type: on_job_success
        enabled: true
      Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-failed:
        source_job: Send-to-OpenHIM-to-route-to-SHR
        target_job: Notify-CHW-upload-failed
        condition_type: on_job_failure
        enabled: true
```

File: lib/lightning_web/controllers/api/provisioning_controller.ex [hunk 4]
```diff
@@ -21,17 +21,30 @@ defmodule LightningWeb.API.ProvisioningController do
...
-      |> render("create.json", project: project)
+        {:ok, project} ->
+          conn
+          |> put_status(:created)
+          |> put_resp_header("location", ~p"/api/provision/#{project.id}")
+          |> render("create.json", project: project)
+
+        {:error, %Ecto.Changeset{} = changeset} ->
+          conn
+          |> put_status(:unprocessable_entity)
```
Comment (jyeshe) [inline lib/lightning_web/controllers/api/provisioning_controller.ex:38]: :+1:

File: lib/lightning_web/controllers/changeset_json.ex (hunk 2 above)
Comment (midigofrank) [reply lib/lightning_web/controllers/changeset_json.ex:30]: `traverse_errors` is focused on the `error message` and not the `error key`. It keeps that `error key` to itself

**Comment by taylordowns2000** [comment]
> @midigofrank as you've asked, I have done some tricky things (: on jobs added an 'invented' credential:
> 
> ```
> jobs:
>       Transform-data-to-FHIR-standard:
>         name: Transform data to FHIR standard
>         adaptor: '@openfn/language-http@latest'
>         credential: 'invented'
> ```
> 
> on edges added a typo (`standart`) on the source_job:
> 
> ```
> edges:
>       webhook->Transform-data-to-FHIR-standard:
>         source_trigger: webhook
>         target_job: Transform-data-to-FHIR-standard
>         condition_type: always
>         enabled: true
>       Transform-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-SHR:
>         source_job: Transform-data-to-FHIR-standart
>         target_job: Send-to-OpenHIM-to-route-to-SHR
>         condition_type: on_job_success
>         enabled: true
> ```
> 
> on triggers played with webhook type to `cron` but I understand that the `webhook` might be just a label. The output of `./priv/openfn/bin/openfn deploy -c config.json ` was: Screenshot from 2024-06-05 12-20-54
> 
> full edited project.yaml:
> 
> ```
> name: openhie-project
> # description:
> # credentials:
> # globals:
> workflows:
>   OpenHIE-Workflow:
>     name: OpenHIE Workflow
>     jobs:
>       Transform-data-to-FHIR-standard:
>         name: Transform data to FHIR standard
>         adaptor: '@openfn/language-http@latest'
>         credential: 'invented'
>         # globals:
>         body: |
>           fn(state => state);
>           
>       Send-to-OpenHIM-to-route-to-SHR:
>         name: Send to OpenHIM to route to SHR
>         adaptor: '@openfn/language-http@latest'
>         # credential:
>         # globals:
>         body: |
>           fn(state => state);
>           
>       Notify-CHW-upload-successful:
>         name: Notify CHW upload successful
>         adaptor: '@openfn/language-http@latest'
>         # credential:
>         # globals:
>         body: |
>           fn(state => state);
>           
>       Notify-CHW-upload-failed:
>         name: Notify CHW upload failed
>         adaptor: '@openfn/language-http@latest'
>         # credential:
>         # globals:
>         body: |
>           fn(state => state);
>           
>     triggers:
>       webhook:
>         type: cron
>         enabled: true
>     edges:
>       webhook->Transform-data-to-FHIR-standard:
>         source_trigger: webhook
>         target_job: Transform-data-to-FHIR-standard
>         condition_type: always
>         enabled: true
>       Transform-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-SHR:
>         source_job: Transform-data-to-FHIR-standart
>         target_job: Send-to-OpenHIM-to-route-to-SHR
>         condition_type: on_job_success
>         enabled: true
>       Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-successful:
>         source_job: Send-to-OpenHIM-to-route-to-SHR
>         target_job: Notify-CHW-upload-successful
>         condition_type: on_job_success
>         enabled: true
>       Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-failed:
>         source_job: Send-to-OpenHIM-to-route-to-SHR
>         target_job: Notify-CHW-upload-failed
>         condition_type: on_job_failure
>         enabled: true
> ```

hey what was the expected output here? this looks good to me 👍

**Comment by midigofrank** [comment]
@jyeshe looks like you forgot to say yes to the deploy. That was a prompt asking you if you're sure to proceed.

**Comment by jyeshe** [comment]
> @jyeshe looks like you forgot to say yes to the deploy. That was a prompt asking you if you're sure to proceed.

Please have a second look at the image of the review:
image

**Comment by taylordowns2000** [comment]
ah nice!
- ok yes, credential is all good. no change here but certainly we want to continue to strengthen the CLI. (let's open an issue there.)
- on source_job_id, that's the behaviour i'd want the CLI to do, but i'm really curious what happened in the app. what does an edge look like without a source_job_id?

**Comment by midigofrank** [comment]
For some reason, I'm unable to deploy. I keep getting 401

**Comment by taylordowns2000** [comment]
> For some reason, I'm unable to deploy. I keep getting 401

i think roger had an old cli version, trying now.

**Comment by midigofrank** [comment]
@taylordowns2000 since the `source_job_id` isn't required, the changes just get saved. And we will have a dangling node

**Review by stuartc — APPROVED** [review]
